### ISSUE TITLE
Parameter.Delate node - multiple parameters/multiple families listing

### ISSUE THREAD

**Issue by EasternChill** [erfajo/OrchidForDynamo#10]
### Parameter.Delate node - multiple parameters/multiple families listing

Hi,
I am trying to make graph based on xls and your nodes connected with family documents. - which are real help and I thank you for as most of the community i guess. Using many threads with your support on dynamobim i solved most of the puzzles for my needs. creating multiple parameters for multiple families, setting multiple values and formulas all from xls file. 

Unfortunately I am stuck at delete node. I am trying to delete multiple parameters from multiple families without concern if they are in the family or not. This first part works, I received a list according to each family with parameters that are both in the family and on my delete list. Unfortunately no matter the levels of Parameter.Delete node I can't push it through. It works for one family or for many families with same parameter to delete set.

I send graph, excel and files.

Thanks in advance.

![obraz](https://user-images.githubusercontent.com/44380023/47317261-662d4680-d649-11e8-9bde-43310937f029.png)

![obraz](https://user-images.githubusercontent.com/44380023/47317623-60843080-d64a-11e8-97b6-435a685d6fd7.png)

[PARAMETER.DELETE.zip](https://github.com/erfajo/OrchidForDynamo/files/2503303/PARAMETER.DELETE.zip)

**Comment by erfajo** [comment]
if you need to take one document and delete a specific list of parameters, then you need to control the list level.
Setting the node to --> familydocument level 1 and parametername to level 2 should do it

**Comment by EasternChill** [comment]
Thank you for your replay. With level one for document and level two for parameters it aplies to one fanily only as you wrote. 

I cannot make it to apply  first list of param to first document, second list to second document etc. so it would batch delete parameters for many files.

**Comment by erfajo** [comment]
I might be wrong, then try with list level 2 for both... test the different options with list level, since that is the answer

**Comment by erfajo** [comment]
I am testing you files now...

**Comment by EasternChill** [comment]
I do the same,

maybe the out[0] is the problem..

my results till now:

lv1 vl1 saves one document and doesnt delete parameters
lv1 lv2 saves one document and deletes parameters
lv 1 lv3 saves one document and deletes parameters
lv2 lv1 seems to push one document of many through many times
lv2 lv2 doesnt seem to work - deletes parameter in one family but due to error doesnt save.

**Comment by EasternChill** [comment]
Yes,
Your solusion was good. it should be lv1 documents and lv 2 parameters, but i cut the results with out[0] node block whitch was unnecesery it seems.

I had good results before but i saved only one document.

Thank you

**Comment by erfajo** [comment]
Just by looking at your images that should be the answer... so i could not understand why this didn't work in the first place. maybe because of some of the other fails in your graph.

one important thing --> "false" is not false... remove the quote marks!
and you delete all except the last occurrence of "ParametrTestowy" in every file!?

lastly, please update your Orchid version :-)
![image](https://user-images.githubusercontent.com/2844374/47355220-15593480-d6c1-11e8-8dc0-8fc00f0914e5.png)

**Comment by EasternChill** [comment]
Again thank you, 

I'm a beginner, your answer didnt work in the first place becouce i added out[0] code block before save node. I used out[0] form your answers form dynamobim concerning other nodes but they were creatin illiteration by using same document mutiple times which is not the case here.

ParameterTestowy is test parameter and it is artificial scenario where i leave the last one :D

The aim is to list any parameters you want in excel file and to delete them in many families. It also checks if the parameters exist, otherwise it gets lots of errors. And after your comments it seems to work. I use it for a complicated over 100 shared paramtered families which needs changes in paramerters. It works really well together with your other nodes :)

I need to update both dynamo and orchid it seems :)
