### ISSUE TITLE
Follow up Issue #99: unresolved nodes

### ISSUE THREAD

**Issue by LPav66** [erfajo/OrchidForDynamo#100]
Revit: 21.0.0.383
Dynamo Core: 2.5.0.7460
Dynamo Revit: 2.5.0.7586
Orchid: 260

Hello Erfajo,

Follow up from issue #99 :
I've uninstalled Orchid, rebooted the computer, installed Orchid again, installed Orchid samples on _C:\Users\MyProfile\Documents\_, rebooted the machine again... Initialized Revit and opened one of your samples (_2021_changeMaterial.rvt_), initialized Dynamo and I've got the following:

![Material_2020-11-24_12-22-44](https://user-images.githubusercontent.com/42032849/100088099-f1dcb700-2e4f-11eb-86f8-54ee3c30a065.png)

As you may see, the nodes are unresolved. This happens with all the ***.dyn** files on the Orchid Samples folder. I'm sure that I've installed everything fine and the [error](https://github.com/erfajo/OrchidForDynamo/blob/master/error.md) page doesn't give me any other clue.

I'd really appreciate your help because at this point I even don't know if the problem is the installation or if it is something related to my poor abilities as an user ;-P . Also I'm attaching the Dynamo log and a notification below.

Thanks in advance!

Best greetings

**Here you may read the log:**

_Dynamo log started 2020-11-24 10:58:37Z
Python template set to default.
Dynamo -- Build 2.5.0.7460
Duplicate migration type registered for SunPathDirection
The folder 'C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid 260\definitions' does not exist
The folder 'C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid\definitions' does not exist
Dynamo will use the package manager server at : https://www.dynamopackages.com
Exception encountered scanning the package directory at C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid 260
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid 260
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid 260: 
 C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid 260\pkg.json contains a package without a header.  Ignoring it.
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid 260
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
Exception encountered scanning the package directory at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit
notification:Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit
   at Dynamo.PackageManager.PackageLoader.CheckPackageNodeLibraryCertificates(String packageDirectoryPath, Package discoveredPkg)
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates):
 Failed to load library: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit: 
 "A package called GenerativeDesign found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit could not be verified to have signed dll files.  A dll file found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit\bin\GenerativeDesignNodes.dll did not have a signed certificate.  Ignoring it."
Dynamo.Exceptions.LibraryLoadFailedException:
Failed to load library: C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages\GenerativeDesignRevit
   at Dynamo.PackageManager.PackageLoader.CheckPackageNodeLibraryCertificates(String packageDirectoryPath, Package discoveredPkg)
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)
The folder 'C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid 260\packages' does not exist
The folder 'C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid\packages' does not exist
DynamoPackageManager (id: FCABC211-D56B-4109-AF18-F434DFE48139) extension is added
Backup files timer is started with an interval of 60000 milliseconds
SYSTEM:Environment Path:C:\Program Files\Autodesk\Revit 2021\AddIns\SteelConnections;C:\Program Files\Autodesk\Revit 2021\en-US;C:\Program Files\Autodesk\Revit 2021;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files (x86)\Autodesk\Backburner;C:\WINDOWS\twain_32\ebscan;C:\WINDOWS\twain_64\ebscan;C:\WINDOWS\twain_32\erscan;C:\WINDOWS\twain_64\erscan;C:\Program Files\TOSHIBA\TOSHIBA e-STUDIO Client\TOSHIBA e-STUDIO AddressBook Viewer\Shared;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files (x86)\Infocert\DiKe 6\RAO;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Users\MyProfile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Autodesk\Revit 2021\AddIns\DynamoForRevit
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384;16384
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384;16384
DynamoManipulationExtension (id: 58B0496A-E3F8-43D9-86D2-94823D1D0F98) view extension is added
LibraryUI (id: 85941358-5525-4FF4-8D61-6CA831F122AB) view extension is added
NotificationsExtension (id: ef6cd025-514f-44cd-b6b1-69d9f5cce004) view extension is added
archilab (id: bdac5a46-fa1d-4aee-b34e-00778e30e779) view extension is added
Data Shapes (id: a14c2489-67e7-42ad-a328-5295bd6f2349) view extension is added
PackageManagerViewExtension (id: 100f5ec3-fde7-4205-80a7-c968b3a5a27b) view extension is added
Workspace References (id: A6706BF5-11C2-458F-B7C8-B745A77EF7FD) view extension is added
Welcome to Dynamo!
00:00:00.6370333 elapsed for loading Dynamo main window.
Preparing to load the library resources.
WPF Render Mode: SoftwareOnly
Saving C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN
Active view is now Splash Screen_

**I've got also the following notification:**

"**_Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\MyProfile\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid 260
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory, Boolean checkCertificates)_**"

**Comment by erfajo** [comment]
thanks for this report, I will look into this asap.

**Comment by erfajo** [comment]
Hi @LPav66,
If you read the error log, then you will notice that Orchid could not be found. You need to install it where your Revit 2021 finds it packages. since I can see you have a "Orchid 260" folder it looks like you are installing manually. If you install it by the executable then would the folder be named "Orchid" and most likely be installed in "%appdata%\Dynamo\Dynamo Revit\2.6\packages\Orchid"
Since you have a "\Dynamo Revit\2.5\packages\" path, it looks like you have not updated to the latest release from Autodesk, but the path should in this case only change from 2.6 to 2.5
next, inside Dynamo should you verify that dynamo looks at the given path!

**Comment by LPav66** [comment]
Hello @erfajo!

Thanks for your attention!

I took sometime and updated revit. Everything runs fine now.

Thanks again and best greetings!
