### ISSUE TITLE
Please Help "Warning Element. Set Parameter By Name operation failed."

### ISSUE THREAD

**Issue by aburefaei** [erfajo/OrchidForDynamo#101]
[](url)
Revit: 2021
Dynamo: 2.5.0.7

### Warning Element.SetParameterByName operation failed. No parameter found by that name.

(I have 1647 curtain panels in this project and I'm trying to randomize glass color for all of them, I have used this method so many times, and always works perfectly. but this time when I tried to use (SetParameterByName) only 595 panels selected and it says "No parameter found by that name." please help me)

![321](https://user-images.githubusercontent.com/74998776/100174088-d2d83680-2edc-11eb-9ffa-052064b59adf.JPG)
![Random Glazed_2020-11-25_05-03-39](https://user-images.githubusercontent.com/74998776/100174091-d4096380-2edc-11eb-8448-6b053523437a.png)

**Comment by erfajo** [comment]
I am sorry to say that the node "SetParameterByName" is a dynamo team node, not mine. In fact all nodes are from the dynamo team. You should put your question at the dynamobim forum.
However, When you add your issue to dynamobim forum, then I will suggest you add the graph file and a minimal version of your Revit file, so those who might want to help you have a chance to do it without reproducing your scenario.

**Comment by aburefaei** [comment]
Thanks
