### ISSUE TITLE
Bulk Add Shared Parameters Invalid Parameter Type Error

### ISSUE THREAD

**Issue by akrovance70** [erfajo/OrchidForDynamo#102]
###
[TWC Shared Parameters 2017.txt](https://github.com/erfajo/OrchidForDynamo/files/5655361/TWC.Shared.Parameters.2017.txt)

### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 19.2.20.24
Dynamo: 2.0.3.8810
Orchid: 204.1.4.7626

### The issue
Trying to build a graph that will bulk insert Shared Parameters into .rfa files. I get "_Warning: SharedParameter.Create operation failed. Invalid parameter type_" when I connect up my nodes to the _Orchid SharedParameter.Create_ or _SharedParameter.Add_ nodes.  I'm a bit new and feel that I'm missing something; any help troubleshooting would be appreciated. I hope I have attached my SP file, and the dynamo graph.  

![image](https://user-images.githubusercontent.com/58192053/101408426-008c8a80-38a2-11eb-94f1-476d327b93c4.png)

**Comment by akrovance70** [comment]
I think I figured it out... I needed to type all caps, no spaces in my parameter group to get it to work.

**Comment by erfajo** [comment]
Hi @akrovance70 
As far as I can see from your screendump you have two errors. The node turned yellow miss the type input and your group name is wrong (you miss an underscore).
...and instead of the "passthrough" node, you should use my "await" node.
