### ISSUE TITLE
Problem with Orchid-Installation

### ISSUE THREAD

**Issue by LadyBIM** [erfajo/OrchidForDynamo#103]
Hi I am using: 
Revit: 2020
Dynamo: 2.1

I have downloaded and installed all the Orchid version, but none of them work, when i open dynamo it keeps on showing just the "about" line. What might be the problem? why can't i install it?
![001](https://user-images.githubusercontent.com/75899232/101986178-c8fc5480-3c8c-11eb-8f3a-fcfbe435f4a9.JPG)
![002](https://user-images.githubusercontent.com/75899232/101986179-c994eb00-3c8c-11eb-9cfc-8006d6cb372d.JPG)

### The issue
(Fill in here)

**Comment by erfajo** [comment]
have you read the error handling page for assistance.
https://github.com/erfajo/OrchidForDynamo/blob/master/error.md

**Comment by LadyBIM** [comment]
I have solved by unpacking the zip file (version 200) and placing all the files in the same directory where I have the other packages installed.

**Comment by erfajo** [comment]
That is doable, another way would be just to move the files after installation to you folder or simply adding another folder to the search path inside dynamo.
![Snap001105](https://user-images.githubusercontent.com/2844374/102492451-00467900-4072-11eb-9953-dbc8828a71af.png)
