### ISSUE TITLE
Orchid not installed after Following the Installation Steps. 

### ISSUE THREAD

**Issue by caed99** [erfajo/OrchidForDynamo#104]
I Have Revit 2021 and Dynamo 2.5
I followed the steps for Dynamo Orchid 260. After that I proceded to open Dynamo but The Orchid Package is still only showing the Read Me node. 

I tried to unzip the .exe File with Winrar, and got the following error. 

I tried both extracting directly to the Dynamo packages Folder and extracting to a personal Folder and got the same error message. When I checked the Orchid Folder it seemed empty. 

Is there a way to fix it or did I missed a crucial Step?

Thanks in advance

![image](https://user-images.githubusercontent.com/75983823/102470993-41ab3a00-401a-11eb-95a3-3b944ac9f3e4.png)

**Comment by erfajo** [comment]
exe files are execuptables, you cant unzip such a file, you need to run the file.
try to read the error handling page for assistance.

**Comment by caed99** [comment]
I tried running the .exe file but the package is still showing the same ReadMe node. I'm sorry I missed that one, I read the instructions, you have a different folder for the Zipped files. I'm not that experienced to try the manual method. 
I have all the folders in the default location. I even re-installed Revit 2021 but got no success with Orchid. The Error Handling says that the Folders must be on the default location for the package to work.

**Comment by caed99** [comment]
I want to install it manually.
 I do understand the part that says to "unzip the zip-file of the chosen version into your dynamo package folder, into a folder named Orchid."  That is located in the Zipped Folder. I haven't tried that one. 

but I have issues with the step:
**"Download may be handled either by downloading a single file or by cloning or zipping the repository"**
Is that necessary for the Manual Installation?

**Comment by caed99** [comment]
**I find Orchid in** 
C:\Users\username\AppData\Roaming\Dynamo\Dynamo Revit\2.5\packages\Orchid

![image](https://user-images.githubusercontent.com/75983823/102479337-63112380-4024-11eb-8775-5ae3b5f03696.png)

**But there is no orchid on**
 C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.5\packages 

![image](https://user-images.githubusercontent.com/75983823/102479760-ed598780-4024-11eb-9916-12363d8eaf25.png)

**Comment by erfajo** [comment]
inside Dynamo is the path given for packages... what does this say? is it the same as one of the paths my installation makes?

130 --> 1.3, 200 --> 2.0, 230 --> 2.3, 260 --> 2.6
![Snap001105](https://user-images.githubusercontent.com/2844374/102491913-2e778900-4071-11eb-9158-d385a044b546.png)

If not, then either add the propper path or move the Orchid files. The reason to you do not have these folders could be that you are missing an update!

**Comment by caed99** [comment]
Hi @erfajo, I installed it manually. I followed the steps for the manual installation and it worked. 
I just followed the step you mentioned:
"unzip the zip-file of the chosen version into your dynamo package folder, into a folder named Orchid." That is located in the Zipped Folder.

I unzipped files to the folder named Orchid to a folder located in:
C:\Users\#Username\AppData\Roaming\Dynamo\Dynamo Revit\2.5 or 2.6

I think I added it to both 2.5 and 2.6.. I did not try cloning though I didn't understand that part.

Thanks for replying to my question

**Comment by erfajo** [comment]
The "cloning" part is a familiar term for Github users. At some time in your progression will you learn what cloning is :-)

**Comment by Batievskiy** [comment]
> I tried running the .exe file but the package is still showing the same ReadMe node. I'm sorry I missed that one, I read the instructions, you have a different folder for the Zipped files. I'm not that experienced to try the manual method. I have all the folders in the default location. I even re-installed Revit 2021 but got no success with Orchid. The Error Handling says that the Folders must be on the default location for the package to work.

Same problen here in 2024. Just installed Orchid from .exe. But in Dynamo is only one node "Readme"

**Comment by erfajo** [comment]
First, adding to an old issue, that is closed is not smart, please make your own issue where you can refer to this issue.
Next, before doing that, verify your folderpath for packages, open that folder and see if it should be the case that your folder is set up to an older version of Dynamo, which I will find most likely. Correct that and try restarting Revit and Dynamo.
