### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by MM1033** [erfajo/OrchidForDynamo#105]
Hello, 

I've tried everything to install this package on my computer with no luck. I have Revit/Dynamo version 2.5 and tried downloading and running the .exe for versions 2.6 and 2.3 of this package and neither work. It goes through the motions and installs them, but nothing changes in Dynamo as it still has the "Read Me" as the only node. I tried unzipping the Zipped contents of each version, separately, into the folder called "Orchid" within my package directory from Dynamo using your instructions, and by doing this, when I try and open Dynamo again, the Orchid package is removed from my list in Dynamo then has errors in my Manage Packages area and won't even let me uninstall it. How do I fix this?

**Comment by erfajo** [comment]
Version 260 will install the package in the Dynamo folder named 2.6 and 230 in 2.3 folder. Since you have 2.5, then you need to move the content from 2.6 (preferable) to 2.5. Dont use the 230 version in Revit 2021/Dynamo 2.5.
