### ISSUE TITLE
Problem with SharedParameter.Add

### ISSUE THREAD

**Issue by Antonio-Baroja** [erfajo/OrchidForDynamo#106]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2017.2.5 
Dynamo: 2.03.8811
Orchid: OrchidForDynamo_200 (downloaded 2020-01-12)

### The issue
Trying to add multiple paramaters to multiple families. With an older version of the package, node  worked but gave little error regarding lacing for grouping the newly created SP inside the families.

Updated Orchid to the latest version to see if it worked better 

and now the node doesn´t work:

![image](https://user-images.githubusercontent.com/70519035/104363809-049d6f00-5516-11eb-983b-66f991be8980.png)
The problem is with the first input (family document). Says it expects argument type "Document" but is getting instead "Orchid.RevitProject.Common.Document"

Thanks for your work and also thanks in advences in case you can help me

**Comment by Antonio-Baroja** [comment]
Ok. Restored with build 7125, as you advised in an older thread. 

Still have the problem with the grouping of the paramters, but at least Orchid works again. Thank you.

**Comment by erfajo** [comment]
Try to see the error message, you should have to look at your input.
Notice what can be called with a list, and what cant... then use list level to compensate for that

**Comment by Antonio-Baroja** [comment]
Hi, 

I´ll check it, but got no error message. 

Error was strange, only happended when two parameters had nearly the same name with diffrerent number siffux AND were diferent type. Probably list / level related but didnt happen with other groups of parameters.

Thank you
