### ISSUE TITLE
To get some parameters from a family folder

### ISSUE THREAD

**Issue by LauftLaterne** [erfajo/OrchidForDynamo#11]
Revit: 2019
Dynamo: 2.0
Orchid: 130.0.7
I'm trying to get some parameters from a family folder.

![imagen](https://user-images.githubusercontent.com/44639349/47784482-09dfbc00-dd06-11e8-9dd0-4fd2cb0cd948.png)
Thks

**Comment by erfajo** [comment]
Thanks for this error report, I have tested my nodes and I see a need for at least two new nodes and some refactoring of existing nodes. I am working on this and will return asap.

**Comment by erfajo** [comment]
I have build two new nodes and recoded the getter and setter nodes, please download the newest executable, the version is 132.3.6.6880 / 201.3.6.6880

In the samples can you find this graph (SetGetParameter.dyn)
![setgetparameter](https://user-images.githubusercontent.com/2844374/47921296-83b5a800-deb4-11e8-92bd-5a1f6622ee56.png)

**Comment by LauftLaterne** [comment]
Thks Erik.

**Comment by erfajo** [comment]
https://github.com/erfajo/OrchidForDynamo/tree/master/Samples
