### ISSUE TITLE
Add Shared Parameters in Family Doc Issue

### ISSUE THREAD

**Issue by MM1033** [erfajo/OrchidForDynamo#110]
I'm getting the following error with my graph. Not sure why it's not liking the YesNo parameter value. It is indeed a valid parameter type in Revit. Any ideas?
![image](https://user-images.githubusercontent.com/74573553/108280099-8777a200-7132-11eb-9281-905dd560c278.png)

**Comment by erfajo** [comment]
First is it an outdated version of Orchid you are using. By the way, you didn’t write any of the required information I ask for, however, I do recognize that the node layout is old.

Next, it looks like you are feeding the node with list values. that in itself is not the way the node is designed, however, with list level is it doable to feed it with lists where it takes single values.

Lastly, I did test if my nodes should have any kind of issues with YesNo parameters, either by creating or adding, and I could not replicate any errors. Try to see the below illustration.

I am afraid that the best advice I can give is, please update your Orchid version and then try to revise your graph once more.
![image](https://user-images.githubusercontent.com/2844374/108324661-7b3e2400-71c8-11eb-92a8-b6cb37506f38.png)

**Comment by MM1033** [comment]
I downloaded the 260 version from your Builds area, which looks like the latest available, and because of my dynamo version (which I have no control over updating), I had to move the files after running the .exe from 2.6 in my Package Manager to folder 2.5 as you helped me do in my last issue request. Anyways, I changed everything to feed the Parameters node using list@levels and removed the YesNo parameters from the excel list and now I still get the same error but with "Force".

**Comment by erfajo** [comment]
Right, why do you then feed it with a type value?
I removed "type" from "Adding an existing shared parameter since that value is present in the SP file. Only when creating a new SP do you need the type.
Please see the illustration, I picked both the Add and the Create node to illustrate the difference.
Have you also notices the new AddByFile node?

**Comment by MM1033** [comment]
updated based on your graph above by removing the "type" and it works now. thank you
