### ISSUE TITLE
"Parameter.Associate" - Looks like it's not working properly.

### ISSUE THREAD

**Issue by HAIDCH** [erfajo/OrchidForDynamo#113]
Revit: 2020
Dynamo: 2.3
Orchid: for Dynamo 2.3

### The issue
Hi, Erfajo!
I'm using your package and I'm having problem with "Parameter.Associate".
I want create material parameter for multiple families from project. I created and set value parameter, but I didn't associate parameter with element parameter. I have observed the problem and found that:
- First time, I run and warning.
- Second time, I disconnect "element" port of Parameter.Associate, and run.
- Third time, I connect "element" port again. It was finally successful.
I hope you understand my explains.
I would like to attach the test files. 
Thanks and kind regards.

![Gán Thông tin Element từ Project - Material_210309_2021-03-22_11-09-47](https://user-images.githubusercontent.com/81027744/112021892-5856b500-8b64-11eb-8a1f-55ecfb765562.png)
[Parameter_Associate_Test.zip](https://github.com/erfajo/OrchidForDynamo/files/6183681/Parameter_Associate_Test.zip)

**Comment by erfajo** [comment]
I will try to see your graph.

**Comment by erfajo** [comment]
All my nodes worked perfectly, however, your usage of it did not... more precisely was your problem the two nodes which was not Orchid nodes the problem. You cant get the extrusion in the way you tried.
![Gán Thông tin Element từ Project - Material_210309](https://user-images.githubusercontent.com/2844374/112104081-02593000-8bab-11eb-94cb-c14e52be1f4f.png)
remove .txt from filename.
[Gán Thông tin Element từ Project - Material_210309.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/6187428/Gan.Thong.tin.Element.t.Project.-.Material_210309.dyn.txt)

**Comment by HAIDCH** [comment]
Hi, Erfajo! Thanks for your reply!

I tried your option, but it's empty list at "All Elements of Type" node. I don't understand.
Thanks and kind regards.

![Gán Thông tin Element từ Project - Material_210309_2021-03-23_01-59-49](https://user-images.githubusercontent.com/81027744/112106990-fd16d800-8be0-11eb-9518-9139eaa932dc.png)

**Comment by erfajo** [comment]
It worked perfectly for the textbox you attached in the first post. You need to find a way to get the component/object you want to attach a material parameter to. First when you have this component/object are you able to associate a parameter. Try to examine your families what they contain in the individual family files, before you try to do it automated in a project file.

**Comment by HAIDCH** [comment]
Hi, Erfajo! Thanks for your reply!
I will try with your suggestion. Please don't close this issue until it's finished. I will respond.
Thank you very much!

**Comment by HAIDCH** [comment]
Hi, Erfajo!

I can't actually get members in family from project by your option, while, i can get them by "ʳʰʸᵗʰᵐ|Collector.ElementsOfTypeInDocument" node. But this node is not compatible with "Parameter.Associate".

Thanks and kind regards.

![Snipaste_2021-03-23_16-14-02](https://user-images.githubusercontent.com/81027744/112123459-ddd57600-8bf3-11eb-9582-111e268b0285.png)

**Comment by erfajo** [comment]
yes it is, the problem is that is is handed to you as a list. try add "list.firstitem" or something like this. you can also take a codeblock at type "t[0]". that should work.
However, I dont understand why the rhythm node can give you the extrusuon while all elements of type cant. I will try to see why, and then code the missing node so you dont need any other nodes than mine.
which family did you test it in from your testfile?

**Comment by HAIDCH** [comment]
I have tried both ("list.firstitem" and code block), bbut it didn't work.
I will wait for your update.

Thanks and kind regards.
![Gán Thông tin Element từ Project - Material_210309_2021-03-23_06-59-18](https://user-images.githubusercontent.com/81027744/112144464-d6ba6200-8c0b-11eb-82bf-f57518640533.png)

**Comment by HAIDCH** [comment]
"when you invoked the graph you will NOT be able to see any output from the "All Elements of Type" node due to you run this on a file in the background, and finally load the result into your project file... by doing this you will empty the memory from the background file (remember to close the background opened files!)".
I did not understand this well, and did not heed it. So how it works correctly?
Simply, I open project contain this family, i want create and associate parameter family from project.
Besides, before run dynamo, I tested family's properties, like the picture you sent, have no parameter. After run dynamo, family have new parametrer "MA", like the picture you sent.
But, carefully, you try change material to know if the family has changed or not.

Thanks and kind regards.

**Comment by erfajo** [comment]
I dont understand what you are writing!?
Do you not understand what the graph is doing or...!?
What ever you are doing on those families, is it done as background opened files which you cant see. They are only loaded into memory, byt they will remain opened until you close the files again. Whatever you are doing is therefore only available in memory, and should not be revealed to the user.
If you want to follow what is being done, then open a family and see what it is doing... this way you can follow all steps.
However, working on families as a bulk operation, you need to work with loading them into memory, and closing them again. this is how it is done!

**Comment by HAIDCH** [comment]
I understood.
I will explain more clearly.
I am creating box from multiple room in project by "Family Instance By Geometry" of Springs. Then, I want create material parameter and associate that parameter with element parameter of family from project. So, I used your nodes.
I hope you understand my explains.

Thanks and kind regards.

**Comment by erfajo** [comment]
yes, and that is why whatever you want to, will be processed in memory... 
you should folow the concept shown in the samplefile "OrchidForDynamo/Samples/Graphs/Families/Collect families in project.dyn"
![Collect families in project](https://user-images.githubusercontent.com/2844374/112175832-dd3ede80-8bf7-11eb-90da-d2698af6b50a.png)

**Comment by HAIDCH** [comment]
I will trying your sample file, then, i will respond.

Thanks and kind regards.

**Comment by erfajo** [comment]
I have closed the issue long ago, since all nodes worked as expected. If you want more help in learning how dynamo work I have to forward you to the dynamobim forum. this is the helping forum for users.

**Comment by HAIDCH** [comment]
I know https://forum.dynamobim.com/. But i cannot sign in forum. So, I can't post my problem.
I create parameter and set value, but I still not associate parameter. I don't understand.

Thanks and kind regards.

**Comment by erfajo** [comment]
get in touch with Autodesk, and get your account fixed.

**Comment by HAIDCH** [comment]
Thanks for your help!
