### ISSUE TITLE
Parameter.SetValue not picking up correct values

### ISSUE THREAD

**Issue by HoyosJuan** [erfajo/OrchidForDynamo#116]
Hi!

I'm trying to delevop a batch family updater and orchid has helped me a lot (is the only package I am using for this). Everything seems to be ok, until I try to update the parameter values from several types in one single family. Below is the screenshot of the part that I am getting troubles with; the node executes without warnings and the values are set, but not the correct ones altough I am feeding the inputs with the correct values for each family type. Any suggestions on this? Thank you so much!

![Batch Family Updater Problem](https://user-images.githubusercontent.com/84806689/119550975-afdcf100-bd5e-11eb-901a-b5729bcdf7b2.png)

Revit: 2020.2
Dynamo: 2.3.0
Orchid: 203.3.0.7800

**Comment by erfajo** [comment]
First, try to use the camera upper right, zoom into some few nodes and use the camera, this gives a better resolution.
next, I am not sure what you are trying to do, but are you familiar with list level?
If I should try to help you further, then please provide med with the bare minimum as a zip-file (rename extension if needed), I need at least two families and the graph file.
AND please try to describe what you expect as an output.

**Comment by HoyosJuan** [comment]
Hi,

The resoulution is ok if you open the screenshot by clicking on it. Yes, I have used list at level in several parts of this script. Im trying to update family parameters from Excel. Here is the zip with the files: [Batch Family Updater.zip](https://github.com/erfajo/OrchidForDynamo/files/6541995/Batch.Family.Updater.zip). The first node of the script ask you for the Excel file, and in the first column of the Excel file are the paths to the families you want to update, you need to change those fileds with the ones from your PC after you download the files. The output is just the family with the parameters updated by the excel file, as described in the first post.  Any help would be appreciated, let me know if you need more explanation. Thanks.

**Comment by erfajo** [comment]
Your former image does now show everything, it is narrowed down to a few nodes... this is why the camera solution is much better to use than screendumps.

...And sorry, but I dont hope you have send a script!? 
I work with graphs and compute graphs!? However in very very few cases do I make scripts inside code blocks and even more rare if I use a python script node. Scripting is low technology only supposed to be used when the complexity is very low.

I will try to see what you have zipped and hope it contains a graph and not a script.

**Comment by erfajo** [comment]
It looks like you have removed the zip file and have not provided a new file. I presume you have solved the problem and will close this issue
