### ISSUE TITLE
"IFC Settings" node is unclickable in dynamo 2.6

### ISSUE THREAD

**Issue by CongzhengZOU** [erfajo/OrchidForDynamo#117]
### Revit, Dynamo and Orchid version
Revit: 2021
Dynamo: 2.6.1
Orchid: OrchidForDynamo_206.exe

### The issue
Hi, I appreciate you great work very much, it's just incredible. Here is a simple issue to discuss with you.

1.  **download OrchidForDynamo_206.exe** from https://github.com/erfajo/OrchidForDynamo/blob/master/Builds/OrchidForDynamo_206.exe
2. Install .exe and open revit 2021 then **open dynamo**
3.  first issue is a warning saying "Dynamo.Exceptions.LibraryLoadFailedException: Echec du chargement de la bibliothèque: C:\Users\CongzhengZOU\AppData\Roaming\Dynamo\Dynamo Revit\2.6\packages\Orchid\bin\OrchidIB.dll"
it says **Failed to load libraryOrchidIB.dll** 
4. I don't know what it means and there is no similar issue on the internet, so I started to try the IFC nodes. Here is the second issue, I found out that **"IFC Settings" node is unclickable**.
5. Furthermore, I wanted to export IFC with my own configuration, as shown in the image, it seems like "IFC versions" node can not find the imported or new created configuration in revit ? If is true, one of my idea for the solution is to add these additional configuration in the script, so I give the string input to IFCversion, it can find the related configuration. 
![IFC_configuration](https://user-images.githubusercontent.com/70321029/120344192-aa048400-c2f9-11eb-9c53-ba250c4f170b.JPG)

**Comment by erfajo** [comment]
I cant reproduce your error, so something in you environment is giving you an error. You can try to move the other packages somewhere else, while trying to see if you will be able to load Orchid. If this works, then you need to figure which other package might be the problem. A well known error is if some of the other packages does ship their package with common assemblies. This is something no-one should do, but it does happen...

You own schema cant be selected, this is why you can export it, and then use the export setting as data setting when importing. Try to see the sample files for this solution.

**Comment by CongzhengZOU** [comment]
Hi, thanks for your reply. It still saying **Failed to load libraryOrchidIB.dll** after I move all other plugins outside the folder, even reinstall Orchid, reboot PC didn't change the warning.

**Comment by erfajo** [comment]
just to be sure, you have the latest version of the IFC exporter
https://github.com/Autodesk/revit-ifc/releases

**Comment by CongzhengZOU** [comment]
YES ! It worked on revit 2022. Thanks a lot.

**Comment by erfajo** [comment]
Sounds good, I found that the error was due to an update I made in the installer, it was not the assemblies og any code in generel :-S
