### ISSUE TITLE
OrchidlB.dll fails to load 

### ISSUE THREAD

**Issue by Robbert2308** [erfajo/OrchidForDynamo#119]
### Operating system
Windows 10

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 21.1.21.45
Dynamo: 2.6.1.8786
Orchid: 203.3.0.7829

### What did you do? 
Download the ZIP version, unpacked and moved to local packages folder.

### What did you expect to see?
Orchid nodes in Dynamo, no warnings/ notifications

### What did you see instead?
This notification:
Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\temp_BIM\Packages 2021\Orchid_206_Revit\bin\OrchidIB.dll

Failed to load library: C:\temp_BIM\Packages 2021\Orchid_206_Revit\bin\OrchidIB.dll

Build error for library: C:\temp_BIM\Packages 2021\Orchid_206_Revit\bin\OrchidIB.dll
Could not load file or assembly 'IFCExportUIOverride, Version=21.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by erfajo** [comment]
...and you have installed the IFCexporter?
https://github.com/Autodesk/revit-ifc

**Comment by Robbert2308** [comment]
Just updated the IFC exporter to latest version. This indeed resolved the problem. Sorry, I thought in Revit 2021 the IFC exporter was installed out of the box…


Thanks for your help.


Met vriendelijke groet,
Robbert Ploegmakers
BIM Regisseur

M +31 6 - 829 21 640  |   E ***@***.***


Het Cluster Bedrijfshuisvesting van Janssen de Jong Groep bestaat uit:
***@***.***D761C3.8A9D7190]<https://www.hercuton.nl/>     ***@***.***D761C3.8A9D7190] <https://www.remco.nl/>      ***@***.***D761C3.8A9D7190] <https://woodybuildingconcepts.nl/>      ***@***.***D761C3.8A9D7190] <https://www.servicebouwplus.nl/>      ***@***.***D761C3.8A9D7190] <https://www.pvvt.nl/>      ***@***.***D761C3.8A9D7190] <https://www.remco.nl/en/>      ***@***.***D761C3.8A9D7190] <https://www.ocmer.com.pl/>

**Comment by erfajo** [comment]
I thought that this was the case... The built-in IFC exporter is very limited, and I dont know anyone who would rely on that. Why Autodesk haven't deprecated their own yep, since they also own/supply the opensource IFC exporter...
