### ISSUE TITLE
Can’t install Orchid Package - Revit 2021 Dynamo 2.6.1. - to create shared parameters 

### ISSUE THREAD

**Issue by Mishkt** [erfajo/OrchidForDynamo#120]
Hi, I have a problem with installing the Orchid Package for Dynamo.

Here is my version of Dynamo:

![version](https://user-images.githubusercontent.com/67702373/122031548-1a69d580-cdcf-11eb-99ef-3b8e80720a0c.PNG)

And here the files in Orchid Github folder.

![orchid](https://user-images.githubusercontent.com/67702373/122031593-23f33d80-cdcf-11eb-97ab-8865ece9ca86.PNG)

I’ve tried to install each of them (and Samples as well), but none of the installation files was working for Dynamo 2.6.1.

Is it possible to install Orchid Package in Revit 2021 for Dynamo 2.6.1.? What am I doing wrong?

I am trying to create shared parameters for Door family. Dynamo Component for creating shared parameters didn’t work.

Here a some screenshots:

![Dynamo_2021-06-15_10-02-07](https://user-images.githubusercontent.com/67702373/122031647-2f466900-cdcf-11eb-8cf7-57b633406f53.png)

![shared_param](https://user-images.githubusercontent.com/67702373/122031669-340b1d00-cdcf-11eb-8587-522656d8fa17.PNG)

**Comment by erfajo** [comment]
The 206 version is for dynamo 2.6.x versions and Revit 2021...
...and you have read the [https://github.com/erfajo/OrchidForDynamo/blob/master/error.md](Error Handling) page!?

**Comment by Mishkt** [comment]
Thank you @erfajo! I have read the Error Handling page (I didn't see it before - sorry) and I could solve my issue by changing the Node and Package path

**Comment by ZhaohanbingResearch** [comment]
I can not run the 212.exe on my office computer, even connecting with my own hotspot.  I don't know if should run it as administer.
![image](https://github.com/erfajo/OrchidForDynamo/assets/124351171/04bfe6c3-f94b-4673-a61d-156e03e412c7)

**Comment by erfajo** [comment]
If the file is corrupted, then download it again... When I tried to download I did not have any issues other than I need to force that I will run the installer, but that is due to I don't have any certificate I can use for my freeware tools.

BUT, next time you want to put up a question, then please make a new issue/post, in that post, you can refer to any other posts, also closed posts.
