### ISSUE TITLE
Link Revit Files from BIM360/ACC

### ISSUE THREAD

**Issue by Chrono9084** [erfajo/OrchidForDynamo#121]
Your model linking nodes are great.  Unfortunately, all of our projects reside on BIM360/ACC these days which (unless I am missing some functionality) renders these nodes unusable.  I am not even sure there is a way to do this with Dynamo but if we had the ability to link models from BIM360/ACC it would be amazingly helpful.  The ability to query models from a folder on BIM360/ACC in order to add them in bulk would be even better!

I currently have a few multi-discipline/multi-model projects where the amount of models for each project surpass 20 and this workflow is not going to change unfortunately.

Thank you for your hard work!

**Comment by erfajo** [comment]
I have actually thought the same... so I am working on it :-)

**Comment by erfajo** [comment]
I have tried to build new nodes for "Link", however, I am taking my summer vacation, so I dont have network capacity to test BIM360 links... could you try this out?
please try to give me som screendumps with the issues you meet :-)

**Comment by Chrono9084** [comment]
Will do.  Thanks!

**Comment by Chrono9084** [comment]
> I have tried to build new nodes for "Link", however, I am taking my summer vacation, so I dont have network capacity to test BIM360 links... could you try this out?
> please try to give me som screendumps with the issues you meet :-)
> 

Any chance you could direct me to where these nodes live?  I am having a hard time locating them.  I am probably just missing something.

**Comment by erfajo** [comment]
sorry but I am taking my vacation, so not everyday am I checking github :-)
link nodes are placed where they used to be (RevitProject, Common, Link), and are named the same... it is inside the code for the node I have updated it. however, I tried to test my nodes on som modles I have on my computer, but links pointing towards BIM360 demands online access, which I dont have in that amount at the time away from office. So thos links failed... I simply dont know if the code works!? :-)

**Comment by Chrono9084** [comment]
> sorry but I am taking my vacation, so not everyday am I checking github :-)
> link nodes are placed where they used to be (RevitProject, Common, Link), and are named the same... it is the code inside the node I have updated. However, I tried to test my nodes on som models I have on my computer, but links pointing towards BIM360 demands online access, which I dont have in that amount at the time away from office. So those links failed... I simply dont know if the code works!? :-)

I guess if you could just point me in the right direction in terms of what I am supposed to put in as the file in order to pick up a BIM360 hosted file.  Are we talking about a straight URL to the file?  Something like: BIM 360://project name/Project File/SomeProject.rvt?

**Comment by erfajo** [comment]
yes thats what we are talking about, and I have implemented code which should be able to reach that...
in my sample collection do I have a graph which might help you... as usual :-)
https://github.com/erfajo/OrchidForDynamo/blob/master/Samples/Graphs/Projects/LinkedDocument.dyn

**Comment by Chrono9084** [comment]
So first I tried to use you nodes to get link.info for an existing BIM360 linked model and got this:
![image](https://user-images.githubusercontent.com/37596510/126079465-ff482f30-31a2-4429-8ad0-9ee582814c34.png)


Then I tried linking a new BIM360 model in and go this:
![image](https://user-images.githubusercontent.com/37596510/126079436-29f96f18-5d11-4425-afd2-f6fd4af315e3.png)

I think I might be doing something incorrectly but please let me know.  :)

**Comment by erfajo** [comment]
I can see that i need to have net so i can test it properly... I will return when I have any news

Få Outlook til Android<https://aka.ms/ghei36>

________________________________

**Comment by Chrono9084** [comment]
> I can see that i need to have net so i can test it properly... I will return when I have any news

Sorry that I couldn't be more helpful!  :(

**Comment by erfajo** [comment]
I have now solved the problem of getting the info from cloud based files, however, there is no API support for creating links. this is on the road map for the Revit team.
![LinkedCloudDocument](https://user-images.githubusercontent.com/2844374/127191769-4e87dc8e-849e-4cad-85e2-6b3ac53cd464.png)
