### ISSUE TITLE
FamilyType.GetNested throwing error after recent update (possible bug?)

### ISSUE THREAD

**Issue by Chrono9084** [erfajo/OrchidForDynamo#123]
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 22.0.2.392
Dynamo: 2.10.1.4002
Orchid: 210.1.0.7829

This is happening in all versions though.

### What did you do? 
I have a graph that you run in a project.  It asks you to select a family (in this case a titleblock) and checks to see if two nested family types are present.  It has been functioning fine for a few years but after I recently updated to the newest version of your package the FamilyType.GetNested node is complaining about an incorrect argument type.  It says it expect Orchid.RevitProject.Common.Document, bool but is being called with Autodesk.Revit.DB.Document, bool.

I played around with it a bit thinking that it might have something to do with the ever-changing API but no combination of nodes seem to work so I am tossing it your way just in case it is a bug.

![image](https://user-images.githubusercontent.com/37596510/125216992-46209400-e285-11eb-81bf-fa1d33130558.png)

**Comment by erfajo** [comment]
It is not a doable family document you are sending to my node, It need to be a Orchid type of a family document.
