### ISSUE TITLE
Adding Shared Parameter based on Family type?

### ISSUE THREAD

**Issue by clausneergaard** [erfajo/OrchidForDynamo#124]
### Revit, Dynamo and Orchid version
Revit: 2022
Dynamo: 2.10.1
Orchid: 210

### The issue
Hello –

I have a topic that I’ve struggled a bit with, to which I hope that someone in here could help me tackle.

Here goes;

I want to be able to have a Shared Parameter file, which has all the groupings corresponding to all the Family types. This, I have created. When adding a Shared Parameter manually, I need to select the category / grouping, and then add each of the parameters individually. This, I can skip by using the Orchid-package (@erfajo), which is really great.

Next step for me is, I want the Dynamo-definition to go in, read which Family-type it is that I am working on (is it a Door-family, is it a Window-family, is it a Furniture-family, is it a Mass-family, etc.), and then the definition should go in under the equivalent group-name in the Shared Parameter-file, and add all of these Shared Parameters.

What I’ve managed to do is to extract the Family-type of the currently open Family (i.e.; Door, Window, Furniture, Mass, etc.), as a String. Now I can use this String as a “selector” for my Shared Parameter-category, without having to do it manually, which, experience-wise, could be pretty error-prone. All-in-all, from my perspective, this could be a nice way to keep all the Shared Parameters in one file, and then, by just running the Dynamo-definition in each new family-definition, I can add all of the relevant Shared Parameters under the current Family-category.

The above is definitely possible, as the definition succeeds with many of the groups - but the thing is, I get some yellow nodes on some of the parameter-groups, more specific;

PG_AREA
PG_PRICE

I hope that this makes sense? Are there differences between some of the groups? Could this be the reason? Or maybe I am just missing something.

All thoughts are appreciated, and please see attached definition to this post (which, by the way, should come with a “quite-messy”-warning, as I’ve been trying out a lot of stuff).

Cheers!

[WORKS - DYNAMO-SCRIPT-WORKING-SO-FAR_2021-06-21_03-58-05 - ANNOTATED](https://user-images.githubusercontent.com/7966833/125254000-4eff7d00-e2fa-11eb-8dd1-28f9c42bb29f.png)

[SHARED PARAMETERS.txt](https://github.com/erfajo/OrchidForDynamo/files/6799726/SHARED.PARAMETERS.txt)

[DYNAMO - ADDING SHARED PARAMETERS BASED ON FAMILY-TYPE.dyn.zip](https://github.com/erfajo/OrchidForDynamo/files/6799733/DYNAMO.-.ADDING.SHARED.PARAMETERS.BASED.ON.FAMILY-TYPE.dyn.zip)

**Comment by erfajo** [comment]
Hej Claus,
Er denne til mig? eller er det en kopi af et indlæg du har lavet?
smid evt. selve graf filen, fremfor et billede. Jeg kan se du anvender min eksempel samling, så jeg bude kunne teste selv :-)

**Comment by stevievwkelly** [comment]
I'm using Revit 2020 and Dynamo 2.3 to add shared parameters to families already in my project. It's not working for me so far. Do you have an example for this situation in this version of Revit and Dynamo?
![image](https://user-images.githubusercontent.com/31353130/127671610-d6f25506-9bfc-4df5-b818-9be03a045c75.png)
![image](https://user-images.githubusercontent.com/31353130/127671676-12aa5623-79d9-49ba-ac51-b53431ef0faf.png)

**Comment by erfajo** [comment]
@stevievwkelly, have you tried to see the samples provided? There are graphs available for family issues, and among these, graphs for shared parameters.

**Comment by stevievwkelly** [comment]
Yes, I did, but they are in an older or newer version, so my version doesn’t have all those nodes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by erfajo** [comment]
All nodes for familydocuments are the same in all versions. There has not been developed any news for that area from the Revit team in many years. However, there are some few news for nested elements primarily images. Parameters has not been updated. I can see that you refer to the danedu package, and since then has many things been updated.

**Comment by clausneergaard** [comment]
Hello all -

Thanks for replying, and thanks to you @erfajo, for responding. I am unsure if I should write this in english or danish, so I am gonna go with the english version. Also, I apologize for the delayed response, due to the summer vacation and lack of internet where I am currently finding myself.

I'll try and post the Dynamo-definition, with the risk of showing how messy it is :-)

[DYNAMO - ADDING SHARED PARAMETERS BASED ON FAMILY-TYPE.dyn.zip](https://github.com/erfajo/OrchidForDynamo/files/6913377/DYNAMO.-.ADDING.SHARED.PARAMETERS.BASED.ON.FAMILY-TYPE.dyn.zip)

Hope this makes sense, and it is still about the following groups (at least, that I've noticed).

PG_AREA
PG_PRICE

Thank you!
Best,

**Comment by erfajo** [comment]
well, then we are two taking our vacation :-)
...and since we both were Danes, could we do it in our native language, however, English is also fine :-)
but, we are rather closely connected Claus, so please write me an email, you know the address :-)

I/we can bring the solution here, before the issue is being closed :-)
