### ISSUE TITLE
Cannot see all node included in package, failed load library

### ISSUE THREAD

**Issue by joeyosky** [erfajo/OrchidForDynamo#125]
Revit: 2020.2
Dynamo: 2.3.0.6270
Orchid: 203.3.0.7878

Downloaded the orchid package no problem but while building a script I tried looking up the "Parameter .AddSharedParameter" node and could not find it in the package. Then realized I had a flag in the notifications pointing to the following error:
---
Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\7Pro64\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Orchid\bin\OrchidIB.dll
(show details)
Failed to load library: C:\Users\7Pro64\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Orchid\bin\OrchidIB.dll
----
I tried reinstalling the package with the .exe file and the problem keeps coming up, tried manually installing it and still get the same error, it seems I can see/use most of the nodes in the package but not all of them, for example, the one I previously mentioned.
I tried messing with the package node paths manage, adding more specific file paths and still have no luck.

Please advise!

**Comment by erfajo** [comment]
First of all, it this your first installation of Orchid? if so, have you tried to see the page describing possible errors. You can access it from the frontpage.
https://github.com/erfajo/OrchidForDynamo/blob/master/error.md

If you have had Orchid up and running lately until this recreantly update, then I will try to see if something new has happen since last update I made a week ago or so.
- and by the way, is your username "7Pro65" on you computer, or is something else not working?

**Comment by zeonchameleon** [comment]
Hi!

I have the same issue.

Revit 2022.1
Dynamo 2.12.0.5650
Orchid 212.1.0.7950

Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\Vlad\AppData\Roaming\Dynamo\Dynamo Revit\2.12\packages\Orchid\bin\OrchidIB.dll
-
Failed to load library: C:\Users\Vlad\AppData\Roaming\Dynamo\Dynamo Revit\2.12\packages\Orchid\bin\OrchidIB.dll

(Show Details)
-
Build error for library: C:\Users\Vlad\AppData\Roaming\Dynamo\Dynamo Revit\2.12\packages\Orchid\bin\OrchidIB.dll
Could not load file or assembly 'IFCExportUIOverride, Version=22.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Не удается найти указанный файл.

-------
I don't know, why the error message is partly in Russian ))) My language is Russian, but I set the locale of Revit to English for this report. The last sentence is "Failed to locate the file"

I have removed all other Dynamo packages for testing, but the error still occurs. Also, what might be important, right now I am testing several add-ins for Revit. So I install and remove them a lot, and in some combinations I have "System.IO.FileLoadException" in Dynamo. And I think it's Ok. But I never had the "Failed to load library" error before I installed the last version of Orchid.

I hope this will help to find the solution.

**Comment by zeonchameleon** [comment]
> Failed to load library: C:\Users\Vlad\AppData\Roaming\Dynamo\Dynamo Revit\2.12\packages\Orchid\bin\OrchidIB.dll

BTW This location is correct and the file exists

**Comment by erfajo** [comment]
First: Do NEVER reply on another issue, this is destroying any the issue someone else has reported!!!!

The error message describes that you have an error in relation to "IFCExportUIOverride, Version=22.2.1.0", I have coded my nodes for "IFCExportUIOverride, Version=22.3.0.0".
Please try to get the latest IFC export --> https://github.com/Autodesk/revit-ifc
