### ISSUE TITLE
MaterialThermal Create with Orchid 210 and Revit 22 not work

### ISSUE THREAD

**Issue by rolfarchi** [erfajo/OrchidForDynamo#129]
Hi Erik Falck,

### Operating system
Windows 10

### Revit and Dynamo version
Revit: 22.0.2.392
Dynamo: 2.10
Orchid:  210.1.0.7927

Best regards to Denmark

Rolf

[error.jpeg.txt](https://github.com/erfajo/OrchidForDynamo/files/7189612/error.jpeg.txt)
[Material Thermal Create.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/7189973/Material.Thermal.Create.dyn.txt)

**Comment by erfajo** [comment]
I will look into this asap

**Comment by rolfarchi** [comment]
Many thanks for the quick response :-)

**Comment by erfajo** [comment]
I am so sorry, the error is entirely my fault... It is one of those errors which should never happen, I have no excuse for this, other than Murphy's First Law: Anything that can go wrong will go wrong.
Please download the updated package, and please forgive this rookie error.

**Comment by rolfarchi** [comment]
Hi Erkik Falck,

thank you very much for the very quick problem solving. Now it works very well!

This "error" could only occur because the Orchid package actually exists.
Thank you so much for creating and sharing these very helpful tools without which I couldn't solve my problems!

Best regards from Berlin

Rolf
