### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by sameyers** [erfajo/OrchidForDynamo#13]
Can I manually copy the files into my packages folder?  I thought that was possible and suspect the json file would need to include the contents for this to work.  Am I misunderstanding how this is done?  I am unable to run exe on my system. Thanks.

**Comment by erfajo** [comment]
You should be able to do excactly that. But in the online packages is "only" the full package stored. If you use the installer does it install both a version for the sandbox edition and the normal dynamo (D4R). In other wors do the executable installer hold two different json files all other content is the same.

**Comment by sameyers** [comment]
I am looking at the D4R outcome.  Because I am not an administrator on my machine, I cannot run installers, so I can only copy/paste.  Is the JSON file downloaded from the repo all that is needed?  It seems to be missing the 'contents' references, but instead has the contents from the package one would get from the package manager.  With the instructions for going here, to Github.

**Comment by erfajo** [comment]
All that it takes is that the content of either the 1.3.2 or the 2.0.1 version is places in one subfolder... I named it "Orchid" but you can name it whatever you prefer. If the subfolder is placed correctly in the search path supported by Dynamo, then it should be loaded automatically.
![image](https://user-images.githubusercontent.com/2844374/48211539-fb367c00-e379-11e8-9935-baad4161b243.png)
