### ISSUE TITLE
Confused with Circuit node

### ISSUE THREAD

**Issue by DynaBimm** [erfajo/OrchidForDynamo#132]
Hello, @erfajo

Also can't understand, does Circuit adds extra unwanted level to passed list?
![image](https://user-images.githubusercontent.com/62960555/137160381-538d5459-7b4b-4bf8-a535-f14490b508b7.png)

**Comment by erfajo** [comment]
I think this issue has been covered during the subsequent releases. I am closing this issue marked as solved.
