### ISSUE TITLE
Problem with instalation of Orchid package (cannot see Orchid package in Dynamo)

### ISSUE THREAD

**Issue by Wojt12** [erfajo/OrchidForDynamo#135]
Revit: 2022
Dynamo: 2.10.1.4002
Orchid: 2.12

Hallo

I have tryed to install Orchid package on my PC. Firstly I have done it too quickly and didn't close Revit during first Orchid instalation. After that I have read almost every post on the forum and have done all those things:
- deleted Orchid
- reinstalled Revit
- installed Orchid from exe
- deleted exe Orchid
- downloaded zip Orchid
- unzipped files to proper location (several folders)
- received notification like this:
![Orchid](https://user-images.githubusercontent.com/93378277/139417162-2ffa5a48-62a4-4332-93e6-a9413f7baa0b.png)

Is there anything else I can do to make Orchid work? I think I have read all threads about Orchid installation and none of them solved my problem.

**Comment by erfajo** [comment]
You have to update your Revit Installation, so you will have a dynamo 2.12 version.
However, you can get the latest released 210 version by looking into the history, I presume it will be late september for the last 210 version

**Comment by Wojt12** [comment]
Thanks for your help
