### ISSUE TITLE
Load Active Family into background file

### ISSUE THREAD

**Issue by HC-Austin** [erfajo/OrchidForDynamo#139]
I am trying to load an active family in to a template file in the background. I am currently using your code to collect the orchid document  of the template and I gather the family file path via other code then attempt to load and get the below error. Is there something I am doing incorrectly? I entered an override string of the file's location just to try to problem solve, I previously was collecting this string in an earlier bit of code. Thanks
![image](https://user-images.githubusercontent.com/44181006/143149667-0fc91bd2-6f6d-4eed-a237-4d2bf2e0c3b6.png)
![image](https://user-images.githubusercontent.com/44181006/143149086-f9f0e759-6d22-41f4-8931-f470653b3d42.png)

**Comment by erfajo** [comment]
as I see it, you try to open a rte file, that is not a document!... and you should use "await" node instead of "passthrough"

**Comment by HC-Austin** [comment]
Thanks for the quick response. So I assume that the Document.BackgroundOpen is not able to open a revit template? Thanks

**Comment by HC-Austin** [comment]
As I was just messing around and doing some problem solving with the code. I changed the open document to a rhythm package and then converted it to the orchidtype for the load family and get the same error on the Document.LoadFamily node as before: "active document may not be closed from the API"

Thanks

![image](https://user-images.githubusercontent.com/44181006/143277799-fa433f88-e222-4db9-8e66-a61e7014cda4.png)

**Comment by erfajo** [comment]
You should not, under any circumstances, play around with template (rte) files.
Please try with a proper document file and eventually save this as a template ind the end. However, I dont provide any nodes for any kind of template files, so you need to find nodes for that elsewhere.
