### ISSUE TITLE
Associate parameter in multiple family files - for example node Orchid parameter.associate

### ISSUE THREAD

**Issue by MarkoAndrejasic** [erfajo/OrchidForDynamo#14]
Revit: 2019
Dynamo: 2.0.1.5055
Orchid: 201.3.6.6881

Hi @erfajo ,
I am trying to associate the element material parameter with a family material parameter in multiple family files. For the last two days I am trying to do it with the parameter.associate “Orchid package”, which looks great! 
**It worked from the first moment using the current open family document.** 
But I didn’t managed to get it working for multiple documents. Any other solution would be appreciate too. I am adding pictures of the script.
Please help me find out what am I doing wrong. :slight_smile:

Link to files:
https://app.koofr.net/links/d3cfc427-1efd-4e6c-b0bc-780bca108070 

ps: I have previously posted the question on the Dynamo forum (link below) and @Manel_Fernandez suggested me to visit this page:  

https://forum.dynamobim.com/t/associate-parameter-in-multiple-family-files-for-example-node-orchid-parameter-associate/28429/3 

Regards, Marko

**Comment by erfajo** [comment]
did you see the example in the sample collection
Samples/Dynamo_133/FamilyDocument/Nested-Lookup.dyn
![nested-lookup](https://user-images.githubusercontent.com/2844374/48555107-7ea71e80-e8e0-11e8-89b6-6533fe77d3da.png)

**Comment by MarkoAndrejasic** [comment]
Thanks for your time!
Yes I have seen them. 
You are right, there are no nested families in my files as you have mentioned. 
But on the other hand your node works in the case of no nested families and "current document" setting.

Please open the family CutCover_B_2.rfa and use the daynamo Associate_1_1.dyn.

http://k00.fr/wc26uf0i 

It will associate the element material parameter with the family type parameter "Material_GP1". So even if it was not made for these purposes, it seems to be working for the current files. 

I have thought that in this case there must be a way to get it working for multiple (even if non nested families)

So do you think there is a way to get it working in the way I am trying to?   

Thanks again, Marko

**Comment by erfajo** [comment]
No it will not work unless you nest families inside a family file. You must repeat how you would do it manually... Dynamo can only do whatever you as a human can do, it cant invent something by it selves.

**Comment by MarkoAndrejasic** [comment]
Sorry for bothering you, but I would like to ask you for the last time :) 

Maybe I was not clear enough. So I made a screen recording  video in which I use your node to associate a parameter of a non nested family. 

video: http://k00.fr/83it6vof 

I am asking if is it possible to do something like this for other files (families) that are currently non opened.

Nevertheless thanks for your Dynamo nodes and help 👍 
Marko

**Comment by erfajo** [comment]
aha now I got it, you are not asking for associate, just a normal "SetValue"...
![capture](https://user-images.githubusercontent.com/2844374/48562189-fe89b480-e8f1-11e8-9e07-8e54ae07d05d.png)

**Comment by erfajo** [comment]
I now found some time to test what you have sent. I didnt know that you could combine that Rythm node and grap a freeform like this, nice solution. So combining that with other of my nodes was very doable... try this
![capture](https://user-images.githubusercontent.com/2844374/48563262-3abe1480-e8f4-11e8-92ea-03c05a49a7bd.png)

remove .txt from the file
(https://github.com/erfajo/OrchidForDynamo/files/2585952/Associate_erfajo.dyn.txt)

**Comment by MarkoAndrejasic** [comment]
Thanks I really appreciate your help! 
Your workflow works for me for one opened family, but it dos not work for multiple families. Do you have any other ideas? 

Video: http://k00.fr/n5hdhfkx 

![image](https://user-images.githubusercontent.com/42461874/48569816-09991080-e903-11e8-815d-35d3c66c6eb6.png)

Regards Marko

**Comment by MarkoAndrejasic** [comment]
Thanks @erfajo; please let me know if you will develop an enhancement in the future that will solve my problem.
Marko

**Comment by erfajo** [comment]
Well, it is always annoying not to be able to solve something. So I could not let it be. It showed up, that it actually was not that difficult when I just started to think more into depth over the problem. Essentially I change very few lines of code and then it worked.

In your case must it be combined with list level, but that would have been the case anyway since you feed the list with a list of documents and a list of familytypes… that are unique for each of the families!

remove txt from filename
https://github.com/erfajo/OrchidForDynamo/files/2588925/Associate_erfajo_2.dyn.txt
![capture](https://user-images.githubusercontent.com/2844374/48616493-13b71f80-e994-11e8-880b-e1973e1c084e.png)

**Comment by MarkoAndrejasic** [comment]
Thank you very much, for your support and development. The node works like
a charm.

Regards Marko

V V pet., 16. nov. 2018 ob 11:38 je oseba Erik Falck Jørgensen <
notifications@github.com> napisala:

**Comment by erfajo** [comment]
You are welcome, and thanks for your feedback :-)
