### ISSUE TITLE
 Package Instructions

### ISSUE THREAD

**Issue by 1422657183** [erfajo/OrchidForDynamo#140]
HI!
   

     Could you tell me where I can get this package instructions.

**Comment by erfajo** [comment]
sorry I really dont understand!?
However, if you dont understand what is written on the welcome page and eventually the error page for installing. Besides are a sample collection available. Concerning Dynamo in generel, please go to the dynamobim forum.
If you cant figure how to install/use Orchid from all these sources, then please dont install Orchid.
