### ISSUE TITLE
OrchidForDynamo_203.exe is installing files to 2.0

### ISSUE THREAD

**Issue by heinrichboldt** [erfajo/OrchidForDynamo#141]
I have downloaded the files and need to update the Orchid for Dynamo 2.3.xxx

after running the installation file in Build ( had to resolve an security issue tracking problem by allowing to proceed  - symantec problem?) 
I could not find the folder in 2.3.

after recording the installation progress I could review that the "OrchidForDynamo_203.exe" is extracting files to 
...\Roaming\Dynamo\Dynamo Revit\2.0\Orchid\...

just 

### Revit, Dynamo and Orchid version

Revit: 2020.2.3
Dynamo: 2.3.0.xxx
Orchid: x.x.x.x

**Comment by heinrichboldt** [comment]
user\AppData\Roaming\Dynamo\Dynamo Revit\2.0\Orchid
is now the new folder after running the "OrchidForDynamo_203.exe"

this might be wrong?

**Comment by erfajo** [comment]
that is the right folder... Dynamo is installed that way, it is the primary number for version 2.0 which is used. For Revit 2020 is the folder named 2.3, for Revit 2021 is the folder named 2.6, and for Revit 2022 is it named 2.12 (2.10 for the shipped version of Revit, but with update 1 for Revit 2022 was that changed).

**Comment by heinrichboldt** [comment]
Good morning, 

this is in my settings:
` <CustomPackageFolders>
    <string>C:\Users\u4014125\AppData\Roaming\Dynamo\Dynamo Revit\2.0</string>
    <string>C:\Users\u4014125\AppData\Roaming\Dynamo\Dynamo Revit\2.3</string>
  </CustomPackageFolders>`

**Comment by erfajo** [comment]
sorry I thought that you where a programmer, I understand now that you are a user...
You can edit your paths from inside Dynamo, please do that!, and your path should reflect the version, meaning... the ONLY path should be "C:\Users\u4014125\AppData\Roaming\Dynamo\Dynamo Revit\2.3".

**Comment by heinrichboldt** [comment]
thanks for action
after deleting the one path for 2.0 in the settings the installation is adding the folder in the right place

**Comment by erfajo** [comment]
thanks... I am looking for the first line in the xml file, since this is the first path the user has setup. That was the "error" :-)
However, since Revit 2022, has the Dynamo Team made a change adding a path as a variable as the first path... this is also solved when installing Orchid 212.
