### ISSUE TITLE
Orchid on Revit 2022

### ISSUE THREAD

**Issue by BIMRail** [erfajo/OrchidForDynamo#142]
Hi @erfajo.
Due to company upgrade policy, Revit has been upgraded to v.2022 with Dynamo version at 2.10 instead of the latest version available
Is there any way to get Orchid on this installation?
I know that Orchid is now developed for Revit 2022.2 and Dynamo 2.12. I would like to find some sort of workaround to not lose the scripts with Orchid nodes.
Thank you.

**Comment by erfajo** [comment]
have you tried to install the 212 version? I dont have an 210 build anymore, but I hope that 212 would work for most nodes...

**Comment by BIMRail** [comment]
I found the solution: manual installation of Orchid v. 212 plugin.
Now is possible to view the nodes into Dynamo and all works well.

**Comment by erfajo** [comment]
Exactly, and I hope most nodes will work. I am not totally aware of the differences between 2022 and 2022.1. My primarily coding platform is 2021 while this is the version we use... only by request do I code nodes for 2022.

...and you are welcome, I am glad that Orchid helps you :-)
