### ISSUE TITLE
SharedParameter.Create doesn´t work as expected

### ISSUE THREAD

**Issue by efebei** [erfajo/OrchidForDynamo#144]
### Operating system
Windows 10

### Revit and Dynamo version

Revit: 22.1.10.541
Dynamo: 2.12.0.5740
Orchid: 212.1.0.8046

### What did you do? 
Trying to bulk create shared parameters of different types in a Revit Family

### What did you expect to see?
21 parameters with different names, types, builtin parameter groups and tooltips
### What did you see instead?

21 parameters only with diferrent names. Type, builtin parameter group and tooltip are the same repeated ones as the first. 
[enviadoOrchid.zip](https://github.com/erfajo/OrchidForDynamo/files/7900390/enviadoOrchid.zip)
.

**Comment by efebei** [comment]
Playing with the lacing options of the node, I´ve seen using longest list gives the expected results. Whereas with the default option of "automatic" the node generates 441 incorrect parameters. The built-in node of dynamo gives the 21 parameter result in auto instead.

**Comment by erfajo** [comment]
Please not the inpu on each port. only the "parameterName" takes a list!
All other are single input!, meaning you need to arrange everything according to this!

the idea is that you can create several parameters **of the same** type!
meaning, parameters should be grouped as the same type, with the set of names for them.
![image](https://user-images.githubusercontent.com/2844374/150530889-9876b359-0031-4a84-b492-6ef4ecf35703.png)

**Comment by efebei** [comment]
As a suggestion: the default node takes lists on every port, so it would be very user friendly that this node could take the same approach. Anyway, I discovered that using the lacing option of longest list instead of the default of automatic I can get the desired result equal to the default node of dynamo. Thanks!

**Comment by erfajo** [comment]
This is not how parameters are created in the API. You can bulk create many paramaters, however, they need to be similar only divided by the name... This is what I have implemented.
