### ISSUE TITLE
Parameter.AddSharedParameter not available

### ISSUE THREAD

**Issue by Vern2022** [erfajo/OrchidForDynamo#147]
Hello!

I am following a tutorial on adding shared parameters to families using Dynamo and they use the Orchid node "Parameter.AddSharedParameter" but I do not see that node anywhere in my version. Was it renamed? Did I download Orchid incorrectly? Any help would be appreciated. Have the same issue in both 2020 and 2022.

I will add, I am extremely beginner when it comes to Dynamo... but you gotta start somewhere!

Thank you for your time.
Vern.

Revit: 2020 and 2022
Dynamo: 2.3.0.8352 and 2.12.0.574
Orchid: 203.3.0 and 212.1.0

**Comment by erfajo** [comment]
Have you tried to undfold the package?
RevitFamily --> SjaredParameter
![image](https://user-images.githubusercontent.com/2844374/162733165-2a49a179-acb9-4ca1-a537-34c35608bd8c.png)

**Comment by Vern2022** [comment]
Hi,

Thank you for the reply and sorry for my late reply. I did do that. The tutorial I was following had totally different items listed under the shared parameters. The tutorial is here by Aussie Bim Guru https://www.youtube.com/watch?v=8mRXo37veao

Maybe I have a newer version installed than what’s in the tutorial?

This is what is on his that I don’t see on mine…
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by erfajo** [comment]
If you write now, then I can assure you that the node has changed dramatically!
The below post describes why all nodes that did use internal types are changed, and this will most likely include all Zero Touch packages by now. The “converter” I have shared will all codes means that every coder now can use the shielded classes by the dynamo team.
https://forum.dynamobim.com/t/the-fusion-post-for-coders/78033

I can't be responsible for whatever someone is making videos about or help provided in the dynamobim forum, I can only assist you if you provide me with the needed material, as a minimum the graph file. However, I will recommend that you download my sample collection and try to see what may help you.

**Comment by jptrujillol** [comment]
I have the same issue with revit 2021 and dynamo 2.5. I tried to install the package in four different folders with no luck. Some nodes are not there. Very sad

**Comment by erfajo** [comment]
The nodes are there, but they are renamed... and this will happen over and over again. Unfordenetly has migration not worked since the shift from dynamo 1.3 to 2.0, and this is still the problem. The only way to find the nodes is to walk through the folders... and here will you find Parameters and Sharedparameters... or check out my sample collection.
