### ISSUE TITLE
Material Maps Setting

### ISSUE THREAD

**Issue by bradshales** [erfajo/OrchidForDynamo#148]
I would like to see SetGlossiness Image, SetTransparency, SetCutouts Images in Material Creation Render Appearance.
Also, Is there a way to apply the Edit Image Scale Sample size like 1500mm x 1500mm.
Thank you.

**Comment by erfajo** [comment]
I will look into this. I will add it to my list of thing to do :-)

**Comment by erfajo** [comment]
Sorry for the long response time, but it has been and is still a very comprehensive job to handle all the functions attached to materials...

I have not reached the end goal yet, but I think I have made what you were asking for. However, If you also want to edit textures, you have to wait for the next update... this release includes "only" all the functions you have asked for :-)
![Apperance](https://user-images.githubusercontent.com/2844374/174625672-cd643280-2d90-461a-a541-dbd50ba4aff4.png)
