### ISSUE TITLE
Parameter Associate for Global Parameters with a project setting

### ISSUE THREAD

**Issue by Chrono9084** [erfajo/OrchidForDynamo#15]
I am currently trying to associate a titleblock with global parameters inside a project.  I have been using your Parameter.Associate node within families with great success but it obviously does not function within a project document.

It would be amazing if you could create a similar node that allows the user to specify a family, global parameters, and family parameters.

Otherwise, thank you so much for the Orchid package!  It is great!

**Comment by erfajo** [comment]
I am not sure what you are suggesting.

If you are suggesting global parameters in families. Well, this cant be created since this kind of parameter doesn't exist for families. You need to ask the Revit programmers to code this for families. Furthermore, please remember this is not the Dynamo team or the dynamo forum you can put this up in since no one from here has any influence on this.

Associate parameters on the other hand cant be created inside a project, and this is by the same reasons as above mentioned.

However, I might have totally misunderstood what you are suggesting, please try to describe it more deeply if I am wrong.

**Comment by Chrono9084** [comment]
Thanks for the response.  Let me try to describe what I am trying to accomplish.

Currently our companies titleblock has a number of parameters which are associated with the projects global parameters:
This is our titleblocks type properties/parameters.
![image](https://user-images.githubusercontent.com/37596510/49473307-4efc7f80-f7d7-11e8-9cf7-b8da3ddca09b.png)

Here are the global parameters in our project.
![image](https://user-images.githubusercontent.com/37596510/49473346-705d6b80-f7d7-11e8-9070-bdf3993117e0.png)

This works very well when we are using our own titleblock as it is preset and ready to go.  I am trying to make it easy for our technicians to bring in an outside companies titleblock and use it.  I have already created a script which imports our logo, creates all parameters within the client titleblock, and then associates the logo with the new parameters.

The final step would be running a script that associates the global parameters to the titleblock family just like in the pictures above.  Does that make sense?

**Comment by Chrono9084** [comment]
To add to this, the end process would look like this:
1) Bring new titleblock into project.
2) Open titleblock and run dynamo script with brings in our logo, creates appropriate parameters, and then associates them (this is already working).
3) Load titleblock back into project.
4) Run dynamo script to associate global parameters (project) with the titleblocks type parameters.

**Comment by erfajo** [comment]
It makes more sense now, do you have a small sample... a purged project file containing one sheet with a titleblock?
Then I will try to see what I can do about it.

...and scripting is textual coding inside a python node or coding as i do in the .net environment. Nodes connected by wires are graphs.

**Comment by Chrono9084** [comment]
Someone once told me I might get corrected about scripting vs graphing at one point.  I should have listened to her!  I will get you a sample shortly.  Thanks again.

**Comment by Chrono9084** [comment]
[REGISTRATIONTest.zip](https://github.com/erfajo/OrchidForDynamo/files/2646237/REGISTRATIONTest.zip)

I have one sheet.  The left titleblock type is already associated correctly.  The left titleblock type is not.

**Comment by erfajo** [comment]
I will see what i can do as soon as i have finished the nodes i am coding at the moment...

**Comment by Chrono9084** [comment]
I just wanted to throw this in here for your information.

lucamanzoni helped create this python script which does the job but it can only handle one parameter at a time.

```
import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

clr.AddReference('System')
from System.Collections.Generic import List

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

element = UnwrapElement(IN[0])
name = IN[1]
gp = IN[2]

#Get parameters from element
parameters = element.Parameters
myparam = []

TransactionManager.Instance.EnsureInTransaction(doc)

#Get parameters with the input name
for param in parameters:
    if param.Definition.Name == name:
        myparam.append(param)

#Associate parameter
for x in myparam:
    try:
        x.AssociateWithGlobalParameter(ElementId(gp.Id))
        out = "Success"
    except:
        out = "Fail"

TransactionManager.Instance.TransactionTaskDone()

OUT = out
```

Here is a link to the conversation: https://forum.dynamobim.com/t/associating-global-parameters-to-a-family-in-a-project/29340

**Comment by erfajo** [comment]
I did finish my minor update yesterday, and have now made the node you asked for... it is included in the lates build (6915).
![parameter associate](https://user-images.githubusercontent.com/2844374/49643926-46928780-fa17-11e8-96da-1d03e696823b.png)
