### ISSUE TITLE
Parameter.Associate - "This parameter cannot be associated"

### ISSUE THREAD

**Issue by mhiser2** [erfajo/OrchidForDynamo#150]
Revit: 22.1.21.13
Dynamo: 2.12.0.5650
Orchid: 212.1.0.8138

Hello!

I've started using your package in order to quickly make changes to my firms door library. Everything has been working fine, but I am hung up on how to get your Parameter.Associate node to work. I've been going at it for awhile and looked at dynamobim forums, here, and your sample files. I haven't seen the error "This parameter cannot be associated" anywhere. 

I'm trying to associate the material parameter of a nested door panel family to its counterpart parameter in the overall door family. I've tried to associate it with both parameters as instance and type parameters. And I've checked multiple times that I can still manually associate the parameters, which works. Not sure what else to do. 

Any help is appreciated. Thank you!

![image](https://user-images.githubusercontent.com/104935823/166808703-20ca9e86-facf-4bff-bb32-d5e50ecb7678.png)

**Comment by erfajo** [comment]
Can you please provide a family and the graph? you can zip the content and add ".txt" to the filename, so it can be attached.

**Comment by mhiser2** [comment]
Let me know if this works. You'll notice I have the starting point to do this for an entire folder, but swapped it out for a single file just to try to trouble shoot the issues. 

I hope this isn't a "me" issue but I have a feeling it might be. 

[Orchid Issue Files.zip](https://github.com/erfajo/OrchidForDynamo/files/8631410/Orchid.Issue.Files.zip)

**Comment by erfajo** [comment]
Thanks,
I thi9nk the problem is the nested elements... I dont think you are getting them right, so I made a new node (took me 5 min.) and then it worked.
Now I just need to see whatelse I have made, before I can release a new build :-)

I will let you know asap when I can release the next build
![image](https://user-images.githubusercontent.com/2844374/166953291-5f410748-7794-477c-91aa-07fc4ba3403c.png)

**Comment by mhiser2** [comment]
Thank you so much for the quick reply.

If you don't mind, is there something wrong with the nested family, or is there just something about how its set up that the node isn't working with it properly?

Also, I see you just isolated one type for the door panel. Will this still associate the parameter for every type of the family if they are fed in as a list? The reason I came to this issue is that my colleague wanted to add that new glazing parameter for the door panel, but I already built those standard panel types at her direction. So the goal is now to associate that parameter for every type within the main family. You can see why I want to speed this up, considering there are 18 panel types in each family, and I have about 80 door families in the library so far!

**Comment by erfajo** [comment]
and here it is for all familytypes of a family...

your error is, that you load a family but it has nothing to do with the familydocument... it is just something you load in the background. BUT... I did not have a node for nested elements "by name"... now two new nodes is on the way :-)
![image](https://user-images.githubusercontent.com/2844374/166956930-500f285a-a6e2-4c15-92ab-a9cf3c957557.png)

**Comment by erfajo** [comment]
I have uploaded new builds to be downloaded, and I suppose you can use this graph if you need to load the families into the family where you need to associate parameters. If you have the familytypes loaded, then I hope you can fige how to remove the loading part  :-)
![Associate Nested Family Parameters](https://user-images.githubusercontent.com/2844374/167092995-a11bc5f4-7191-4888-8622-ff87658726e6.png)
[Associate Nested Family Parameters.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/8638517/Associate.Nested.Family.Parameters.dyn.txt)

**Comment by mhiser2** [comment]
I'm so sorry, but I'm still have an issue with it. I tried plugging the new node into my script, and then tried downloading the one you've posted here and just running that. I've tried opening the nested family in the background to pull the name, and just entering it as a string. Its not showing any error, but I'm getting empty lists.

I would think the issue is the empty list from the Family.Types node seen below. Is this an issue with the new GetNestedByName node, or the way info is being fed into it? Should something be showing as an output there?

Again, I greatly appreciate the work you've put into this, and I apologize if this is just an error on my part. 

![Associate Nested Family Parameters Issue](https://user-images.githubusercontent.com/104935823/167157043-4f2365a2-ff8d-41c7-8a08-4dd8c6d372f9.png)

**Comment by erfajo** [comment]
The Revit engine comes with some restructions, this is why I knew that "just loading" would not be enough, however, I was affraid that a transaction would be needed... the thing is, that otherwise is the loaded content just loaded into memory. Try to add the node named "traansaction end" or something like that.
If this dosnt work I will suggest two graphs (NOT SCRIPTS) to be runned in seperate handlings. One that loads content and one to associate.
