### ISSUE TITLE
Installation error for revit version 2023

### ISSUE THREAD

**Issue by danghuulam** [erfajo/OrchidForDynamo#151]
My  Operating system
( Windows 10)

My Revit and Dynamo version
Revit: 2023
Dynamo: 2.13.1.3891
Orchid: 2.13.0.0.8161

I used the previous Orchid versions and used it normally, but when I switched to revit 2023 I reinstalled orchid but it was no longer usable. Can anyone give me some advice? Thanks very much !

![Capture](https://user-images.githubusercontent.com/33894496/167399860-afa2ca59-c0e3-4348-85db-6ef58d161e32.PNG)

**Comment by erfajo** [comment]
I think you should see some of the other packages you have installed... Remove all packages and let Orchid be the only one left... Then move package for package back again and find the package that gives the error.
One of the packages you have loaded violates the rule NOT to include any assemblies from either Revit or Dynamo into their package. It is an error that I presume is made by a newbie.

**Comment by danghuulam** [comment]
> 
Thank you very much ! I did as your advice and installed successfully.

**Comment by erfajo** [comment]
just for the record, which package caused the problem?

**Comment by danghuulam** [comment]
> just for the record, which package caused the problem?

Sorry I didn't find each package but copied all of them out of the library, then I copied the orchid folder in, and then copied the library as before.

**Comment by erfajo** [comment]
fair... It would have been nice to know which package was the problem... 
However, you should never walk away from a problem like this, it will hit you again... and this can come faster than you think.
