### ISSUE TITLE
Windows error when launching exe

### ISSUE THREAD

**Issue by jonathanroy8676** [erfajo/OrchidForDynamo#154]
Hi,
When I launch the installation file 206.exe windows gives me an error message and the "Run anyways" option doesn't appear. 
Just wanted to be sure it's an error on our side. Same for samples file

My PC
![image](https://user-images.githubusercontent.com/16231080/170785999-a3b9eb89-cc92-4dfa-9bf3-b9445668d735.png)

Example:
![image](https://user-images.githubusercontent.com/16231080/170786081-f1fd5fa1-2ce9-47c9-90a0-5ce8fc249db9.png)

Issue already opened with my IT. But gotta wait till monday. If you all say it's fine on your side, great. I'll wait.
I tried on two different company PCs
Regards,

**Comment by erfajo** [comment]
I am not sure why you can’t "Run Anyway”, I presume it is either your company that has locked users for installing or it is something you need to tweak with your antivirus software...
anyway, you can download the zipped version and install it manually. Find the folder where your packages are located and unzip the content from the downloaded zip file into a folder named "Orchid". Verify that the content inside is organized as other packages are, this check should capture if you somehow end up with an extra folder level.

**Comment by erfajo** [comment]
In that case, I am afraid you have a package installed which doesn't comply with standards... No packages must contain any assembly files from dynamo, however, from time to time do some new codes include that.
Try to move all other packages out from the folder to your desktop, and see if my package loads. If so, then you have to walk every package through to see which package there course the problem.

**Comment by jonathanroy8676** [comment]
File>Properties>Unblock>OK
![MicrosoftTeams-image](https://user-images.githubusercontent.com/16231080/171052045-5bf7c112-bb43-49ae-8ea6-9153dd6c9451.png)
Voilà, here's the solution to my issue.

**Comment by erfajo** [comment]
thanks for letting me know, Then I will also add this as an option for errors :-)
