### ISSUE TITLE
Graphics.Set node not working

### ISSUE THREAD

**Issue by lrombie** [erfajo/OrchidForDynamo#155]
### Revit, Dynamo and Orchid version
Revit: 2021.1.5
Dynamo: 2.6.1
Orchid: 230.0.3.7584
### The issue
So for some reason this node does not want to work anymore…
![image](https://user-images.githubusercontent.com/106814588/171849370-5f9083e6-66fa-429c-b467-4f5adbb4c6ad.png)

It has already worked for me in the past and all parameters are the same so I have no idea why it just stopped working and I’m going crazy over it!
The only thing I could figure out is that the node is from Orchid version 230.0.3.7584 and I currently have 260.0.3.7584.
I've tried installing 230 again, but I get this message:
![image](https://user-images.githubusercontent.com/106814588/171849573-935ec0a7-283c-42ce-9ddb-6e4f72320170.png)

I tried downloading both 230 and newer version from this github page, but my computer does not allow to run it
![image](https://user-images.githubusercontent.com/106814588/171849696-1bf8d4ac-5e8c-4200-9ea9-ff6e0d5a41c8.png)

I'm getting really desperate here, really want this to work. Hope you can help.

Thanks in advance
This is the excel file I'm using for data, can't seem to upload my .dyn file here?
[test2.xlsx](https://github.com/erfajo/OrchidForDynamo/files/8832139/test2.xlsx)
.

**Comment by erfajo** [comment]
First, can you send the graph file (rename the extension to .txt if you cant upload)
next, you computer might lock ececutable files, however you should be able to unblock the file by entering file properties
try to see this issue --> https://github.com/erfajo/OrchidForDynamo/issues/154

**Comment by lrombie** [comment]
[MA_FromExcel - Copy.txt](https://github.com/erfajo/OrchidForDynamo/files/8833105/MA_FromExcel.-.Copy.txt)
Here is the .dyn file as .txt

I'll do an update right now

**Comment by lrombie** [comment]
I tried to recreate the sample graph, but I'm still getting the same error
![image](https://user-images.githubusercontent.com/106814588/171902558-6bc7fd8d-357d-4008-ae53-1d89986565bb.png)

**Comment by lrombie** [comment]
Just tested out a theory, using the separate nodes, it works perfectly! I'll see if all of them work and use this as a workaround for now.
![image](https://user-images.githubusercontent.com/106814588/171902943-ba9c73ca-f438-41d3-9945-dd112cd59aa8.png)

**Comment by erfajo** [comment]
I have found the problem, I have not coded my solution for a string value that did not exist... the pattern "No pattern" does not exist, since it is the default value.
I am working on a fix for that, and will release this later today. I will also send you a updated graph, where I have optimized some of you processes. Just a hit, what you can do for all elements in one process should be done instead of have several nodes doing the same on smaller datasets :-)

**Comment by erfajo** [comment]
update...
I have totally updated all material nodes, and made som new... my nodes for materials now support all kind of appearnces. However, this means, that the node "Material.SetAsset" is renamed to "Material.SetApperance"... most nodes named something with Asset is renamed.... and the new Asset nodes are handling the real Asset library in Revit now.
the new build is 8192
