### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by QilongTang** [erfajo/OrchidForDynamo#157]
Details in https://github.com/DynamoDS/Dynamo/issues/13062

### Operating system
(e.g. Windows 7, Windows 10, etc)

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: x.x.x.x
Dynamo: x.x.x.x
Orchid: x.x.x.x

### What did you do? 
(Fill in here)

### What did you expect to see?
(Fill in here)

### What did you see instead?
(Fill in here)

**Comment by erfajo** [comment]
Thanks for noticing me :-)
