### ISSUE TITLE
File.LoadFamily Relinquish Worksets

### ISSUE THREAD

**Issue by Jdjohnson260** [erfajo/OrchidForDynamo#16]
I am new to Dynamo so forgive me if my question is basic. @erfajo i am using you graph to update title blocks in many projects. the problem that i am running into is that I end up being the owner of the work set after I run the script. I believe it is in the “File.LoadFamily” node. (can’t inspect the code of the node) If this is correct could you add a line of code that will relinquish all work sets.

**Comment by erfajo** [comment]
It is not designed for use with central files, but I will look into it asap.

**Comment by Jdjohnson260** [comment]
Thank you

**Comment by erfajo** [comment]
I have now tested this issue and I cant replicate it. I don't end up as the owner of the workset no matter how I test it. I must own worksets in advance, and then it is really not an error.
So I am afraid you need to test some of your other processes to see if they fail.

**Comment by Jdjohnson260** [comment]
Thank you for looking into this for me. I will do some more testing and get
back to you if i still see problems or an issue.

**Comment by Jdjohnson260** [comment]
After running the script again on my files it still makes me the owner of
the "work set" . Here are screen captures of the project before and after
the script.

Before running
[image: before_Runing_.png]
After running

[image: After_Script_2.png]

Before
[image: Before_Script_2.png]
After
[image: After_Script.png]
Before
[image: Before_Script_3.png]
After
[image: After_Script_1.png]
Hope this helps.

**Comment by erfajo** [comment]
I cant see your images, but anyway, since I cant replicate your problem, I cant do any thing about it.

**Comment by erfajo** [comment]
It should not be necessary to code anything, I think others have made nodes for worksharing you can use in graphs... but if you are capable in coding your own scripts then you can help yourself with many things.
However, I still don’t understand why you end up in this problem, there must be something else going on in your graphs besides loading families into your project files.
