### ISSUE TITLE
Get Shared parameter type and group information from multiple families

### ISSUE THREAD

**Issue by pedersenjpp** [erfajo/OrchidForDynamo#160]
### Revit, Dynamo and Orchid version
Revit: 2021.1.7
Dynamo: 2.6.2.15772
Orchid: 206.3.0.8131

### The issue
I cant seem to find a way to extract Parameter Type (Text, Int, Yes/No) and Group (Data, Dimension, Identity Data) information. Do you have a node, which can convert the Parameter from Orchid to Revit, or is it possible to create it using orchid?

So far I can only get the value based on Orchid Familiy document and a list of Shared parameters I know is in the families (Or all parameters if needed).
I want to export this data, to QA shared parameters created in families. (This was before using your package to add them to new families)

**Comment by erfajo** [comment]
You should update your package to the latest version. I have made a converter file for all programmers which is put up in the dynamobim forum, so everyone can convert types into dynamo types even they are shielded from the dynamo team. This means also that I don't have any times left that exist in dynamo as a type.
If this still means that you miss a node, then please reach out again :-)

**Comment by pedersenjpp** [comment]
Thanks for the quick response.
Updating gave just what I needed. Though I didn't use the converter as the types in the newest update already are Dynamo types for some reason. Is this also the expected behavior? I understand from your message that the converters are used to go from Orchid type to Dynamo types.

It would be nice to have a node to get shared parameters based on Name instead of only being able to choose all and then filter the ones not needed out after "converting" back to dynamo nodes.

**Comment by erfajo** [comment]
I do still have some converters. But if a Dynamo type exists, then have I removed mine in most cases. 

However, Geometry nodes are still my nodes, or Revit nodes if I should be more precise. I have made a series of nodes using the Revit API geometry, which is better for some purposes than the Dynamo geometry. Especially if the geometry exists and you want to retrieve information about it.

I tried to see if a get project/shared parameter type existed, but it doesn’t seem to be the case, so I will put it on my todo list.

You can get a parameter (project or shared) by name... and the categories
![home](https://user-images.githubusercontent.com/2844374/183279459-2bd357bb-3ca8-40f5-b4d1-c20bf7299c38.png)
 
You are welcome to attach your graph so I have a testbed to build the node for. Remember to rename (or add) “.txt” to your file before uploading :-)

**Comment by pedersenjpp** [comment]
Getting the parameter types is possible with Dynamos own nodes FamilyParameter.ParameterType and FamilyParameter.Group. They work just fine with your FamilyParameter.ByName node. I must have missed them before my last message.

Thanks for the help, and great package by the way. Using it a lot for batch changing family parameters.

**Comment by erfajo** [comment]
Thanks :-)

After I changed it, so that if a dynamo type existed, then could I also inherit whatever is made by the dynamo team is pretty smart :-)

However, it was something John Pierson made, which made me aware of how we could bypass the Dynamo team is shielding many of their types, I posted how to do this in the dynamobim forum so anyone now can bypass it :-)

By doing this, we now can share all functions and this is much more “open”… I really don’t understand why the team is shielding so many classes :-S

Thanks for your credit as well, I am glad that you find Orchid usable :-)
