### ISSUE TITLE
Document.LoadFamily node not working using Revit 2023 but works using Revit 2020

### ISSUE THREAD

**Issue by jarods350z** [erfajo/OrchidForDynamo#161]
Windows 10
Revit: 2023.0.2
Dynamo: 2.13.1.3887
Orchid: 213.0.1.8

have the node Document.LoadFamily in my dynamo script. I ran my script in a family environment (border)

It should replace the family in the file with one that is picked on the network with the same name (state seal)

Got an error that I need to run this command in a project document

P.S. this works fine using Revit 2020

![orchid error](https://user-images.githubusercontent.com/31901707/184024103-f10e68d0-e701-46a4-aec8-f9142c7102bd.png)

[Add Seals_script.zip](https://github.com/erfajo/OrchidForDynamo/files/9304170/Add.Seals_script.zip)

**Comment by erfajo** [comment]
I will test it asap :-)

**Comment by jarods350z** [comment]
Thanks you so much for your quick response.

[NV_Verticle_Full_Signature]<http://www.nvironmentdesign.com/>

Jarod Tulanowski | Bim Manager | Architectural Designer
Nvironment
***@***.******@***.***>
www.nvironmentdesign.com<http://www.nvironmentdesign.com/>

27 E Russell Street | Suite 300
Columbus, OH 43215
614.725.4644 o




[Icon  Description automatically generated]<https://www.linkedin.com/company/nvironment?trk=top_nav_home>   [A picture containing text, vector graphics  Description automatically generated] <https://www.pinterest.com/NvironmentDesign/_created/>

**Comment by erfajo** [comment]
aha, that was why I could not replicate the error. The error message says it all... This node works only in a project file, not in a family document file!
If the target is a family document, then use the comparative node for families :-)
If it had worked earliere must it be and older version you have of my package, I have added a test there should test if it is a project og a family document now...
However, I did made som missing cases of nodes while testing, so next version will have more nodes for loading families :-)

**Comment by jarods350z** [comment]
OK looks like I need to change the way my file looks at the revit family, because it says it cant use a string to load. any suggestions
![orchid error new](https://user-images.githubusercontent.com/31901707/184195538-4b84c33e-796e-4758-a87b-09d214b682f9.png)
?

**Comment by erfajo** [comment]
sure, just open the file in background, and close it again when you have ended the usage.
[Add Seals_graph.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/9314323/Add.Seals_graph.dyn.txt) (remove ".txt")
![Add Seals_graph](https://user-images.githubusercontent.com/2844374/184301239-cac8f883-ca97-45f9-ae09-388ccc9fa58b.png)

**Comment by erfajo** [comment]
I have decided to mark the nodes taking a file from a string as obsolete when the next version is released. 

And I found that dynamo has an error in the earlier version, if you had several nodes named as the same but taking different input, then would dynamo not see it as an error if it was fed with a wrong type. Meaning, if the family node took a string, a Family, or a Document, and if the node only should take a string value but got a document, then would it just recycle to another method (node) without warning and returning a correct result. This I very dangerous and I am glad that this has been removed in the latest dynamo version.

**Comment by jarods350z** [comment]
Wow thank you that works when I run it directly from Dynamo. Unfortunately, it only works a few times when I run it through pyrevit or the Dyno Browser. (It acts the same, but nothing is replaced) But this at least gives me hope. 

It might be because it needs to update the family from 2020 to 2023 first so the data stream await runs out of time before the close. I will keep testing.

Thanks again for the help here is my final script if you want it
[Add Seals.zip](https://github.com/erfajo/OrchidForDynamo/files/9316727/Add.Seals.zip)
.

**Comment by jarods350z** [comment]
That was it!  Once I opened a few of the seals and upgraded the families to Revit 2023 it worked fine through the toolbars.  It must stall in the upgrade process just a FYI.

**Comment by erfajo** [comment]
Sure an upgrade session is not something I under any circumstances can manage… this is something that is handled only inside Revit and does not send feedback to Dynamo. Meaning, you have to do the upgrade process in a manner where you are sure no other things must happen which can conflict with that.

remember no scrips only graphs... unless you really are scripting in code blocks or having it all as a python script... meaning no class or definition calls in your python script, unless you can answer yes to that you have moved far beyond scripting.
https://erfajo.blogspot.com/2019/03/graphs.html
