### ISSUE TITLE
Change parameter group

### ISSUE THREAD

**Issue by HVCFOGEY34** [erfajo/OrchidForDynamo#162]
### Is your feature request related to a problem? Please describe.

I'm trying to batch edit some families to change some parameters. One of the changes I want to make is changing the group some parameters belong to. EX: changing from "Visibility" (PG_Visibility) to "Set" (PG_COUPLER_ARRAY).

### Describe the solution you'd like 

I would like a node to be able to change an existing parameters group to another without loosing any family association to the parameter. I would assume it would work similar to the Formula.Set node with inputs for familyDocument, parameterName, but instead of a "value" input, an input for the group name.

### Describe alternatives you've considered 

I haven't attempted yet, but I was thinking of trying a python solution, but from the last time I tried, it was tricky, especially because I was trying to get it to work in conjunction with other Orchid nodes. 

One post I was looking at for help is this one:
https://forum.dynamobim.com/t/unable-to-permanently-change-a-parameter-group/19556/8

### Additional context 

I'm not quite sure if there is a direct api method for changing the group, so if it helps, a work around I was thinking of is some way to get all the required info to recreate the parameter with the new group, then re-associate any families to the new parameter.

**Comment by HVCFOGEY34** [comment]
I found a solution that works for me. It isn't a Python solution and I ran into an issue that with the Parameter.GetAssociated node that is problematic, but I have it working for now. See: https://github.com/erfajo/OrchidForDynamo/issues/163

**Comment by erfajo** [comment]
So what you essentially is asking for is a node that reads all parametervalues so a parameter can be changed and then reinsert the values... just in case something will be lost!?

**Comment by HVCFOGEY34** [comment]
I'm not sure I follow what you mean. I'm just looking for way to change a parameter to another group (same name, value, associations, etc.).  
Thanks for looking into it!

**Comment by erfajo** [comment]
I have found a solution... but to be sure I need to make som more tests. Besides coding these new nodes made me think on some updates I can make to other nodes. The code I needed to make for these new nodes are much smarter than what other of my nodes do. I can make quite some changes to other nodes, both project and family nodes!
just a screenshop from my tests :-)
![image](https://user-images.githubusercontent.com/2844374/193418977-279fe8d6-d13f-43e9-ace1-99ea57682eba.png)

**Comment by HVCFOGEY34** [comment]
That's great to hear! Those other nodes look very useful! I know I will definitely use them!
Thanks!!

**Comment by erfajo** [comment]
They are as good as finished, however... I must find a way so they can be activated after eachother...

example, first toggel to family parameter and then bach to shared parameter... and somehow I can only run one node in each session... thats not doable to release :-S

**Comment by erfajo** [comment]
I have finally released a new update with the before shown nodes in build 8317 of all versions.

**Comment by HVCFOGEY34** [comment]
Great! I'll try the new nodes out when I can! Thanks again!
