### ISSUE TITLE
Parameter.GetAssociated only outputs one association

### ISSUE THREAD

**Issue by LoganAC34** [erfajo/OrchidForDynamo#163]
### Operating system
Window 10

### Revit and Dynamo version
Revit: 2022.1.3
Dynamo: 2.12.1.XXXX
Orchid: 212.1.0.8047

### What did you do? 
Input familyDocument and parameterName (family document parameter) into Parameter.GetAssociated node.

### What did you expect to see?
All elements and their parameters that are associated to the family documents parameter (whether that's one or multiple elements/parameters). 

### What did you see instead?
Just one element and its parameter. 

### Additional info
To get the other element(s) to show, I would have to disassociate the element that was output originally and re-run the node, and still, it will only show one association at a time. My work around was put multiple Parameter.GetAssociated nodes in series while disassociating the output of each node before moving onto the next (essentially a loop, dealing with one association at a time). This duplicates and clutters the graph. 

This is what I have currently, which fortunately I only have to account for two elements associated to the parameter.
![Example](https://user-images.githubusercontent.com/6226581/191607193-5e1e210c-fdb9-46ea-9b2c-c1e1349d168c.png)

**Comment by erfajo** [comment]
Sorry, but if I must have just a chance to see what you have sent, then please zoom in on a few nodes and then use the camera uppe right, then will the image of the graph be readable. Even bette is if you can attach the graph, rename extension or add .txt to the file, then can you upload it.

**Comment by HVCFOGEY34** [comment]
Sorry, that was my attempt to give you my solution to the problem and I tent to err on the side of more info than needed. 
Attached is a very simplified graph and a test family. 
[Testfam.rfa.txt](https://github.com/erfajo/OrchidForDynamo/files/9635086/Testfam.rfa.txt)
[Get associated.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/9635087/Get.associated.dyn.txt)

**Comment by erfajo** [comment]
I have finally released a new update with the before shown nodes in build 8317 of all versions.
...and updated the sample file as well
![ParameterSet](https://user-images.githubusercontent.com/2844374/194761049-c12500fc-801c-4d6f-ba08-1289219a6ee7.png)
