### ISSUE TITLE
Document.Background Open bug

### ISSUE THREAD

**Issue by frconde91** [erfajo/OrchidForDynamo#164]
### Revit and Dynamo version
Revit: 2022
Dynamo: 2.10.1.3976 (dynamo Core) 2.10.1.4002 (dynamo Revit)
Orchid: 210.1.0.7829

Hi, 

Tried to create a script to bulk replace shared parameters in families with background open. If I freeze the script in the middle of the script (doesn't matter where), the nodes worked perfectly and as expected. If I unfreeze and run, this happens: 
![image](https://user-images.githubusercontent.com/60347608/192343838-5c69bc87-3fba-4fde-a59f-7030bd62a562.png)

And basically the subsequent convert nodes also stop working. 

I've tried different solutions to this but I'm getting nowhere. Thanks in advance for your help, I leave the script, tested family and shared parameter file in the next link: https://we.tl/t-O12qJPFmHe

**Comment by erfajo** [comment]
It seem that you are out of date with your packages, at least mine i ourdated by far!
![image](https://user-images.githubusercontent.com/2844374/192690772-b804d454-22b1-4538-9f57-97b0f14c70b0.png)
