### ISSUE TITLE
o|Tag.ByElementAndLocation doesn't let you tag already tagged elements.

### ISSUE THREAD

**Issue by soorajmathews** [erfajo/OrchidForDynamo#166]
### Operating system
Windows 10

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2021.1.7
Dynamo: 2.6.2
Orchid: 206.3.1.8227

### What did you do? 
Used o|Tag.ByElementAndLocation to place two tags on each pipe (at StartPoint & EndPoint)

### What did you expect to see?
Two tags getting created per pipe element

### What did you see instead?
One tag created per pipe element

**Comment by erfajo** [comment]
You cant tag element tagged in advance, filter your selection so you only tag untagged elements.

**Comment by soorajmathews** [comment]
The native Tag.ByElementAndLocation node lets you tag elements that are already tagged. Only problem is that the built-in node doesn't let us choose tag type. 
So was hoping o|Tag.ByElementAndLocation could be tweaked to let us tag already tagged elements.

**Comment by erfajo** [comment]
hmmm... you are right. I will take a second look at it.

**Comment by soorajmathews** [comment]
Thank you. Highly appreciate all your work.

**Comment by soorajmathews** [comment]
Excellent! Will try it out and let you know

**Comment by soorajmathews** [comment]
Works perfectly 💯
