### ISSUE TITLE
Missing nodes for Installation R21+D2.5

### ISSUE THREAD

**Issue by jptrujillol** [erfajo/OrchidForDynamo#168]
![image](https://user-images.githubusercontent.com/20504048/195967108-550de67c-05a3-4f6f-86c0-98cde68b0521.png)
Orchid: 206

I tried copying orchid files to default dynamo paths and others like c:\Orchid from installation package, and dynamo core 2.5 folder where I copied orchid core files. No luck. As I read the problem is related to paths I tried what I could but no new ideas. I have educational Revit version.

The main issue is missing nodes like SharedParameter branch and others.

Thanks !

**Comment by erfajo** [comment]
If you can't load my package I am sure it is due to the dynamo version... I don't support dynamo 2.5 anymore I support Dynamo 2.6.
Please update your Revit installation with the proper service update that includes Dynamo 2.6
