### ISSUE TITLE
Document LoadFamily Revit 2023

### ISSUE THREAD

**Issue by matius0013** [erfajo/OrchidForDynamo#169]
Hi 
I'm trying make script who load families to multiple rvt files. I can't find File.LoadFamily  document. Avaible is only node who's load families to active project file. 
I see the revit files are open and close in bacground but family is not loaded to them. What I doing wrong ? 
Revit 2023 
Orchid 213

![MULTI RODZINY_V1_2022-10-24_10-11-11](https://user-images.githubusercontent.com/116594181/197620371-46067896-b3ac-45a4-a8a5-e6cb3c82528b.png)
![excample](https://user-images.githubusercontent.com/116594181/197623652-bfc66ffa-0ffc-4689-bfd8-af9492dc51bb.PNG)

**Comment by erfajo** [comment]
I think you are looking for these nodes... Document.LoadFamily and/or Family.Load
![File+Fam-Load](https://user-images.githubusercontent.com/2844374/197773340-10262c3b-9d5d-4ff3-94c9-c0c03cd534b5.png)

**Comment by matius0013** [comment]
Why you conncect Document.LoadFamily witch .rvt document ? I don't understand this becouse in enter node Document.LoadFamily is .rfa document? Where is connection beetwen family and model files? Im example under it is clear becuse File.LoadFamily is concenction with rfa and rvt files in this same time


![image](https://user-images.githubusercontent.com/116594181/198033710-f4a0275e-f190-4ec7-9120-3f0f08f4c56d.png)

**Comment by erfajo** [comment]
Sorry for the old sample I did show you. the node is renamed... Family.Load and it takes an (family)document as input, it dont take a file any longer.
![File+Fam-Load](https://user-images.githubusercontent.com/2844374/198064714-928dbc0b-f4db-40bb-a8f1-a2c8a058fff9.png)

**Comment by Kickdak** [comment]
@erfajo will it work with multiple project files, since u have removed the document input?
I tried the setup in the image above, but it seems to only work in the file that I open dynamo through.

**Comment by erfajo** [comment]
That is correct.
Is there a need for opening multiple project files for loading multiple families?
Opening multiple project files will consume much memory and on top of that opening multiple families... So yes I removed that option since I didn't think anyone used it.

**Comment by matius0013** [comment]
Hi, for example i have a few reinforcement model in project and i need update sheet family.

**Comment by erfajo** [comment]
right, I will fix it :-)

**Comment by Kickdak** [comment]
@erfajo this script worked perfectly when I had the files local! 
But another case soon appeared when I realized that all my models are in the acc cloud or bim360...
Is there a way to use the same setup here but change it to multiple cloud models?

**Comment by erfajo** [comment]
script? what is that??? I work with graphs, please elaborate.
Next, anything in BIM360 is not handled the same way as normal files, this is why my company don't use BIM360.

**Comment by J3deye** [comment]
> @erfajo this script worked perfectly when I had the files local! But another case soon appeared when I realized that all my models are in the acc cloud or bim360... Is there a way to use the same setup here but change it to multiple cloud models?

you do have a local model file location in BIM360 that you can work with in Dynamo but its going to be a pain and you cant work with them in bulk.

**Comment by erfajo** [comment]
You have only a local file if you are the creator of the file... In my case am I in the REFM business. Meaning I receive files from our business partners, I have nothing and must therefore relink everything. This is why we require that all files are relinked when uploading to our web platform. To help our business partners I created the shown process (and nodes).
The problem includes also contractors that are dependent on models made by others…
Autodesk has really made something that is a nightmare for many with this crappy BIM360 :-S
