### ISSUE TITLE
Boolean switch nodes for Print Setup Window Option Checkboxes

### ISSUE THREAD

**Issue by growetry00** [erfajo/OrchidForDynamo#17]
Hello,
Thank you for inviting me from:
https://forum.dynamobim.com/t/print-setup-checkboxes-boolean-controlled-via-dynamo-graph/29824

I would greatly appreciate any nodes that would turn on/off the Option Checkboxes at Revit's Print Setup window.  The "Hide crop boundaries" checkbox in particular (Please see screenshot below). Thanks again for your consideration.  

![image](https://user-images.githubusercontent.com/45975442/50168728-ee724580-02a0-11e9-9e3b-b99ec3bf714a.png)

**Comment by erfajo** [comment]
I will add this on my todo list, it should be doable to create this rather fast.

**Comment by erfajo** [comment]
I have included four new nodes supporting "print options" in the latest release
![print](https://user-images.githubusercontent.com/2844374/50302449-6fd8fc00-048a-11e9-9304-8732124f7fda.png)
