### ISSUE TITLE
Unable to find node document.loadfamily after installation

### ISSUE THREAD

**Issue by Niki-ko** [erfajo/OrchidForDynamo#170]
Revit: 22.0.2.392
Dynamo: 2.10.1.3976
Orchid: 212.3.0.8329

Hi,

I can't find the Document.LoadFamily node in the package.
I have searched through the libaries, but it's not there.
As far as I can tell I've installed the package correctly.
Can you tell me where this node should be?

Thanks in advance!

**Comment by erfajo** [comment]
You are right... I need to update my samples :-S
that is what happens when you have more than 700 nodes :-S
![image](https://user-images.githubusercontent.com/2844374/197803045-59bcfdb9-bf9a-49d7-87e6-280b19b30ae9.png)

**Comment by Niki-ko** [comment]
Thank you so much for fast reply.
But that's not the one I meant.
![grafik](https://user-images.githubusercontent.com/116289088/197804089-fd2e9347-8df2-4345-bd63-0c84a135884e.png)
This is a different node, isn't it?

**Comment by erfajo** [comment]
thats right... and now it is named "Family.Load" and takes either an family or an (family) document
![File+Fam-Load](https://user-images.githubusercontent.com/2844374/197958667-b32f0704-c15b-46b2-8e0c-bb6e9a87e371.png)

**Comment by Niki-ko** [comment]
oh ok, well thank you!
