### ISSUE TITLE
Some List function nodes give warning and don't pass data

### ISSUE THREAD

**Issue by thomartfitz** [erfajo/OrchidForDynamo#171]
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 22.0.2.392
Dynamo: 2.10.1.3976
Orchid: 2.12

### What did you do? 
Using specific list function nodes (List.replaceitematindex, list.getitematindex, list.insert) give the error "Unable to castobject of type 'systemint64' to type 'system.collections.ilist'".  Used in simple lists and operations (1..10..1; etc etc) give the same error. I have received the error even when using Orchid 2.06. I do not recall getting the errors in prvious dynamo builds with 2.06 Orchid.

### What did you expect to see?
The node attempting to do the function of the node

### What did you see instead?
This error message
![Screenshot (2)](https://user-images.githubusercontent.com/116904080/198681464-7617a133-fe3f-48a9-8e5a-fe7a80a82964.png)

Thanks!

**Comment by erfajo** [comment]
Thanks for heads up :-)
this clearly reminds me that I have to implement int64 for 2022 and beyond :-)
i will fix this asap :-)

**Comment by thomartfitz** [comment]
[erfajo orchid list nodes bug.zip](https://github.com/erfajo/OrchidForDynamo/files/9922496/erfajo.orchid.list.nodes.bug.zip)


Apologies for the delayed reply. Here is a sample graph. I just used simple sample data without regard for list levels or lacing, as the nodes errored out before even attempting to do the work. In the graph i attempted to use them in, they were lists of points. Since it didnt seem like the error was happening with the type of data provided, i only gave the simple sample data. 

The nodes in the graph are the ones that i found that were erroring. I didnt run through all the nodes in the list category, but i have used others, such as List.Clean, without any issues. 

Thanks for creating such great tools! I literally use them all the time. 

Keep up the great work

**Comment by erfajo** [comment]
Sorry for the long delay, however, the good news is that nothing is wrong with the node... but you need to understand how my nodes work since they work quite differently than the ootb node do.
try to see my sample collection in the core folder
https://github.com/erfajo/OrchidForDynamo/blob/master/Samples/Graphs/Core/List%20Index.png

**Comment by thomartfitz** [comment]
Hmmm okay, sorry for the wild goose chase, I really thought they were
broken haha. I'm on mobile now, but will review the items you sent
tomorrow. Thanks for being on top of it!

-Thomas

**Comment by erfajo** [comment]
I can see that I have written in the "help" for the node that it works on nd lists, but I have now added a warning to all nodes based in index, hopefully this will prevent others from thinking it is alike the ootb node

the warning added in next release :-)
"Note. This function works differently than the Dynamo ootb node does, please examine the sample collection for usage!"
