### ISSUE TITLE
FamilyParameter.Associate - can't get it to work with background opened families

### ISSUE THREAD

**Issue by Lazarica-t** [erfajo/OrchidForDynamo#173]
### Operating system
Windows 11

### Revit and Dynamo version
Revit: 2020.2.8
Dynamo: 2.3.1
Orchid: 203.5.0.8347

### What did you do? 
I'm trying to open multiple families in the background and associate a material parameter to the geometry inside them, but I can't seem to make it work:
![image](https://user-images.githubusercontent.com/49474519/200577551-1ddd4904-a6ae-4ec9-aa52-10a4432c131a.png)
![image](https://user-images.githubusercontent.com/49474519/200577633-a040fe77-c5dc-426e-87e7-c692a5061459.png)

### What did you expect to see?
In older versions it worked just fine, see images bellow:
![image](https://user-images.githubusercontent.com/49474519/200577695-758a451e-f01b-44cb-b863-794cf1c5d25d.png)
![image](https://user-images.githubusercontent.com/49474519/200577746-b123c75b-a107-4572-ab99-d94946c0dd41.png)

### What did you see instead?
I've attached my files bellow.

Is there a new workflow for this? Or is this even a supported feature anymore?
 Thank you!
[Test_Param associate.zip](https://github.com/erfajo/OrchidForDynamo/files/9961539/Test_Param.associate.zip)

**Comment by erfajo** [comment]
well... I just openend the graph and ran it!?
![image](https://user-images.githubusercontent.com/2844374/200789022-b45ad04f-b0e4-44c3-ba61-7fe606476ec9.png)

**Comment by erfajo** [comment]
found the problem... something with background loaded files...
thanks for reporting, i will look into it :-)

**Comment by erfajo** [comment]
well the problem is not my nodes but the builtin nodes...
![image](https://user-images.githubusercontent.com/2844374/200793352-19672f46-0f23-45ae-8f05-d55d49546181.png)
I dont think that has ever worked, I will try to see If I can code a node...

**Comment by Lazarica-t** [comment]
> found the problem... something with background loaded files... thanks for reporting, i will look into it :-)

Well that is good news 👍

**Comment by erfajo** [comment]
so now I just need to round it all up and release :-)
![image](https://user-images.githubusercontent.com/2844374/200800025-a5897063-8a2d-49c2-87cb-6332751f1e0f.png)

**Comment by Lazarica-t** [comment]
Awesome! 👏 Looking forward in testing 😸

**Comment by erfajo** [comment]
Here is the updated graph and some new nodes is released, please update you packages :-)

remove .txt from file
[ARC-GEN-DAT-Batch_family_associate_parameter-8347_erfajo.dyn.txt ](https://github.com/erfajo/OrchidForDynamo/files/9972449/ARC-GEN-DAT-Batch_family_associate_parameter-8347_erfajo.dyn.txt)

**Comment by Lazarica-t** [comment]
It works!! 💯 Awesome!
Really nice job ! 🥇

**Comment by erfajo** [comment]
and you did see all the light red boxes for informations, I noticed you python node and I know that several of the things you do inside that are going to be deprecated :-)

**Comment by Lazarica-t** [comment]
To be honest, it's just something part of the template we use where I work at.. I never really did bother with it 😆 
But good to know 👍  maybe we will remove altogether.
