### ISSUE TITLE
Document.loadfamily now only works with RVT files. 

### ISSUE THREAD

**Issue by J3deye** [erfajo/OrchidForDynamo#176]
Revit version 2022
Orchid version, most recent build for 2022

First thank you so much for your awesome package and work on this :) 

I am trying to load my active family, which is nested into many other families, into that list of RFA files in the background. Document.loadfamily will now only accept RVT files as an input. As you can see I tried multiple different nodes, they all seem to load the list into my current family and not the other way around. thoughts? 
![kitchen](https://user-images.githubusercontent.com/94412985/202603541-33f2886d-d4fb-4775-a397-7ecf9c389a31.png)

**Comment by erfajo** [comment]
I see... I will fix this "error" for the next release.
Apparently, I totally have underestimated how many used that function when I deprecated it (August 2022) and hereafter when I added it again (October 2022) but with some new code. However, thanks to all who have been writing me for this node :-)

**Comment by J3deye** [comment]
Thank you for building all of this! 

I have this situation where I have shared families nested into larger libraries of families. When I updated the shared family it then needs to be loaded back into all of the other families it is nested into, and it varies a lot from family to family, which it was loaded into. Automating that, even with significant time and memory usage, would be invaluable to me. 

I really would want to learn how to code it myself to be honest, but I am just descent in python and very new to API. Ive been playing with some code from a Ehsan tutorial, but got stuck at trying to iterate the load over a list of files opened in the background.

**Comment by erfajo** [comment]
I do understand it is not that easy to read and understand an API, but for me is it an open book of options where I don't know where to stop... there is so much I can do, and it is just there waiting for me to reveal it. I love to do what I am doing :-)
The node is changed, and Orchid 216 is released due to Revit 2023 SP1

**Comment by J3deye** [comment]
So thanks for the updated node! It is working with RFA files now but I am unfortanately still having a bit of an issue, the family in question is a shared family, and I am getting this error when attempting to load- 

![overwrite error ](https://user-images.githubusercontent.com/94412985/202907898-32428b2a-8860-4c82-b757-79c2ea1d4f6d.png)

Here is the error from the Orchid node -

![error from orchid node ](https://user-images.githubusercontent.com/94412985/202907905-ecc8cfcd-c691-459e-841e-222b6dbed132.png)

also a minor detail, the node works with RFA but its tooltip still says RVT  file.

**Comment by erfajo** [comment]
That sounds like a problem... but if you can do what you want to do manually inside Revit without using Dynamo, then we can build it for Dynamo as well. So the question is, can you do what you're trying to do in Dynamo manually?

**Comment by J3deye** [comment]
I can yes but this is part of a larger workflow i am developing for my team. we have put whole arch units into families and within them they share bathrooms and kitchens, so we may have 40 unit types but only 3-4 kitchen typees and bathroom types that are housed in nested shared families. I am trying to design something that will allow my architects to edit a kitchen and then hit an "updated nested kitchens" button and it loads htat kitchen into the families it is nested into, either from UI selection, or ideally I read the nested families of the unit types and filter them down to only the ones that have that kitchen and load it in automatically to those files. Without an automated solution, they make a mess of my units. 

I could update this in project, but I am also using your create solid nodes to convert the majority of these elements to import  instances when loaded into project, so we can load a unit that has a file size of about 2mb into our actual revit project instead or loading the family, allowing us to keep placeholder units in our file up until CD's, thus making it MUCH faster and lighter to work with. without the nested shared families to overwrite in project however, I left with this problem of updating edited kitchens and baths without using an RVT environment, which led me down this road. 

looking into IFamilyLoadOptions, it seems that this will do what I need- provide the options to overwrite the shared family if found. I have been working on this in python, code below: 

`#thanks to Gavin Crump for the base code here 

import clr

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitAPI")
import Autodesk 
from Autodesk.Revit.DB import *
from Autodesk.Revit import DB

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

clr.AddReference('System')
from System.Collections.Generic import List

currDoc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


def tolist(input):
    result = input if isinstance(input, list) else [input]
    return result


paths = tolist(IN[0])
docs = []

#opening a list of docs in the background and sending it to docs

for path in paths:
	try:
		doc = app.OpenDocumentFile(path)
		docs.append(doc)
	except:
		docs.append(None)

#from a Pyrevit Workshop https://www.notion.so/Python-Revit-Coding-Sessions-3cdc3a58519140e2a0df8248e918aed1

class FamilyLoaderOptionsHandler(DB.IFamilyLoadOptions):
    def OnFamilyFound(self, familyInUse, overwriteParameterValues):
        overwriteParameterValues = True
        return True

    def OnSharedFamilyFound(self, sharedFamily, familyInUse, source, overwriteParameterValues):
        source = DB.FamilySource.Family
        overwriteParameterValues = True
        return True

#mycode, attempting to iterate the LoadFamily method and Hassa's Floader class over my list of background docs

for doc in docs:
	TransactionManager.Instance.EnsureInTransaction(doc)

	fload_handler = FamilyLoaderOptionsHandler()
	doc.LoadFamily(currDoc, fload_handler)
	
	TransactionManager.Instance.TransactionTaskDone()`

but its throwing an error - 

Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed.
Traceback (most recent call last):
File “”, line 56, in
Exception: The input argument “document” of function `anonymous-namespace’::Transaction_constructor or one item in the collection is null at line 94 of file E:\Ship\2022_px64\Source\Revit\RevitDBAPI\gensrc\APIUndoTransactionProxy.cpp.
Parameter name: document

I am unfortunately well beyond my knowledge here.

**Comment by erfajo** [comment]
I removed your Python code since that is what I perceive as spam. Nothing in that code is new, this is exactly what I also do in my family load. Besides am I sure that I was the one who put up this code initially many many many years ago, and it does apparently still live on today.

**Comment by J3deye** [comment]
yeah sure, here is a link to a few test files I have been working with and the dyn file. its too big to put in Git, so I uploaded it to my Drive 

https://drive.google.com/file/d/1OvcGuwsb5s-E9Nfzg3hs3ak7kB4zqH9q/view?usp=sharing

**Comment by J3deye** [comment]
Its working perfectly now thank you so much!
