### ISSUE TITLE
ParameterFileter.ByRule iddur

### ISSUE THREAD

**Issue by camirozario** [erfajo/OrchidForDynamo#178]
### Operating system
(e.g. Windows 7, Windows 10, etc)

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for the Orchid version, go to Packages > Manage Packages_)
Revit: 2022
Dynamo: 2.10
Orchid: 2.12

### What did you do? 
I am creating multiple filters by rule and applying to my views

### What did you expect to see?
I expected all my filters to be generated and work and when applied to views be able to color my elements accordingly. 

### What did you see instead?
Apparently, the filters are set up correctly in the filter properties they all seem to be set alright however when I apply them to my view they won't work unless I  enter in the filter and click okay inside of the properties. Even though they seem to be set alright Revit does not seem to be recognizing them. Apparently, the only filter that works is the first filter rule in my rules list (this one is set and applied perfectly) but for the rest I have to go into my project and press okay.

Filter is apparently being set up alright
![image](https://user-images.githubusercontent.com/80728454/207066559-d84c4a29-8c31-48d1-b927-05bc176c0930.png)

Filters are applied to view and visible 
![image](https://user-images.githubusercontent.com/80728454/207066682-25c1abd8-e170-440f-97d1-73728a65895e.png)

Only yellow filter works  (first one generated with the dynamo script)
![image](https://user-images.githubusercontent.com/80728454/207066861-147a1448-5808-4c8f-8ce3-c131f789bd6f.png)

Tried removing and reading the filter to view -> nothing happend.
Tried opening the filter settings and reassigning values to it -> worked.

I believe the issue happens when the filter is created

**Comment by erfajo** [comment]
please add the graph, you can rename it by adding ".txt" to the file and then upload.
