### ISSUE TITLE
Tag.ByElementAndLocation Operation Fail - "Length" Type not found

### ISSUE THREAD

**Issue by Hamel-BS** [erfajo/OrchidForDynamo#180]
Windows 11

Revit: 2020.2.9
Dynamo: 2.3.2.15696
Orchid: 203.5.0.8388

I have been using the Tag.ByElementAndLocation node in one of my scripts. It use to work fine, but recently updated Orchid and reinstalled Revit and It has started throwing an error:

Warning Tag.ByElementAndLocation operation failed.
"Length" Type not found in document.

![Screenshot 2022-12-22 112459](https://user-images.githubusercontent.com/121231976/209124295-ebdc9d14-865e-4da6-a460-6a4e96a14a14.png)

**Comment by erfajo** [comment]
I need some more information... please attach the graph, you can add ".txt" to the file and it can be uploaded...

**Comment by Hamel-BS** [comment]
Hi,

Thanks for your assistance, I have attached a simplified version of my graph. But produced same error, nonetheless.

Thanks, H

**Comment by Hamel-BS** [comment]
Hi,

Thanks for your assistance, I have attached a simplified version of my graph. But produced same error, nonetheless.

Thanks, H
[Github_DYN_TagView.txt](https://github.com/erfajo/OrchidForDynamo/files/10294593/Github_DYN_TagView.txt)

**Comment by erfajo** [comment]
good thing I found the area, the bad thing... I cant manage to fix it today :-S

I have made some errors in my translation scheme from the old to the new unit system...

example I lookup 
case "CoolingLoadDividedByArea": val = "UT_HVAC_COOLING_LOAD_DIVIDED_BY_AREA"; break;
or
case "UT_CUBIC_FEET_PER_MINUTE_SQUARE_FOOT": val = "CubicFeetPerMinuteSquareFoot"; break;

however, I made mistakes in some lines... must have fucked up the excel lists, and it looks more durable to start over :-(
damm...

**Comment by Hamel-BS** [comment]
Thank you very much for resolving this! Much Appreciated
