### ISSUE TITLE
Copy Welcome Screen Sheet from Source model to Target Model

### ISSUE THREAD

**Issue by AbdallahZakaria** [erfajo/OrchidForDynamo#181]
Hiii Erfajo,
I'm trying to create a dynamo graph to copy the splash screen sheet from one model to another without opening either the source or the target models.
the dynamo graph is working well but it copies the sheet without its contents (just get an empty sheet ).
Could you please help in solving this issue?
The splash screen sheet got by dynamo looks like in the shown image below
 
![image](https://user-images.githubusercontent.com/41986525/210768680-bdfe1ce6-bcbb-46bf-ac97-a467807fd67b.png)

but it should be like what is shown in the image below

![image](https://user-images.githubusercontent.com/41986525/210769192-292094ac-0ab6-4285-80e5-74e3b8519009.png)

My graph is shown below

![Copy Splash Screen sheet From document to another](https://user-images.githubusercontent.com/41986525/210771021-5437d5d3-d755-4801-9967-f7010bd29c47.png)

**Comment by AbdallahZakaria** [comment]
thanks a lot for your answer but could this be done by dynamo ?

**Comment by erfajo** [comment]
Sure... "Document.LoadFamily" or "Family.Load" depending what you find best...

All shown graphs are available in the sample collection.
![BulkLoadFamily](https://user-images.githubusercontent.com/2844374/211351120-5e0ab7c6-ec2f-4f1a-97ea-2a240e62e759.png)
![Load families](https://user-images.githubusercontent.com/2844374/211351456-523e2623-da54-4b99-9d2d-e1fe713de754.png)
![File+Fam-Load](https://user-images.githubusercontent.com/2844374/211351690-93bd3584-fd63-4b36-8f29-9f46e7662911.png)
