### ISSUE TITLE
Shared Parameter - Input Documentation for data type

### ISSUE THREAD

**Issue by OlafKammler** [erfajo/OrchidForDynamo#182]
Hi!
I want to read an excel list to create shared parameters in a Revit Project.
I stumble over the data type - the usual types are working fine (TEXT, NUMBER, MULTILINETEXT, ...).
For the following types, I get an error:
ELECTRICAL_DEMAND_FACTOR
ELECTRICAL_WATTAGE
ELECTRICAL_EFFICACY
ELECTRICAL_LUMINOUS_FLUX
ELECTRICAL_APPARENT_POWER
ELECTRICAL_POTENTIAL
ELECTRICAL_FREQUENCY

![image](https://user-images.githubusercontent.com/59934637/214072910-db37c3c0-8463-4038-b5a1-db809325d7bd.png)

I could not find documentation on how to call them correctly. With try and error, I figured ELECTRICAL_WATTAGE is called WATTAGE. How about the others?

Kind regards
Olaf

**Comment by OlafKammler** [comment]
I found a solution to figure out Group Type IDs and Spec Type IDs. I collected them in two CSV Files.

I hope the mentioned spec types are the right ones.

[Revit Group Type ID.csv](https://github.com/erfajo/OrchidForDynamo/files/10482131/Revit.Group.Type.ID.csv)
[Revit Spec Type ID.csv](https://github.com/erf
[ReadOut All Group AND Specs Types to Excel.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/10482137/ReadOut.All.Group.AND.Specs.Types.to.Excel.dyn.txt)
ajo/OrchidForDynamo/files/10482132/Revit.Spec.Type.ID.csv)

**Comment by erfajo** [comment]
I made nodes for this a while ago, and have made samples for this as well... As I remember it there is also an issue with it and maby also something in the dynamobim forum...

Try to see the sample folder for Families and for projects

Family:
![LightSource](https://user-images.githubusercontent.com/2844374/214334433-87bb5e06-ed4c-4fbb-852d-172cf24350ed.png)

Project:
![LightSource_FamilyType](https://user-images.githubusercontent.com/2844374/214334646-44dc8332-363a-4508-ab8c-2b326e036527.png)
