### ISSUE TITLE
Set shared parameters in family documents 

### ISSUE THREAD

**Issue by jwvanasselt** [erfajo/OrchidForDynamo#183]
Hi,

I try to use the set parameter by family documents but somehow I don't get it to work in multiple documents.

Can you take a look ?

https://forum.dynamobim.com/t/set-parameter-by-name-shows-errors-saves-family-and-does-not-close/23883/24?u=jw.vanasselt

Kind regards,

Jan Willem van Asselt

**Comment by erfajo** [comment]
You can describe the problem here and I will try to see if it is a node problem or a usage problem.

**Comment by jwvanasselt** [comment]
Hi @erfajo ,

My bad, over here the problem.
I try to use the node FamilyParameter.SetValue with multiple documents:

![image](https://user-images.githubusercontent.com/122460731/215423636-a657763d-1690-4f4d-af15-3497c9fbc616.png)

I want to set multiple parameters for each type with his own value.
Is this possible?

Over here the link with some attached files.

https://we.tl/t-BkDjtuu6n4

In this case I use the excel for retrieving the family documents and the parameter names.
You can ignore the rest of the excel.

Let me know if you need more information.

Kind Regard,

Jan Willem

**Comment by erfajo** [comment]
Your issue is problematic since you want to change every parameter individually and the node is not coded for that.
However, I do understand why you want to do that, but I am in a comprehensive coding phase right now for other things, so I must postpone looking at this issue until later.

**Comment by jwvanasselt** [comment]
Thanks for the response.

For me it's okay to do it with single parameters with multiple family/types for now.  
But how can I do that? 

I tried that to:

![image](https://user-images.githubusercontent.com/122460731/215510248-29cc38e3-5ad4-4c42-a2d9-9859d2f6f230.png)

**Comment by erfajo** [comment]
it is multiple document that is the problem... if it was only one document you could combine it as you please, and if it was multiple documents but with same parameter value the would it be ok... so it is the combination.

**Comment by jwvanasselt** [comment]
Ah, that make sense.  Thanks.

**Comment by erfajo** [comment]
Good news is, that it was quite easy to recode the node, but now I need to test all the other scenes to see if it also work under those conditions.
AND I need to finish my coding branch I am working on at the moment, should be finished within few days.
![image](https://user-images.githubusercontent.com/2844374/215551973-d67e5a86-64ba-4d2a-a75f-bbcae9c4ef64.png)

**Comment by erfajo** [comment]
I have uploaded a new release...

**Comment by jwvanasselt** [comment]
Thanks alot @erfajo!

**Comment by jwvanasselt** [comment]
Well done, it works! 
Do I need to close this topic?
