### ISSUE TITLE
IFC nodes stopped working

### ISSUE THREAD

**Issue by Mordeton** [erfajo/OrchidForDynamo#185]
Hi.

OS: Windows 10
Revit 2022

I've been using the orchid package for some time with no problems.

Recently most of the ifc nodes stopped working and are giving me (i think) API-errors.

Ive made sure the ifc for revit addon is installed (The versions number is displayed in the ifc-export window).

What i've tried:

- Updating/reinstalling Orchid and ifc for revit to newest versions
- Opening the ifc-export settings before (and also after) opening dynamo

Heres an examples:

![Snag_48058f](https://user-images.githubusercontent.com/80106109/216271206-ad0608b6-6f71-4d58-8855-ce451099d2c0.png)

I also cant place this node any more:

![image](https://user-images.githubusercontent.com/80106109/216272000-8b7d4bd7-4c17-4a32-8187-310c5491832f.png)

**Comment by Mordeton** [comment]
SOLVED!

Downgrading to Ifc for revit version 22.5.0.0 worked

**Comment by erfajo** [comment]
Well... I must try to see the new release... But I know that they have only released it for 2022 yet, and will not release it for 2020, so now I have to code for separate versions :-S

**Comment by erfajo** [comment]
I released a new version yesterday that supports the new IFC exporter 22.6.0.0.
Newer versions of the IFC exporter for Revit 2022 have been recoded so the work as the exporter for Revit 2023 and beyond.
I fear that this means that nothing will be updated for the IFC exporter for 2021 and before :-S
