### ISSUE TITLE
Dynamo Error - 0.0.3

### ISSUE THREAD

**Issue by EasyBIM-Reut** [erfajo/OrchidForDynamo#186]
**Occurs in all version, for referance I'll use Revit 22**
Revit: 22.0.2.392
Dynamo:
Core - 2.10.1.3976
Revit - 2.10.1.4002
Orchid: 0.0.3

Hello,
I keep getting error 0.0.3 when trying to download Orchid package - There is no description what this error means. I used to work with Orchid for a while and it worked perfectly (I download Orchid from github+install package in Dynamo - for each Revit version). I tried uninstalling/installing Orchid again but it wont work. To be clear, I closed Revit/Dynamo before installation.
What could be the problem? Thanks!

![2023-02-07_8-29-04](https://user-images.githubusercontent.com/105439633/217209267-dfef041a-a20d-44d5-9263-9124ae800bf6.png)

**Comment by erfajo** [comment]
You are using Dynamo 2.10 but the Orchid version is for 2.12. You should update your Revit to the latest servicepack... and please remove DanEDU it is by far outdated by now.

**Comment by EasyBIM-Reut** [comment]
Thank you, I updated Revit & uninstalled-reinstalled Orchid and it worked!

**Comment by erfajo** [comment]
Thing is, that Autodesk does quite some updates in their API these days, especially how units and parameters are dealt with... so there is no point of return, and just following all the changes between the last three versions is a job to do... glad that it all works for you now :-)
