### ISSUE TITLE
Installing the Orchid-package?

### ISSUE THREAD

**Issue by clausneergaard** [erfajo/OrchidForDynamo#187]
### Revit, Dynamo and Orchid version
Revit: 2023
Dynamo Core: 2.13.1.3887
Dynamo Revit: 2.13.1.3891
Orchid: 212 / 216

### The issue
Hello, Erik -

I am having a hard time figuring out how to install your package, Orchid. I feel like I've tried everything. Downloaded it from your GitHub, I've tried installing older versions, etc. But it just keeps showing up in my Dynamo with the one node that I don't like, anymore, which is the About.ReadMe-node that gives me the link to your GitHub-page.

I've read a lot of the previous issues here, on your GitHub-page, and I seem to be unable to find any answers.

When I download the install-package from your GitHub-page, I get it to run fine - it seems like it is installing everything the right way, and I've made sure that both Dynamo and Revit is both closed down while installing, and all ...

So, I am out of options.
I hope that you can help me out, any thoughts or ideas is appreciated.

Thanks!

Best,
Claus

![about, Dynamo](https://user-images.githubusercontent.com/7966833/217948871-7237ea58-7951-4a55-b7dd-00dfd8693ef7.jpg)

![about](https://user-images.githubusercontent.com/7966833/217948891-a0a26df7-aae0-499a-a409-fe86489d10fe.jpg)

**Comment by c2k-** [comment]
I also was unable to get it to work with the installer. Like you I found that it seemed to install, but the nodes were not there.
I ended up using the manual approach and now I can see the nodes.
https://github.com/erfajo/OrchidForDynamo#manually-installation

**Comment by clausneergaard** [comment]
Allright! Thanks, @c2k-, I appreciate your inputs. I've just tried your approach as well, but it still won't work. 

I don't get it.

**Comment by clausneergaard** [comment]
Ah ... It worked! Thanks, man! I've got all the nodes. Amazing!!

**Comment by erfajo** [comment]
Hi Claus,

One of the most common issues with installers is the "protection" put up by companies and/or the windows system in general. I think that most issues can be solved by "allowing" the installer and/or the assemblies to be activated.
If you downloaded the Dynamo Sandbox versions, you would experience the same issues, namely blocking.

that is why I have tried to describe the issue on the error page
https://github.com/erfajo/OrchidForDynamo/blob/master/Error.md

**Comment by clausneergaard** [comment]
Yeah, I get that the Windows-system isn't always allowing all this stuff. But, it is not always easy, I find, to overwrite all of these blocked paths.

I'll keep the link for future reference.

Thanks again!

**Comment by erfajo** [comment]
I am affraid that you should update your Orchid already today... I have made a larger revision for all nodes creating parameters, both for families and projects... those nodes now take Dynamo SpecType and Grouptype if you use Revit 2023/Dynamo 1.16

**Comment by clausneergaard** [comment]
Check! Thanks.
