### ISSUE TITLE
0x00000007 error while working in family documents

### ISSUE THREAD

**Issue by Christopher-Pepin** [erfajo/OrchidForDynamo#188]
### Operating system
Windows 10

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2023.1.1
Dynamo: 2.16.1
Orchid: 216

### What did you do? 
Created a new family. Opened Dynamo and placed a FamilyDocument.Current node.

### What did you expect to see?
It to return the family document so I could pass it to a FamilyParameter.ByName node so I could read the parameters value.

### What did you see instead?
When placing the node or almost any other node related to a revit family document I get a 0x00000007 error.

**Comment by erfajo** [comment]
I need further informations, and maybe interaction, so it would help a lot to know if you are located in Denmark? or by which company do you work?

**Comment by Christopher-Pepin** [comment]
Just tried again with the latest version I could find, 216.3.0.5796, and the problem seems to persist exactly as before. Steps to replicate are still the same


Create new family, Generic Adaptive in my case, open up Dynamo from Revit, place FamilyDocument.Current node. Each time I get the same 0x00000007 error

**Comment by erfajo** [comment]
Sorry, but I can only build once a day, since I use the daynumber (5796) as my Build sequence. However, yesterday I found the error after I had made the build and released it, so I made an upload (5796#1). Did you download that version?

**Comment by Christopher-Pepin** [comment]
Tried downloading the latest build again and everything seem to work perfectly. Thank you for your patience, you are truly a saint.

**Comment by erfajo** [comment]
I am so relieved, trying to build something new, and it then resolve into everything failing is not funny 😀
Many thanks for your help pointing out that errors surely was possible 😀
