### ISSUE TITLE
Check if a parameter is being associated within a family

### ISSUE THREAD

**Issue by Chrono9084** [erfajo/OrchidForDynamo#19]
The goal is to be able to verify that a nested family has it's parameters properly associated with the host families parameters.

A huge bonus would be if it were possible to run this from a project environment where we specify the family (in my case, a titleblock), specify the nested family (in my case, a logo family), and the node provides all parameters that are associated (both instance and type).  Output much like the following picture would suffice:
![image](https://user-images.githubusercontent.com/37596510/51140335-e22fc880-180b-11e9-9237-82cad7ff4efa.png)

The node shown in the picture above only checks instance or type parameters depending on whether you feed it element or element type.  It would be very helpful if your node took the element and provided both type and instance parameters.

**Comment by erfajo** [comment]
Thanks, I have actually already coded it, but I am also coding other nodes... I will release them asap.

**Comment by erfajo** [comment]
here is the new node checking if a parameter has associated elements (...in upper right corner)
![nested-lookup](https://user-images.githubusercontent.com/2844374/51440691-fb33f000-1cc9-11e9-9cc5-227b29cf25cc.png)

**Comment by Chrono9084** [comment]
@erfajo This is great.  It works perfectly.

Would it be hard to create a secondary output which reports the parameter that is associated to the input parameter?

**Comment by erfajo** [comment]
I had an idea that this would be your next question, so I will put this on my list. However, I have an idea that this is a bit more complicated, since this information require that you open all the nested families… but I am not sure.

**Comment by Chrono9084** [comment]
I wanted to provide a bit of testing feedback and see if I am misunderstanding how this works.  The results seem....inconsistent but it may be due to my graph being setup incorrectly.  I will include a complete screenshot of my graph at the bottom.

![image](https://user-images.githubusercontent.com/37596510/51547457-f71fe380-1e2b-11e9-95f9-6f0ed85fbeec.png)
Here are the results if I run the graph with the titleblock parameter associated and the nested family parameter associated correctly.

![image](https://user-images.githubusercontent.com/37596510/51547739-7f05ed80-1e2c-11e9-8ac2-e0744b9ca1b2.png)
Here are the results if I go into the titleblock family and disassociate the AllInOne logo's Professional Engineer Logo Type parameter.

![image](https://user-images.githubusercontent.com/37596510/51547851-b1afe600-1e2c-11e9-9670-8c484e4dd256.png)
Here are the results if both the titleblock and nested family have this same parameter disassociated.

![image](https://user-images.githubusercontent.com/37596510/51547949-e15eee00-1e2c-11e9-8ced-52560b57e298.png)
Here are the results if the nested family is associated correctly but the titleblock is not.

Here is my entire graph:
![testing](https://user-images.githubusercontent.com/37596510/51548063-2551f300-1e2d-11e9-9c5a-6f3f794f59a2.png)

**Comment by Chrono9084** [comment]
Erfajo,
Just curious what the status of this is?  Again....I can't explain how much I appreciate your effort.

I am drafting a guide for the usage of my current graphs and am trying to figure out if I will be able to complete the checker graph that relies on the completion of this functionality.  If it will not be done soon then I will just leave that out for now.  No worries....just checking in.

**Comment by erfajo** [comment]
I am working on this issue in writing... I can find the parameter which is associated, but i need to test it deeper to be sure it gives me the correct result.

**Comment by Chrono9084** [comment]
One other question that relates to this node: Is it possible with your current collection of nodes (or possibly out of the box nodes) to check if a family/family type has it's parameters associated to global parameters?

**Comment by Chrono9084** [comment]
Thanks again!

**Comment by erfajo** [comment]
the beta is released in the builds folder as "BETA_6971" 
https://github.com/erfajo/OrchidForDynamo/tree/master/Builds

please report if there is any issues.

**Comment by erfajo** [comment]
new beta --> BETA_6972
![family-associated](https://user-images.githubusercontent.com/2844374/52167638-6ea01d80-271e-11e9-90f2-320ffb9c90ac.png)
