### ISSUE TITLE
Document.ImportImage and ACC Docs

### ISSUE THREAD

**Issue by davidclark70** [erfajo/OrchidForDynamo#193]
Hi, On work shared projects on our local server Document.ImportImage works flawlessly.  I create a QR image in the users temp file, then use Document.ImportImage to bring it into the project.  
We are now using ACC Docs to host our projects and found that the image path is remaining as the users temp folder.  Do you know is there is any workaround for this?
Revit 2022 Orchid 212.3.0.8342
Thanks!
![image](https://user-images.githubusercontent.com/47121186/223861816-8f1e0e02-56a9-41af-9205-479c09632872.png)
![image](https://user-images.githubusercontent.com/47121186/223861835-73f37003-1213-400c-b67c-f3504bf3a006.png)

**Comment by erfajo** [comment]
I don't think so, this is probably due to access restrictions on the folder.
Does it work if you move the images to another folder without any restrictions? (c:\temp or so)

...and you can use "Await" node insted of "passthrough" :-)

**Comment by davidclark70** [comment]
It does not seem to matter where the images are.  For now, I'm going to write them to our local server folder and reference them there.
.....and yes I use "Await" as well as "passthrough" !
Thanks!

**Comment by erfajo** [comment]
did you remember to test a folder not "owned" by you?

**Comment by hoanhquy** [comment]
> I don't think so, this is probably due to access restrictions on the folder. Does it work if you move the images to another folder without any restrictions? (c:\temp or so)
> 
> ...and you can use "Await" node insted of "passthrough" :-)


Hi, I am facing the same problem here. The node Document.ImportImage cannot work with restricted folders. I tested it with my local folder, and it worked normally. However, I need to place my project in a server folder. Do you have any solutions for this?

**Comment by erfajo** [comment]
This is not purely a Revit issue it is more a Windows credential issue, and there is not that much I can do regarding that... You have to have the proper credentials then everything should work, meaning you have to have RW access as I remember it.
