### ISSUE TITLE
o|Link.SetCadFile node returns error with 0x00000007/u01

### ISSUE THREAD

**Issue by TimoeTrex** [erfajo/OrchidForDynamo#194]
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 2020.2.6
Dynamo: 2.3.1.11830
Orchid: 203

### What did you do? 
I'm trying to link CAD files in several views. I did it successfully in Revit 2018 with Dynamo2.0 using an old version of Orchid which can't be found now. 

But then I wrongly updated the orchid package in Dynamo by searching Orchid package and ignored the warning during the update. When I found out that it should only be downloaded and installed by github, it's been too late and I had to update my Revit to 2020.2.6 for dynamo2.3 so that I could install Orchid 203.

Unfortunately, in this version of Orchid, the node "o|Link.SetCadFile" seems to have some issue,  with a warning said "A serious issue (0x00000007/u01) has occurred, please contact the author of the package!" when I ran the program.

### What did you expect to see?
Maybe it could be fixed soon or is there any way that I could get an older version of Orchid for my Revit 2018 with Dynamo2.0?
Thank you!

### What did you see instead?
![image](https://user-images.githubusercontent.com/127360799/223883616-d38551e1-43c9-4cb2-a9af-d1b8368893c3.png)

**Comment by TimoeTrex** [comment]
In the latest version（5812）this bug has already been solved！Much appreciated！

**Comment by erfajo** [comment]
glad that it worked since many users have reported that error (that derives from the windows API)
