### ISSUE TITLE
Schedule formatting

### ISSUE THREAD

**Issue by ZeroXeroZyro** [erfajo/OrchidForDynamo#202]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 22.1.30.34
Dynamo: 2.12.1.8411
Orchid: 212.4.0.5879

### The issue
I can't seem to get the column width assignment to work properly using the schedule.formatting node. I've tried many different values in various different forms through various different nodes. I get the same error each time "This ScheduleFiled cannot display minimum and maximum values.". The schedule field in question is a text parameter in a Generic Models schedule made using schedule keys. I tried the same method with other schedules by building components as well, returning the same error. I'm not sure if I'm doing something wrong or if there as an issue with the version I downloaded perhaps, but I can't figure it out. I attempted to include my .dyn file, but the file extension is unsupported.
![Orchid](https://github.com/erfajo/OrchidForDynamo/assets/120753906/7e309c6d-61d7-4b98-8118-d9e5d1c1ba16)

**Comment by erfajo** [comment]
That sounds strange, however, could you give me a small sample of your rvt file? and the graph file?

If you upload some file, just add ".txt" to the file as extension, then I can remove that and the original extension should be left so I can see if it is zip, rvt or dyn files you hand over.

However, for formatting you can use a string value or my dropdown nodes. For finding the enaum names, lookup at the Revit API documentation --> https://www.revitapidocs.com/2023/d204d391-a453-2793-db9e-1e30716edbaf.htm
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/6dcf4fc2-615b-4e65-b7f6-50d3042c1241)
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/b715682c-82c8-41d9-9a57-d76d582c9949)

**Comment by jkoz73** [comment]
Revit: 23.1.20.70
Dynamo: 2.16.1.6510
Orchid: 2.16.4.5987

The issue
Same as OP.  In my case the schedule parameter is [also] a text type parameter applied to the "Sheets" category.  I get the same error on the "Schedule.Formatting" node stating "This ScheduleField cannot display minimum and maximum values." even while setting the 'calculate' input to "Standard" using the Orchid node "Schedule Field Display Types".

The result to the schedule field is mostly as specified in the graph except for the 'columnWidth' setting which defaults to 1" no matter the value input.

I have tracked the 'bug' down to happeneing between the 2.16.x.5812 and 2.16.x.5829 releases.  In 5812, the error doesn't occur but appears in the 5829 release.

<img width="1129" alt="2023-09-11 13_52_02-Autodesk Revit 2023 1 -  Project7 rvt - Sheet_ A0-0 0-B - COVER SHEET" src="https://github.com/erfajo/OrchidForDynamo/assets/89043492/7fb5cdde-a8a4-4e37-98a4-9d1c64470f9d">

<img width="568" alt="image" src="https://github.com/erfajo/OrchidForDynamo/assets/89043492/45103304-4b84-4994-88cb-36d2da58915f">

**Comment by erfajo** [comment]
could I have the graph file? you can add ".txt" as an extra extension, then you can upload.

**Comment by erfajo** [comment]
You are using so many packages, and I am only using my own and no others, so I can't say where things go wrong, but my best guess is that it is a graph problem, more precisely the computational speed in the graph. You are using some kind of ”await” mechanism in a way that makes no sense.

I will suggest that you try to freeze some parts of the graph, then run the graph. Unfreeze the next part and run… if that is possible with the nodes you are using.
Another way is that you add watch nodes checking that the inputs are what you expect.

Another very simple test/suggestion is to drag your ”Format the header” group towards the left and the bottom… It might sound silly but it is graphs we are building and the ”travel distance” matters in graphs. Not that it should do anything, and this is why we always need to understand what the implications of Directed Acyclic Graphs are. Meaning, you need to figure out a way to control the graph.

Nevertheless, I have added my test graph (also available in my samples), try to run that, and verify if that works.
[Scheduling_R23.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/12593787/Scheduling_R23.dyn.txt)

![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/834ff63e-84ba-4d01-bd0f-dfbfa84a936d)
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/33fbedd9-6f98-488e-851d-a26e624086ab)
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/2e85ef37-14df-4272-a867-3cbbbdd605b8)

**Comment by jkoz73** [comment]
Thank you for taking a look and your suggestions for troubleshooting.  I'll give them a try and report back.  Note that the graph worked fine prior to updating the Orchid (and other) packages so maybe it is something to do with one of them.

**Comment by erfajo** [comment]
That it has worked could very well be due to the computational speed... I optimize my code over and over, so it is being as fast as possible. So please check if my sample graph works, if it does, then figure how you can controll your graph.

Remember to remove the part with adding a shared parameter, you dont need that...
![Scheduling_R23](https://github.com/erfajo/OrchidForDynamo/assets/2844374/a3502e03-d658-43b9-9f00-0b43875dc7de)

**Comment by jkoz73** [comment]
OK.  So I've had some time to do some more troubleshooting.

I took the suggestions in your first response.  Same result as above.  So I created a simpler graph and ran it with the same result.  That graph is attached here.

[Schedule Formatting Test Smaller Graph.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/12610929/Schedule.Formatting.Test.Smaller.Graph.dyn.txt)

I downloaded the graph you provided above, removed the SP add portion and ran it.  The schedules were added but two nodes had warnings, inlcuding the Schedule.Formatting node in question.  I've grabbed screenshots and uploaded them for review.

![2023-09-14 09_22_05-Dynamo](https://github.com/erfajo/OrchidForDynamo/assets/89043492/382431d2-c50d-43d7-b378-bfab80dee28f)
![2023-09-14 09_22_25-Dynamo](https://github.com/erfajo/OrchidForDynamo/assets/89043492/992b7172-c627-4cf8-95c7-1052420db346)
![2023-09-14 09_22_53-Dynamo](https://github.com/erfajo/OrchidForDynamo/assets/89043492/3d13c4ef-5b79-4fd9-9ec5-f260a0a7cbe3)

I also took a look at some notifications that I had in Dynamo.  Shame on me for not looking at these sooner...  One has to do with the Orchid package. I uploaded a screenshot of it. Second one down.  Not sure if the first has anything to do with it but was still present after uninstalling the Orchid package (see comment on the install below, brought up in case it might mean something). 

![2023-09-14 09_18_57-Dynamo](https://github.com/erfajo/OrchidForDynamo/assets/89043492/be82cebb-976b-4e15-b3b1-f0126ffeca3d)

I also noticed something weird about the 2.16 Orchid installation in Programs and Features.  I've installed the 2.16 package (for Revit 2023) but the entry reports Orchid for Dynamo 2.18.1, Version=2.18.1.5987.  The Orchid folder is created in my Dynamo 2.16 package location so maybe it's just a clerical error?

![image](https://github.com/erfajo/OrchidForDynamo/assets/89043492/ce3d268f-e22e-4025-acef-724f49dd0a4b)

Last thing I'll write in this post is that I have disabled all my addins and removed all Dynamo packages except Orchid to try and isolate the issue.

**Comment by erfajo** [comment]
I found the error... apparently there has been a smaller change lately, this was easy to fix. However, there is also a potiental for making a better node, I will try to fix this later...
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/847c5d4d-6151-4b0b-829c-89ade3ee0406)

**Comment by erfajo** [comment]
as announced, is the node refactored along with fixing the error.
[Schedule.Formatting.Test.Smaller.Graph.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/12640628/Schedule.Formatting.Test.Smaller.Graph.dyn.txt)
![Schedule Formatting Test Smaller Graph](https://github.com/erfajo/OrchidForDynamo/assets/2844374/c0ec361a-aa2a-4241-8ef6-a6c3a784dba0)

**Comment by jkoz73** [comment]
Erik

Thank you so much!  This does the trick!

I appreciate you sticking through this with me and working it out.  Thank you also for making this wonderful package for Dynamno.
