### ISSUE TITLE
Partial nodes installed not entire package

### ISSUE THREAD

**Issue by Notte21** [erfajo/OrchidForDynamo#205]
Revit:2020
Dynamo: 2.3
Orchid: 212

### What did you do? 
I have been trying to install the orchid package as i have received a new desktop. I cannot get the package to install fully.
In the library browser it has Orchid broken into three categories- Orchid Core/ Orchid- Revit Material/ Orchid Revit Project.

![image](https://github.com/erfajo/OrchidForDynamo/assets/134810098/eba9e3aa-84ef-4e56-b55c-2e7672ca310d)

### What did you expect to see?
My script uses the node List. AnyTrue- when i go to manage pacages it notes this node is included in the additional files

### What did you see instead?
When i run the script it shows unresolved with question marks  and i cannot find the node via search.

I am not sure what to do and am fairly new to dynamo so perhaps i am missing something crucial however i had this working previously (Novemeber2022)

**Comment by Notte21** [comment]
![image](https://github.com/erfajo/OrchidForDynamo/assets/134810098/bc037a60-e076-4ccf-aa8f-ab649822028e)
This is what shows on the browser library

**Comment by erfajo** [comment]
I am afraid I can't reproduce your error!? Are you sure that Orchid is loaded properly?
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/1d3d82f7-4073-40f3-ba63-3b1328905462)

**Comment by Notte21** [comment]
@erfajo i followed the manual installation and dragged the files to where the other packages are saved. i have tried to do this over and over with the same result. I downloaded ran the exe and then copied over the files- should i run the exe in the folder itself?

**Comment by Notte21** [comment]
Does my version of dynamo matter 
![image](https://github.com/erfajo/OrchidForDynamo/assets/134810098/b3eca526-2ef9-485d-8e8b-81417e8980c5)

**Comment by erfajo** [comment]
Try to see the error page, i am sure your problem is Windows blocking files downloaded from the internet. If you use 7zip the application takes care of that. Built-in zip in Windows does not
