### ISSUE TITLE
Orchid for Revit 2018

### ISSUE THREAD

**Issue by MtbGot** [erfajo/OrchidForDynamo#206]
I need to install Orchid on Dynamo 2.03 for Revit 2018. I installed version 200 but I can't see the nodes on Dynamo. 

I understand it is no longer supported, but please keep the exe on the repository.

I don't know who else I can ask for the files.

THANK YOU

**Comment by erfajo** [comment]
As written on the intropage is as low as Orchid 200 avalible, however not maintained, and only as a zipped version you need to add by yourself.
https://github.com/erfajo/OrchidForDynamo/tree/master/Zipped
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/8c10f6b1-b45a-4364-93b6-489272502c2b)

**Comment by MtbGot** [comment]
Thank you very much. I didn't enter there as it said it was for experienced users, and I am just starting :)
I am amazed at all the nodes you have, congratulations!

I do have some problems due to incompatible versions. Your pack is the first one I installed; it should be an add-on or a plugin (I have several). I will see how to fix it. 

Thank you, again!

**Comment by erfajo** [comment]
" incompatible versions"?
I don’t understand!?

It is normally not the outdated version that is being installed, especially by someone new to the community. And as I remember it, Autodesk does neither support more than 5 versions back, and only four versions is maintained... but I might be wrong.
When I am building functions for Dynamo and Revit I go to the edge, meaning, that a lot has been deprecated by Autodesk if it is more than four years old. 

Just maintaining the last four versions is at the moment rather cumbersome, while the entire unit handling inside Revit has changed for programmers. The users don’t see it, but it is a huge thing. Likewise, all nearby unit handling is now changed to what is called ForgeIDs, and as I remember it, when we changed from Revit 2018 to Revit 2019 Materials went through a large change.

So it might be a better idea to use at least a Revit/Dynamo combination that is among the last four versions, just to be ahead of whatever is taking place. Revit 2018 er really outdated.

**Comment by erfajo** [comment]
Is the Revit installation upgraded with the latest version of 2018?
That should be Revit 2018 upgrade 3.3 (18.3.3.1)? ...and unfortunately, it looks like the last version I build upon was 18.3.2.7

Since I don’t have Revit 2018 anymore, I simply can't do anything. However, it is most important that it is at least 18.3, since major changes occur at that point as I remember it.

**Comment by MtbGot** [comment]
Thank you very much, you already did more than I expected! 
I need to insist on upgrading computers to install the latest versions of Revit.
