### ISSUE TITLE
Dynamo.Exceptions.LibraryLoadFailed

### ISSUE THREAD

**Issue by Daralice** [erfajo/OrchidForDynamo#208]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2022.1
Dynamo: 2.12.0.5650
Orchid: 212.4.0.5889

### The issue
Hey,
I'm quite new to Dynamo and currently work on some scripts where I use the Orchid Package.
Since Friday I get troubles as my Dynamo states that it can't find a file or assembly...

Here is the info I got (it's partially in German):

![image](https://github.com/erfajo/OrchidForDynamo/assets/118201315/7d9226cf-cddf-4a5f-b056-075a332d748c)

I tried this proposed solution, but it didn't work:
https://forum.dynamobim.com/t/dynamo-packages-not-loading-2-12/79904

deleting orchid and reinstalling it didn't help either.

I got a seemingly related problem with "Crumple", but I wasn't able to figure out why it's only these two packages, so I thought I might just ask.

Thank you!

**Comment by erfajo** [comment]
Hopefully, do you work on some graphs, since you ask for usage of my nodes. To do scripting with my nodes are possible, but that is nearly never the case. Most cases (as 99%) would be using nodes in a graph.
However, I am aware that by far too many describe what they do as "scripting"... but that is a slang language that should never be used.

next...
How did you install it? if you downloaded the package as zipped version, then you need to unblock the assemblies. If you used the installer that should be fixed, however, try to see if the assemblies are blocked.
https://github.com/erfajo/OrchidForDynamo/blob/master/Error.md

**Comment by Daralice** [comment]
Hm, okay, interesting! I did use the installer yesterday, as I deinstalled and reinstalled Orchid. I'll try to find and unblock the assemblies :D

About the language: I'm happy to improve my professional english, although most of the time I'm simply happy that people know what I mean, when trying to express myself in a foreign language :D But I'll keep in mind that I work on graphs in dynamo ^^

**Comment by erfajo** [comment]
if you used the installer, then I suppose that the error could be something else.

As I also write on the error page, some of the other packages you have loaded might include assembly files from dynamo, and that is a no-go, but it does happen that newbie codes include those assembly files. So try to unload all other packages by moving the packages to your desktop, then open revit/dynamo again, and see if Orchid works… if so, then add one package at the time to see which package gives you the error. I suppose that it is not any of the larger packages but a small relatively new package.

By the way, my Orchid package is always built upon the latest Revit/Dynamo Build, this would be Revit 2022.1.4 at the moment.

**Comment by Daralice** [comment]
Thank you!

I'l try my best to solve this. As an Interior Architecture student Dynamo and IT structures are sometimes overwhelming for me.

**Comment by sayurlarismanis** [comment]
Hi, I have the similar problem.. How do you install/update the IfcExporter properly?

**Comment by sayurlarismanis** [comment]
Because it stated over there and just like mines that the"IfcExportUIOverride.addin cannot be found, the system can't find the file."

I read from your closed issues from here: https://github.com/erfajo/OrchidForDynamo/issues/119
that by installing the ifcexporter would help. 
FYI I also updated my Revit to 2022.1.4 and it still didn't work..

**Comment by erfajo** [comment]
as I wrote, that is another problem... this is not alike this problem at all...

**Comment by sayurlarismanis** [comment]
Alright, my apologies I will create a new thread then

**Comment by erfajo** [comment]
sorry... it is me... I didnt see that it was the IFC assembly that was mentioned here as well... so your are right, is might be the same problem :-)

**Comment by erfajo** [comment]
So both @Daralice and @sayurlarismanis 
did you install the IFC exporter before installing Orchid? This is a requirement!!!

**Comment by sayurlarismanis** [comment]
Not yet, I'm not quiet familiar how one can install the IFC exporter properly..

I know you referred to this link: https://github.com/Autodesk/revit-ifc
but i'm not sure which one to download

**Comment by erfajo** [comment]
as i is for Orchid, take the version that siuts your Revit version...
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/919e6820-f356-4fdb-978f-f6e507a304bc)

**Comment by sayurlarismanis** [comment]
![image](https://github.com/erfajo/OrchidForDynamo/assets/136445758/c201e42a-b6b1-4cba-8c77-5c4b279bf094)
I installed the latest IFC version.. but it doesnt change anything.

**Comment by erfajo** [comment]
that was strange... could it be the case that the IFC installer is localized? and that this means that the "IFCExporterUIOverride.dll" might have an issue!? I know that ForgeIDs are localized and that means that I only build for the English version and not any other localized languages... but if the sam is the case with Ifc I dont know.

One option is still that something else is shipped with assembly files that not should be the case, this can be checked by removing other packages and then test if Orchid works... and as written earliere, then move one package back at the time to see if it is loading another package that gives the error... and I am sure that if so, then will you see that the package has som assemblies in the "bin" folder it should not have had.

and for your last question, not there should not be anything concerning paths, but try to open the exporter from inside Revit and see if that works... then should this also work from dynamo.

**Comment by erfajo** [comment]
ahhh... so first try to get the IFC exporter to work, and then progress to dynamo after that...

**Comment by Daralice** [comment]
We solved the issue, thanks for your help! 😄 
We deinstalled and reinstalled IFCforRevit2022. It's weird because it was the same version of the IFCforRevit but now it works. 😄

**Comment by erfajo** [comment]
Thanks for reporting :-)
...however, I will wait to close the issue until @sayurlarismanis has answered as well.

**Comment by sayurlarismanis** [comment]
Right as it turns out, uninstalling the IFC was necessary before reinstalling the new version..
I wasn't aware about that. 😄

**Comment by erfajo** [comment]
It is good that the issue got solved :-)
