### ISSUE TITLE
Nodes from older version of Orchid (v212.3.0.8342)

### ISSUE THREAD

**Issue by sayurlarismanis** [erfajo/OrchidForDynamo#209]
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 2022.1.4
Dynamo: 2.12.0.5650
Orchid: 212.4.0.5889

Hi again 😆 

So my graph still doesnt seem to be working, and apparently some of my nodes are currently from an older version of Orchid (v212.3.0.8342)
![image](https://github.com/erfajo/OrchidForDynamo/assets/136445758/ea14f0b6-315a-497b-a856-11abcf3f084b)

![Test_Parameter Formeln hinzufügen_2023-06-16_03-45-53](https://github.com/erfajo/OrchidForDynamo/assets/136445758/a267b42b-d20f-4a6c-a533-b8676d427438)

would you know how to resolve this issue? should i remake a new graph or install the older version of Orchid?

Best,
Larissa

**Comment by erfajo** [comment]
well, you get a null value from the very first nodes that are OOTB nodes... this means that nothing works at all.

You are welcome to upload your graph file (.dyn), you can do that by adding an extra extension as ".txt", then you are allowed to upload the file. hopefully, it will be multilanguage so I get the nodes in English.

...and just for the record, you have had other graphs working before you did this graph... and you can get some of the beginner's graphs shipped with dynamo to work!?

**Comment by sayurlarismanis** [comment]
I tried running a simple graph and it seems to be working..

![Dynamo Test_2023-06-20_09-38-37](https://github.com/erfajo/OrchidForDynamo/assets/136445758/da1dc83e-1e00-4b93-b64c-ef16f6b448cb)

**Comment by erfajo** [comment]
aha... you miss the "star"
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/077d7512-e4fa-4a16-9065-b228d9c0368b)
