### ISSUE TITLE
Selection.ElementByCategory not working with Subcategories

### ISSUE THREAD

**Issue by Schindi11** [erfajo/OrchidForDynamo#21]
Revit: 2017.2 & 2019.0
Dynamo: 2.0.0.4654
Orchid: 201.3.4.6839

Hello erfajo, I am facing a problem with the Node "Selection.ElementyByCategory". The node works fine if I try to get elements by their Main Category e.g. "Generic Models". My issue is that I need to select the Elements by their Subcategory e.g. "Generic Models - Test 1". 
The conversation to this topic can also be found on DynamoBim forum on the following Link:
https://forum.dynamobim.com/t/selection-elementbycategory-with-subcategories-not-working/31367?u=gerhard.schindler

Thanks in advance

**Comment by erfajo** [comment]
Thanks for including your Orchid version, this helps me a lot!
You have a old version, in version 132.3.8 was nodes for subcategories updated. The current version is 132.3.11

Please update...
If you in the feature want to be sure you have the latest version then include a "update" node in your graphs!
https://erfajo.blogspot.com/2019/01/orchid-new-nodes.html

**Comment by erfajo** [comment]
I am not sure what you are doing. I think you are misunderstanding something with forms you make inside a family...

[home.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/2832967/home.dyn.txt) (remove .txt)
![capture](https://user-images.githubusercontent.com/2844374/52288582-ca5fe600-296c-11e9-9854-db46bbc38de9.png)

**Comment by Schindi11** [comment]
Hello,
yeah I know it was all a bit messy and I think you missunderstood me somehow since the beginning. I guess my explanaitons are not well enough :)
Anyway thanks to your help i managed to find that one node that fixes my Problem (trid to find a solution for hours already)
Its the Collector.ElementsOfTypeInDocument - it gives me all the Subcategories from the Family Files even though they are not assigned - because from the beginning I was looking to find a way to find Families with unpurged Subcategories (we have something like 50 in our Family Templates)
