### ISSUE TITLE
Revit 2022, Dynamo 2.10xxx, Orchid???

### ISSUE THREAD

**Issue by mm-gjortzandersen** [erfajo/OrchidForDynamo#210]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2022
Dynamo: 2.10xxx
Orchid: ?

### The issue
I cannot find a version of Orchid that would work for my Revit+Dynamo. Everything works perfectly fine with Revit2021, Dynamo 2.6 and Orchid 2.6, but I cannot make it work with any of Orchid versions in Revit 2021. What could be the problem?

**Comment by erfajo** [comment]
I dont understand!?

if your Revit version is 2022, then must the orchid package be 212. If you try to use Orchid 206 it will fail. However, if you use Revit 2021, then you must use Orchid 206. My package hase a specific version for each version of Revit/Dynamo!
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/fd7fb1fa-43c6-4b70-bf9f-372523fb1d86)

**Comment by mm-gjortzandersen** [comment]
But the Orchid 212 doesn't work and I think it may be because of the Dynamo version which is 2.10 instead of 2.12.

And to make sure it's not a problem with how I install it, I checked with Revit 2021/Dynamo 2.6 and Orchid for this version worked perfectly well.

**Comment by erfajo** [comment]
If you can't load it, then I am sure you have one of the problems mentioned in the error page... but I can write you at gjortzandersen.dk if you need further help, it sounds like a beginners issue :-)

**Comment by mm-gjortzandersen** [comment]
Yes, I'm a begginer ;) if you wouldn't mind I'd greatly appreciate it
