### ISSUE TITLE
IFC.AllSetting node error

### ISSUE THREAD

**Issue by DDO-dp83** [erfajo/OrchidForDynamo#211]
### Operating system
(Windows 10 Pro)

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2022
Dynamo: 2.12.1.8246
Orchid: 212.3.0.8367

### What did you do? 
Place the IFC.AllSetting node

### What did you expect to see?
All the IFC export setup options

### What did you see instead?
Warning: IFC.AllSetting operation failed. 
Method not found: 'Void BIM.IFC.Export.UI.IFCExportConfigurationsMap.Add(BIM.IFC.Export.UI.IFCExportConfiguration)'.

![IFC AllSetting_Error](https://github.com/erfajo/OrchidForDynamo/assets/138563460/96137f1e-20b9-49f5-ad5b-fef311044593)

**Comment by erfajo** [comment]
This is an error indicating that you have not installed the IFC exporter but are using the built-in ifc exporter that is shipped with Revit. I write in the readme (the ifc readme node), that the IFC exporter is required.

Find you version here
https://github.com/Autodesk/revit-ifc/releases

**Comment by DDO-dp83** [comment]
First of all, thanks for the quick response! I checked and i've got the IFC.for.Revit.2022.6.2.0 installed wich to my knowledge is the latest version. Is there somthing else rong then or is it the wrong version?
 
![image](https://github.com/erfajo/OrchidForDynamo/assets/138563460/f81f3d86-915f-4eef-9a4a-9d9acbc23048)

**Comment by erfajo** [comment]
that is the same version I have, and have coded my nodes for.
can you make a small sample model and your graph, and zip it? when you upload, then rename by adding ".txt" to the filename. Then I will try to see what could be the problem.

**Comment by DDO-dp83** [comment]
Like this? If its not wright and you meen somthing else let me know. 

[IFC.AllSetting_Error.zip.txt](https://github.com/erfajo/OrchidForDynamo/files/12000152/IFC.AllSetting_Error.zip.txt)

**Comment by erfajo** [comment]
I cant download anything... please test if you are able to download whatever you upload first...
I presume that the file is around 5-10 MB, not more than that... if the file is very large you are not able to upload, but that would neither be a small sample, so I dont presume that is the problem.

**Comment by DDO-dp83** [comment]
Does it work now? 

[IFC.AllSetting_Error.zip](https://github.com/erfajo/OrchidForDynamo/files/12000639/IFC.AllSetting_Error.zip)

**Comment by erfajo** [comment]
hmmm... this is what I get
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/d17543c5-17f5-477d-a310-a13df01062bd)

Please try to download latest build at github and reinstall...

**Comment by DDO-dp83** [comment]
I reinstalled the OrchidForDynamo_212.exe Build and the error's are gone but some of the nodes now get a null value. Any idea what could have gone wrong?

![image](https://github.com/erfajo/OrchidForDynamo/assets/138563460/953359a9-6674-4e8c-9649-58f0758afcdd)

**Comment by erfajo** [comment]
I have noticed the same, and it seems to be happening if a graph is not yet saved!? I think it is a dynamo problem since I have seen others having the same issue...

on top of that, I am loading the IFC exporter in the background, and this gives also an issue under some conditions I can't figure...
