### ISSUE TITLE
make a design option primary 

### ISSUE THREAD

**Issue by dynolivar** [erfajo/OrchidForDynamo#213]
Im using the orchid nodes, and im using also a python script to set a design option to primary. 
My issue with all the information can be found here: https://forum.dynamobim.com/t/make-a-design-option-primary/92485
software version: 
Revit: 2021.1.5
Dynamo Core: 2.6.1.8786
Dynamo Revit 2.6.1.8850
Orchid: 206.6.0.5842

### The issue
see this link: https://forum.dynamobim.com/t/make-a-design-option-primary/92485

**Comment by erfajo** [comment]
I don't participate in the dynamobim forum...

**Comment by dynolivar** [comment]
Hi @erfajo , 

I understand. I also solved some issue's within the custom python node. Im trying to write a graph to set a non primary design option to primary. But i reached a dead end... Im using the orchid nodes for input. Could you please help me out? 

Could you please help me out? 

**graph with error:** 
![image](https://github.com/erfajo/OrchidForDynamo/assets/88403473/1537b443-5bf0-47e3-b3ae-b6f55f14f45d)

**file:** 
[make designoption primary - dynamo graph (2023).zip](https://github.com/erfajo/OrchidForDynamo/files/12334980/make.designoption.primary.-.dynamo.graph.2023.zip)

**Python script used in the python script node:** 
`# Load required modules
import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import FilteredElementCollector, DesignOption, Document

# Function to set the primary design option
def set_primary_design_option(option_set, option):
    try:
        option_set.SetPrimary(option)
        return True
    except:
        return False

# Inputs
doc = IN[0]  # Use for example the current document node from archilab
option_name = IN[1] # (use node element.name)
option_set_name = IN[2] # (use node element.name)

# Find the DesignOptionSet by name 
option_sets = FilteredElementCollector(doc).OfClass(DesignOption).ToElements()
option_set = None

for opt_set in option_sets:
    if opt_set.Name == option_set_name:
        option_set = opt_set
        break

# Check if the option_set was found
if option_set is None:
    raise Exception("Design Option Set with the provided name not found.")

# Find the DesignOption by name
options = option_set.GetDependentElements()

option = None

for opt in options:
    opt_elem = doc.GetElement(opt)
    if opt_elem.Name == option_name:
        option = opt_elem
        break

# Check if the option was found
if option is None:
    raise Exception("Design Option with the provided name not found.")

# Set the primary design option
result = set_primary_design_option(option_set, option)

# Output
OUT = result
`

**Comment by erfajo** [comment]
I am not aware if there exists any option to set DesignOption as primary, and I cant find any documentation that something like this exists.

I can see that you have tried to write your own method
```
# Function to set the primary design option
def set_primary_design_option(option_set, option):
    try:
        option_set.SetPrimary(option)
        return True
    except:
        return False
```
 but I dont know ehere you have found "SetPrimary(option)", I cant find it in the documentation for the Revit api.

**Comment by dynolivar** [comment]
that makes sense now.. I got this recommended from a colleague. thank you for your help though. It's a pity that the revit api documentation does not offer a method to set a option to primary.

**Comment by erfajo** [comment]
I agree, there are so many things that still are hidden for users/codes by Autodesk... this is just one of the things :-S
