### ISSUE TITLE
FamilyDocument.SetParameterValueByName doesnt work with yes/no parameters

### ISSUE THREAD

**Issue by justloosit** [erfajo/OrchidForDynamo#214]
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 2024
Dynamo: 2.18

### What did you do? 
I wanted to change yes/no family parameters with the FamilyDocument.SetParameterValueByName 

### What did you expect to see?
I tryed 0 and 1 from code blocks, integer slider, string to integer, true/false but the node won't work with yes/no parameters

### What did you see instead?
![image](https://github.com/erfajo/OrchidForDynamo/assets/141972763/a8ae7e49-5a77-451e-8575-f7ba51515841)

"Input value for this parameter needs to be of type integer" even tho they clearly are intger

**Comment by erfajo** [comment]
First, please update your Revit to 24.1 since my 218 is written for that version.
Next you should try to ask the Dynamo team why their node does not work, it is not my node!?
![home](https://github.com/erfajo/OrchidForDynamo/assets/2844374/4f70db17-69ca-4ef2-aca5-1b3b5724edc2)
