### ISSUE TITLE
Load families from file path, expected output Revit.Application.FamilyDocument instead of Revit.Application.Document

### ISSUE THREAD

**Issue by BIMnerd** [erfajo/OrchidForDynamo#215]
### Revit, Dynamo and Orchid version

Revit: 2022.1
Dynamo: 2.12.1.11123
Orchid: 212.4.0.5889

### The issue
Hello,

I am trying to set parameter formulas within my families from documents. The input that i need is Revit.Application.FamilyDocument for my set formula nodes, however when i tried to load families from document with your package i get Revit.Application.Document as an output. This is what i have so far:

![Parameter ID Daten ausfüllen_2023-08-18_03-27-35 (2)](https://github.com/erfajo/OrchidForDynamo/assets/124705501/24a07aed-c52a-4fa7-821d-f6ae36813e71)
![Screenshot 2023-08-18 152713](https://github.com/erfajo/OrchidForDynamo/assets/124705501/0d06526f-19a2-4113-8837-4f06d9c64b29)

Is there any way around to solve this? Thank you in advance :)

**Comment by erfajo** [comment]
this sounds strange... I can see that you open rfa files, and then pr definition the files are familydocuments. I will try to do the same and will return to you.

**Comment by BIMnerd** [comment]
So i updated the orchid version.. there's no more errors anymore.. but now it's just not doing anything
![1](https://github.com/erfajo/OrchidForDynamo/assets/124705501/51a9f1da-4942-4e1d-9046-d705842e702c)

![image](https://github.com/erfajo/OrchidForDynamo/assets/124705501/a34ba08b-86d5-4a1d-a71e-0d81056079b9)
![image](https://github.com/erfajo/OrchidForDynamo/assets/124705501/2cd6f7df-a739-44c8-b210-a5518348fe17)

is there anything else that i have to update? i'm not sure if this python has something to do with the graphs..

**Comment by erfajo** [comment]
I do not understand how Python should be involved, I have nothing coded in Python so it cant be anything in combination with mine... and from what you show there is not any Python related nodes in that graph. Could you zip two families and the graph and uplod it? add the extension ".txt" to the zipfile so it can be uploaded.

**Comment by BIMnerd** [comment]
Sorry i figured out the previous problem.. there was a mistake with the string input for the *.rfa 😅 

at some point it worked once, but when i tried it again it gave me this:
![3](https://github.com/erfajo/OrchidForDynamo/assets/124705501/f4511191-4600-4574-a073-5d4f24a3a49c)
![image](https://github.com/erfajo/OrchidForDynamo/assets/124705501/44b67949-ca3e-459d-9e78-e4d90c293f9a)

Sometimes it also tells me that the string input is invalid.. although it is already a string and the parameter type is also text.

**Comment by erfajo** [comment]
test it by adding some "watch" nodes to output ports, and see if there is valid inputs for dte next node... and create that zip file I asked for.

**Comment by BIMnerd** [comment]
[Formula Set.txt.zip](https://github.com/erfajo/OrchidForDynamo/files/12408958/Formula.Set.txt.zip)

i uploaded a generic family with the graph.. does the zip file work with you? i tried adding a .txt but am not sure if it was the proper way

**Comment by erfajo** [comment]
When I opened the graph I saw immediately the overall problem. It is a missing understanding issue not knowing what the huge difference between a graph and a script is… You have no idea how fast things are computed in a graph since it is functions connected in a graph, and data will travel the shortest (fastest) way.
In your case is the family long closed before you try to set the formula…

The next error is that you are transferring values into a formula, and to do this you must indicate that it is a string value by adding quote marks!

I have highlighted your error with red groups

[Parameter ID Daten ausfüllen.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/12415873/Parameter.ID.Daten.ausfullen.dyn.txt) (remove .txt)
![Parameter ID Daten ausfüllen](https://github.com/erfajo/OrchidForDynamo/assets/2844374/00e57565-4553-4d7b-b771-5c8dfb44c414)

**Comment by BIMnerd** [comment]
What do you mean with misunderstanding script and graph? did I mention script somewhere? or is it something with my .dyn?

But thank you for the remarks! that is good to know for future works.. However, it's not really filling all the formula into my families.. it's filling one parameter for one family, i tried using the cartesian product within the node settings, but it does it for my parameter name and its values- and not for the families.

Also, every time i run the second time, it gives me this report.. I had to close and reopen the graph again to have it run properly, can I also do something else to avoid this?
![image](https://github.com/erfajo/OrchidForDynamo/assets/124705501/a057eb35-fd47-499e-9ee7-eb3c7565b409)

**Comment by BIMnerd** [comment]
P.S it works well for just single family

**Comment by erfajo** [comment]
That error message indicates that the family document is closed before you try to set the formula... freeze the "close.document" and try again.

When you work with dynamo you work with graphs, and this involves the "closing issue", this is something you always need to take into consideration when you build graphs. 

My await node should be able to handle this issue in most cases, but not all. It is, however, the only way I know I can address the closing issue if I don't freeze the subsequent nodes, or split into several graphs.

**Comment by BIMnerd** [comment]
Okay I see.. and how can we manage to have the all the formula set in multiple families? Because as I mentioned before, it sets one formula for one family

**Comment by BIMnerd** [comment]
yes I used the graphs as you left it.. the problem is that the graph is now setting Parameter 1 for Family 1, Parameter 2 for Family 2, etc.. rather than setting all Parameters for all families..

**Comment by erfajo** [comment]
yes... this is how it is done. flatten the output from "setformula" node, and take last item... use that for the "waitfor" input. this should slow things down

**Comment by BIMnerd** [comment]
![Parameter ID Daten ausfüllen_2023-08-24_10-51-06](https://github.com/erfajo/OrchidForDynamo/assets/124705501/f1dbc841-d762-4ae1-bf7e-55120088913b)
i'm not fully following the thinking process.. is this what you mean?

**Comment by erfajo** [comment]
that is correct... but why do you only have four values in the setformula node, if you have +2 documents... you need to adjust list levels so it works with all open documents...

**Comment by BIMnerd** [comment]
So i have numerous families, and i want to set 4 parameter formulas..

what is doing right now:
Set formula 1 - family 1
Set formula 2 - family 2
Set formula 3 - family 3
Set formula 4 - family 4
nothing - family 5 till the last

**Comment by erfajo** [comment]
You need to understand how list level work, try to see this on the dynamobim site under help... I can't exactly remember where it is described how list level is working, try to find it yourself.

**Comment by BIMnerd** [comment]
But thank you nevertheless.. you helped me a step further with my graph.

Just a suggestion for your own experiment for the sake of your development: try to set a list of formulas for multiple families that are opened from directory content, and see how the result goes. If all formulas are set in all of the families, then the mistake must be at my end.

**Comment by erfajo** [comment]
If you dont find list level useful, then do what you feel is better. Cartesian product could also be a solution, there are several ways to solve the issue.
The way the node is designed for a current family, like most nodes are. The dynamo team also design nodes for the current project file.
So when you start opening several families this needs to be reflected in how you are using either list level or other possible ways to solve the issue.
