### ISSUE TITLE
Upgrading package causes Document.LoadFamily to change functionality

### ISSUE THREAD

**Issue by acco-jpitts** [erfajo/OrchidForDynamo#221]
### Revit, Dynamo and Orchid version

Revit: Revit 2020 - Revit 2024
Dynamo: 2.3 - 2.19

Old Orchid: 210.1.0.7927
![old node](https://github.com/erfajo/OrchidForDynamo/assets/104219512/2cb1efde-ad1b-46eb-a5eb-633598b8e2f1)

New Orchid: *.5842 - *.6080
![new node](https://github.com/erfajo/OrchidForDynamo/assets/104219512/2ab0a0c7-a792-422e-9ebf-551a8605ff2b)

### The issue
We have been using Document.LoadFamily node from an older Orchid package with Revit 2020-Revit 2023 without issue, and after updating packages and graphs for Revit 2024 this node is completely different. 

After updating package and opening the same graph, instead of a single input for a RFA file path, there is now a second Document input which is connected to our file path. 

The output is changed from Family to Document.

Is there a 1:1 replacement for the only Document.LoadFamily node? Or will we need to retrieve the family using some other method after loading?

**Comment by erfajo** [comment]
It look like you want to use my node "Family.Load" instead...
![File+Fam-Load_R23](https://github.com/erfajo/OrchidForDynamo/assets/2844374/6088fe04-6212-4888-9b02-56b079b02be5)
