### ISSUE TITLE
How can I get the full package installer for Dynamo 2.17 (R24)? I am after "FamilyType.ByCategory" node. Any way get the installer, please?

### ISSUE THREAD

**Issue by ShinK360** [erfajo/OrchidForDynamo#222]
### How to get help...
I will try to assist you as best as possible. One way to do that is by answering your questions. But to get the right answer, you’ll first have to ask your question in the right way. Although I will try my best, there are things you can do to improve your chances of getting good and quick answers. Below you will find some suggestions on how to achieve that. Do not think of these suggestions as rules and especially do not take them as a guarantee of getting an answer.

1. Choose a descriptive title for your post
2. Be succinct but clear in your wording
3. Attach minimal versions of all the relevant files
4. Include a detailed image or sketch if it makes sense
5. Include links to online resources if possible
6. Create new topics rather than continuing old ones
7. This is not a ‘do my work for me’ assistance
8. Search is your friend, try first to see if your issue is handled in the samples
9. If your problem has been solved, mark the post as solved.

For further information, and an in-depth description of the points, please follow these guidelines
https://forum.dynamobim.com/t/how-to-get-help-on-the-dynamo-forums/4677

_Please delete this line and the above, and start describing your issue._

### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: x.x.x.x
Dynamo: x.x.x.x
Orchid: x.x.x.x

### The issue

I am using Revit 2024 and found that "FamilyType.ByCategory" node is not available with 0.0.3 package. I jumped to GitHub to download the installer "OrchidForDynamo.exe" for a full package but it said the pack is not available. It says "(Sorry about that, but we can’t show files that are this big right now.)".

Can you please give me a way to get installer?

Thank you.

**Comment by ShinK360** [comment]
I managed to got it sorted. Thank you.

**Comment by erfajo** [comment]
My new installer comes with all versions included since the installer is so compact that it in the long run will save the users from downloading all kinds of versions. Besides is it a challenge for some users to know the difference between the individual versions, so they are more into which version they use when they look at the given Revit version.
...and fever downloads/smaller number of files to maintain is also less usage of energy consumption = better for the environment :-)
