### ISSUE TITLE
Node when clicked does not show or produce anything

### ISSUE THREAD

**Issue by LordManyakis** [erfajo/OrchidForDynamo#228]
### Revit, Dynamo and Orchid version
Revit: 21.0.0.383
Dynamo: 2.5.07586
Orchid: 2.6.7.6119

I am using the Zip Folder installation method because when I tried to install Orchid using the EXE method it does not shop up on my Installed packages. As shown in the image I am using dynamo graph from my online class, they are using the orchid 230 ( its an old recording ), Im not sure which Orchid to download since my Dynamo version does not fall on any version based on the guide its either dynamo 2.3 or 2.6 but i am on 2.5 so I chose the 2.6 Instead. My issue is whenever i click on the Sheet Views or any node under the Orchid-Revit Project it does not show or prompt anything. I hope you can help me with this.

Btw, i cant use a higher version of revit, our company uses this version. thank you

![image](https://github.com/erfajo/OrchidForDynamo/assets/145666249/dfa23ba8-8b7e-4604-bca2-061fcf6bdc9e)

**Comment by erfajo** [comment]
I am afraid that you need to update your Revit version. The current version for Revit 2021 is Revit 2021.1.9 and Dynamo 2.6.2
I don't support a lower version than that.
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/a99cafa5-890c-43e1-8c55-a593ca36f8db)
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/99e1d563-e295-473a-b840-c9b745b06f02)

**Comment by LordManyakis** [comment]
Thank you for this!
