### ISSUE TITLE
Nodes are showing error even when loading the new and updated Orchid file from Github

### ISSUE THREAD

**Issue by sagal123** [erfajo/OrchidForDynamo#23]
Hi Erik,

Thank you for support me with my last issue on Dynamobim Forum however I haven't had the chance to run the graph the nodes are showing error I am not what I am doing wrong it also says its clashing with my plugin I have even when I have deleted and uninstalled it I shall show you all the errors that's how please need your help with this one kinds regards sagal

**Comment by sagalrooble** [comment]
![githib](https://user-images.githubusercontent.com/40343478/52340361-7f46e100-2a07-11e9-8945-1c3d5b932103.JPG)

**Comment by sagalrooble** [comment]
Those were the errors i have received Erik

**Comment by erfajo** [comment]
the information you provided so far doesn't say anything.
you need to unfold the yellow note on-top of the node... 

try also to verify your paths... -> Settings -> Manage Node and Package Paths

**Comment by sagalrooble** [comment]
![dynacore isse](https://user-images.githubusercontent.com/40343478/52354748-e6c15880-2a28-11e9-806e-512b363853ae.JPG)

**Comment by sagalrooble** [comment]
This is the errors its coming up with i have done into the location of the file do you think i need to delete the DynamoCore.dll

**Comment by erfajo** [comment]
now I see...
I need some further description. Is this a graph made in a previous (older) version of Dynamo? (e.g. Dynamo 2.0.0) If so, then you have hit an error in Dynamo.
If this is a new graph (recently) then it must be the installation, in that case, erase the Orchid folder in your package folder and reinstall.
If it is the first case, then is there a solution says the Dynamo team, but I have no idea when they release it, my best guess is several months.

You can follow the error here...
https://github.com/DynamoDS/Dynamo/issues/9076#issuecomment-459796339
https://github.com/DynamoDS/Dynamo/pull/9306

**Comment by sagalrooble** [comment]
Hi Erik, 

The migration of nodes did you mean this ?
![migration](https://user-images.githubusercontent.com/40343478/52574421-2961a700-2e14-11e9-9364-d9e583d9b723.JPG)

just literally replacing the error nodes with the same node in the package.

**Comment by sagal123** [comment]
Hi Erik, 

The migration of nodes did you mean this ?

**Comment by erfajo** [comment]
Yes, this is your problem... but try to see this
https://forum.dynamobim.com/t/dynamocore/31912/13

**Comment by erfajo** [comment]
Yes this is the problem with the failing migration. And now where dynamo 2.1 is released is the problem still present. This is a huge problem for many users, but hopefully will the dynamo team at some point solve it.
