### ISSUE TITLE
0x00000007 Document.BackgroundOpen and  FamilyDocument.Parameters

### ISSUE THREAD

**Issue by L-Vaselaar** [erfajo/OrchidForDynamo#230]
![dynamoError](https://github.com/erfajo/OrchidForDynamo/assets/156954737/358a6e00-3d19-459e-8a67-ea134e020aa7)
### Operating system
 Windows 10

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2024.2
Dynamo: 2.19.3
Orchid: 2.19.0.6129

### What did you do? 
place the two nodes in a blank file and graph. I was having the issue in a script I am trying to write and I wanted to see if it worked with a blank slate. 

### What did you expect to see?
I was trying to see if it would recreate the error. it did. 
![dynamoError](https://github.com/erfajo/OrchidForDynamo/assets/156954737/077cedff-8241-41ea-a8dc-9ea4847a5910)
![image](https://github.com/erfajo/OrchidForDynamo/assets/156954737/e9d70cda-4a6f-45e5-8163-e0d35eec6e81)

### What did you see instead?
was given the 0x00000007 message on both nodes when I tried to run script

**Comment by erfajo** [comment]
It is so strange... I have had quite some reports concerning 0x00000007
Could you reveal just a bit more, do you have an error description you can copy from Dynamo? and do you use Revit in English? (not in any other language)

**Comment by velichkoleg** [comment]
> Это так странно... У меня было довольно много сообщений о 0x00000007. Не могли бы вы рассказать немного больше, есть ли у вас описание ошибки, которое вы можете скопировать из Dynamo? а вы используете Revit на английском языке? (ни на каком другом языке) ![изображение](https://private-user-images.githubusercontent.com/2844374/297735845-0bf6a488-ab54-4e90-8bef-a4aefe9773ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzEyNzQsIm5iZiI6MTcwNTY3MDk3NCwicGF0aCI6Ii8yODQ0Mzc0LzI5NzczNTg0NS0wYmY2YTQ4OC1hYjU0LTRlOTAtOGJlZi1hNGFlZmU5NzczYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMTMyOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg0MTY3ZmE3ZGI4MzNjYWU4OTFkMzIxMjM0MmU5YTA5MTIyMjEyYWZjNzY1Y2NlMDkxZGY4YTM2NTY4YTY3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h5M9hqIhKoCqrrYKQoyAVQaDXKAXVmUuFvm7adFExpA)

Hello. I have the same problem. Here is the description
![image](https://github.com/erfajo/OrchidForDynamo/assets/157128515/bbeb12ca-0410-44e9-8de8-38fb7ba787e1)

**Comment by velichkoleg** [comment]
![image](https://github.com/erfajo/OrchidForDynamo/assets/157128515/52250266-bb8d-4579-8238-ee06d881ee3b)

**Comment by erfajo** [comment]
I have now tried to add some checks for language... I have uploaded a beta build, can you test that?
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/ad1403c7-da4f-4412-9e13-697e7a6c37d5)

**Comment by velichkoleg** [comment]
Yes, everything is fine. Works! Thank you very much!

**Comment by erfajo** [comment]
well, this tells me that language is something I need to dive into. So would it be ok to ask for a second test? I am trying to code something right now!?

**Comment by velichkoleg** [comment]
Да, конечно

**Comment by velichkoleg** [comment]
Have you already downloaded the new version?

**Comment by erfajo** [comment]
It looks like it is not just down the road to go from Cyrillic to Latin, I have tried to take your answer I got my mail from Github (Да, конечно) which I can see here means (Yes, sure)... as soon as I can generically get that result, that hopefully include all kind of letters, Chinese as well, then I will return with a new beta.
For now, I simply bypass all non-Latin letters for some new functions I am building for the upcoming versions.

**Comment by erfajo** [comment]
New build is uploaded, this is the beta version you have tested... just to be sure all others can continue working :-)

**Comment by velichkoleg** [comment]
Yes, everything works!))

**Comment by erfajo** [comment]
can you try if this work?
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/4419c9a5-33aa-448b-bc73-37b9739c3e37)

**Comment by velichkoleg** [comment]
Hello. Sorry for not responding on Friday. I checked it today, everything works!)

**Comment by erfajo** [comment]
Thanks a lot, then I will keep that solution until we shift to .net6/.net8 when the next releases of Revit and Dynamo are revealed in the spring of 2024.
I will close this issue as solved then :-)
