### ISSUE TITLE
Add shared parameter node changes

### ISSUE THREAD

**Issue by CAC79** [erfajo/OrchidForDynamo#232]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2023.1.3
Dynamo: 2.16.2
Orchid: 2.16

### The issue
The previous versions of this node (revit22 and earlier) used to take string for group type, now it calls for element group type. i have been using excel to create the lists for the inputs. how do i pull the group types for the new input? 

thank you
![orchid isue](https://github.com/erfajo/OrchidForDynamo/assets/154545059/51990ca3-de75-4e4f-82ae-28eb49d12ecf)

**Comment by erfajo** [comment]
As shown in the sample files...
![AddSetGet_R23](https://github.com/erfajo/OrchidForDynamo/assets/2844374/9cf14944-efa6-440f-8260-2acb62862a1d)
