### ISSUE TITLE
FamilyDocument.NewFamily - (COIeException 0x80030002)

### ISSUE THREAD

**Issue by bnwnn** [erfajo/OrchidForDynamo#233]
### Operating system
Windows 10 Enterprise version 10.0.19045 Build 19045

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 23.1.30.97
20230828_1515(x64)
2023.1.3
Dynamo: 2.16.2.9354
Orchid: 2.19.0.6119

### What did you do? 
Created and ran a script to create new families from an excel spreadsheet using a .rft file and save them to a designated folder as .rfa. The script looks for unique values in a column (types of equipment) and then combines that information with data from other columns to generate the family names. No information is created in the family, it just generates a blank family.

### What did you expect to see?
All of the new families created and saved into the designated folder

### What did you see instead?
In this case, the script found and generated 50 unique families but the node FamilyDocument.NewFamily is stopping after creating and saving the first 17 families in the list. The node gives the warning FamilyDocument.NewFamily operation failed. The model could not be saved: (COIeException 0x80030002).

**Comment by erfajo** [comment]
Maybe you should try to take fewer lines from the Excel file... instead of the entire sheet, take from lines 1-20, and 21-40 or something like that.

Concerning permissions, you need to have permission to write files in the folder you want to save families in. When I google 0x80030002 it always mentions something with permissions, that could be network folders or windows system folders… (”C:\Program Files” is a system folder!)

**Comment by bnwnn** [comment]
You were correct about the amount of RAM that was being used at once. The graph is relatively small overall but I was able to process a smaller amount of information using a chop node between the list of families to create and the family create node. This allowed the node to only look at 5 lines at a time. Thank you again for your help!

**Comment by erfajo** [comment]
Thanks for returning.

This is a fine example of how we are working with graph technology and not scripting. I have had some students doing their master's thesis, running into this problem. It is very important to understand that DAG’s come with some issues, without knowing that, you can risk ending up with some problems that might be strange to understand. But if you remember it is graphs, you will have an idea of what the mathematical challenges are.
So the next step is to monitor your RAM, see where things explode, and then try to optimize on that :-)
