### ISSUE TITLE
Location.GetProjectPosition returns wrong coordinates

### ISSUE THREAD

**Issue by dansity** [erfajo/OrchidForDynamo#236]
### Operating system
Win11

### Revit and Dynamo version
Revit: 2024.2.0.63
Dynamo: 2.19.3
Orchid: latest

### What did you do? 
I have a set of buildings defined by shared coordinates. I want to get their Location coordinates. My graph is rather simple: Location.ByName -> filter nulls (not shared position links) -> Location.GetProjectPosition ->some nodes to save to excel and organize data

### What did you expect to see?
the same coordinates that are reported by revit

### What did you see instead?
coordinates off by some random value (~200mm this case)

![ksnip_20240220-100410](https://github.com/erfajo/OrchidForDynamo/assets/31413689/3b2880f3-4dbb-4936-97f9-4c26b32ea2d1)

dyn file renamed to txt for upload
[LinkLocationToExcel.txt](https://github.com/erfajo/OrchidForDynamo/files/14341930/LinkLocationToExcel.txt)

**Comment by erfajo** [comment]
I have been testing in both Revit 2023 and 2024 to see if there should be any difference, and I simply can't replicate your error, no matter how many models I test.
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/be80660d-165f-4c8f-9d93-cf4373cb9c43)

Have you been trying to set the geometry precession?
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/a2a36978-799f-43e2-a9f9-84321a76f314)

**Comment by erfajo** [comment]
…However, I can move my project base point AFTER I have set the shared site. This means that the point shown inside Revit is the “new” point inside the model, but it is NOT the shared point in the linked model, it is actually telling you that someone is doing something with PBP that not should happen under any circumstances!

Hopefully do you NEVER move PBP away from internal Origin, so you should be able to return your model to Origin again, and again have the proper coordinates. However, I am sure that you can take the current point difference from internal origin and add/subtract to get your wanted coordinate, however, it is not a methodology I will recommend. Use Revit the right way is best.
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/697fda74-5666-477c-bfc4-dc60a656c93d)

**Comment by dansity** [comment]
Thank you for your reply. Unfortunately having the PBP not move is not always possible. We generally place the PBP on a specific corner of the plot and in some cases the plot boundary changes during project lifetime. It is much easier to move the PBP rather than than move the entire project.
I was in the assumption this node gives you the distance between survey and base point which should read as much as it displays in revit -if i understand it correctly.
Now to resolve it -as you said- I need to add the difference to the coordinates. Do you know of a simple way to acquire how much the PBP is away from the zero?
Thanks

**Comment by erfajo** [comment]
Well, it is a problem that Revit allows this, however, still it is an option to do so, and this means that I could add this "not so good thing to do" to my node.
Let med return on this, asap (I am coding something else at the moment).

**Comment by erfajo** [comment]
I have uploaded a new build (6167) today, this includes a range of new nodes for location, and the option to use PBP instead of InternalOrigin, please test the nodes and report back :-)

**Comment by erfajo** [comment]
Please re-download the installer, I made an error when compiling... I am afraid that only the 2.16 package is functional, the other verticals might be corrupted :-S
