### ISSUE TITLE
run orchid version 230.0.3.7682 on dynamo 2.19.3

### ISSUE THREAD

**Issue by 4004259** [erfajo/OrchidForDynamo#239]
Hello,
I want to reactivate a diagram which was working with revit 2020 (20.2.12.1) and dynamo 2.3.0.7661.
The diagram uses orchid 230.0.3.7682 and archi-lab. I think you already know which discription is following now: I was able to run the old version of archi-lab in the current dynamo-version (2.19.3). For orchid I was not successful by now. There is only the possibility to run the latest orchid version and this is not that what my diagram needs.
So:
Is there a possibility to run orchid 230.0.3.7682 on dynamo 2.19.3?

I am a newbie in dynamo- thankful for every single tip.

Big thanks in advance!

Revit: 2024.2 | 24.2.0.63
Dynamo: 2.19.3
Orchid: [as described]

Best regards

**Comment by erfajo** [comment]
There has been significant development from 2.3 versions to 2.19 and it will get even worse when we shift to 3.0 within a few months. I follow very closely the level of development in Dynamo and Revit, so around 50-60% of the nodes might have been developed in that period. This might be much lower for other packages I don’t know!?

However, if you send the graph (.dyn) file, then I can take a look at it, and give my best shot on what to change. You can add an extra .txt extension to the file, then you can upload it. Meaning “xxx.dyn” becomes “xxx.dyn.txt”.

**Comment by 4004259** [comment]
Hello erfajo,
big thanks for your quick answer and your help!
I can send you the graph as described. But could there be a possibility to send you these files in a way that just you can download and read the graph? No offense to all others. I hope they can understand.

Looking forward hearing from you.

Best regards

**Comment by erfajo** [comment]
I do understand privacy, but if your graph doesn't include coding (C#, Python, or DesignScript, etc.), then I find it very odd that you have something not seen on planet Earth before. Meaning, no matter which graphs you send me, all functions need to be public available, otherwise will I not be able to help you. Anything not public will be challenging.
