### ISSUE TITLE
IFC Setting nodes

### ISSUE THREAD

**Issue by dmscholten87** [erfajo/OrchidForDynamo#24]
Revit: 2018
Dynamo: 1.3.2.2480
Orchid: 134.4.2.7024

Hello Erik,

I've tried the IFC nodes and tried to make my own IFC settings to export IFC's from different models. However i have a warning after the first node and maybe you can help me.
I've make the linked nodes as the example i found on dynamobim forum.
See the picture below what the problem looks like.

The .dyn file is attached in the Zip file.

Thanks for the effort.

[Export multiple Revit to IFC.zip](https://github.com/erfajo/OrchidForDynamo/files/3034391/Export.multiple.Revit.to.IFC.zip)

![Warning Dynamo](https://user-images.githubusercontent.com/41347566/55410512-41c48700-5564-11e9-8e1c-1f621a981722.png)

**Comment by erfajo** [comment]
if you have a light grayed node, then you miss to give an input.
Your problem is that you need to set a starting IFC setting in the first node.
try to see the sample files for how to use the nodes.

**Comment by dmscholten87** [comment]
Thanks for your answer, i've missed indeed the first "IFC Setting" node.
I know that when the node is light grey i missed some input wires, luckily I still learn from my mistakes every day. 

Thanks again
