### ISSUE TITLE
Orchid package not installed in Dynamo 2.10 Revit 2022

### ISSUE THREAD

**Issue by anitamta92** [erfajo/OrchidForDynamo#240]
Revit: 2022
Dynamo: 2.10.1
Orchid: 212

The issue:
I tried to install orchid package 212 manually and in Dynamo software, but the nodes still not showing in Dynamo.
I unzipped the folder in the following path, and "unlocked" was also off once unzipping the files.
C:\Users\name\AppData\Roaming\Dynamo\Dynamo Revit\2.10\packages\orchid

When I open dynamo, this errors pops up.
![error orchid package](https://github.com/erfajo/OrchidForDynamo/assets/163341913/ee629623-97c0-4676-b90c-d19d94f9c25c)

**Comment by erfajo** [comment]
That is correct, Orchid 2.12 is for Dynamo 2.12 and not Dynamo 2.10. However, it might work under Dynamo 2.10, I simply can't remember the changes between 2.10 and 2.12. So I will recommend that you update your Revit and Dynamo to the latest version and use 2.12 version.
You can try to move the content from the 2.12 default Dynamo package folder to the 2.10 to see if it works. However, no guarantees are given...

**Comment by anitamta92** [comment]
Thank you for your comment.
It is mentioned up to date in my Dynamo dialog box. How can I update my dynamo 2.10 to 2.12 in Revit 2022.
My Revit is also updated.

**Comment by erfajo** [comment]
The current state is that you need to update to Revit 2022.1.5.
I can't remember when Dynamo moved from 2.10 to 2.12, but somewhere along the releases, it did. update to the latest release of Revit and you will get the updated Dynamo for Revit as well.

**Comment by anitamta92** [comment]
I updated my Revit, and dynamo to 2.12.
Then install the package through dynamo. Got these two errors.
How can I solve this?
![image](https://github.com/erfajo/OrchidForDynamo/assets/163341913/6b31e7b5-874c-4e93-9cee-8207bc250b02)

**Comment by erfajo** [comment]
Please check your paths where you load from in settings. I can see that the package is loaded, but still you are getting errors.
I can exclude that I could have some error since I just recently uploaded the first version that also support Revit 2025. I will test if something could be related to that. When Revit 2025 will be released there are going to be quite some changes this time.

**Comment by erfajo** [comment]
I can't find any errors in any of my versions of Orchid, However, I can see now that you are not using the "proper" IFC exporter in Revit. You probably use the built-in version of the IFC exporter, but you should consider the exporter made by the Revit-IFC team at Autodesk.
https://github.com/Autodesk/revit-ifc/releases

**Comment by anitamta92** [comment]
Thank you.
The issue with orchid package was solved.

**Comment by anitamta92** [comment]
Hello again,
I tried to install the Orchid package for my colleagues. The nodes do not appear, although they are using Dynamo 2.12 for Revit 2022. 
I've installed both installers including the sample, but it has only the read me node.
Can you help to solve the issue?
Thank you in advance.

**Comment by anitamta92** [comment]
Solved 
Please disregard the previous message.
Thank you
