### ISSUE TITLE
Issues with the "Selection.ModelElement" node

### ISSUE THREAD

**Issue by Acastillo-eus** [erfajo/OrchidForDynamo#241]
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 2023.1.1
Dynamo: 2.16.1.6510
Orchid: 2.16.4.6189

### What did you do? 
After updating the package, the node from the version (216.2.1.8410) is missing
![imagen](https://github.com/erfajo/OrchidForDynamo/assets/123563975/938a51a2-eb9f-406d-9578-1b25c779cc8c)

We updated the node in the dyn file to the new Element.ModelElement, but is not working.

### What did you expect to see?
The list of all the model elements in the rvt file and the categories of these element.

### What did you see instead?

![imagen](https://github.com/erfajo/OrchidForDynamo/assets/123563975/9160886c-a882-440b-826d-1f2562e8b030)

It retrieves a null result.

**Comment by erfajo** [comment]
This is surely a bug... I am on it.
Thanks for reporting.

**Comment by erfajo** [comment]
This was a tricky one... however, I have fixed it, please download again and install :-)

**Comment by Acastillo-eus** [comment]
Hi erfajo. The node is working as expected now.
Thank you for the fast response.

Regards
