### ISSUE TITLE
Type Initializer threw an exception.

### ISSUE THREAD

**Issue by DarioMariuzzi** [erfajo/OrchidForDynamo#25]
### Operating system
Win 10 Pro

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2019.2.1
Dynamo: 2.0.2.6826 (Core) 2.0.2.6833 (revit)
Orchid: 202.4.2.7024

### What did you do? 
set up nodes to select material category, select all elements of category get color, Material.AppearanceAsset (ORCHID), AppearanceAsset.SetGeneric (ORCHID) 

I have a project with materials created including render appearances. Each material's graphic color is assigned as per required RGB codes and I wish to transfer same colors to render appearance

### What did you expect to see?
Dynamo to take the color in the graphics of the material and set the render appearance color

### What did you see instead?
Material.AppearanceAsset (ORCHID), AppearanceAsset.SetGeneric (ORCHID)  both threw up issues e.g "Warning: AppearanceAsset.SetGeneric operation failed. 
The type initializer for 'Orchid.Materials.AppearanceAsset' threw an exception."
[z Orchid Render App.zip](https://github.com/erfajo/OrchidForDynamo/files/3054268/z.Orchid.Render.App.zip)

**Comment by erfajo** [comment]
You are mixing things together, please see the samples.
