### ISSUE TITLE
Finding and replacing the values of a particular set of parameter

### ISSUE THREAD

**Issue by VAVIPL** [erfajo/OrchidForDynamo#251]
Hello @erfajo,

Greeting from a very beginner with Dynamo & Revit.

Revit : 21.1.30.74
Dynamo : 2.6.1.8786
Orchid : 2.6.9.6276

I have a project with a bulk number of families. I wanted to find and replace the values of a particular set of parameters, which has already been assigned with some other values. But these families have nested families inside it. I tried making a basic Dynamo script which even doesn't make any effect on my Project. The values are all same. It did not change. 

![image](https://github.com/erfajo/OrchidForDynamo/assets/173201783/1be76d43-4947-4d47-811d-5edad1889854)

For this I tried the following basic Dynamo Script. Also this contain only to change one parameter value which is TRSDC_Data Classification Code. Likewise TRSDC_Data Classification Description also to be changed. Again there are multiple entries for these two parameters. And I need to change the value only if a specific value comes for these parameter.

![image](https://github.com/erfajo/OrchidForDynamo/assets/173201783/cbc996ee-3591-43f1-808d-a6e2feb02c89)

Can you please help me to create a script which will allow me to change the parameter values including the nested families at once.

Thanks in-advance

**Comment by VAVIPL** [comment]
Hi @erfajo,

First of thanking you for the introduction and for the efforts. 

Sorry for the word "scripting / script". Now onwards will state it as "graph".

I tried the graph you have send. But it is failing at "Parameter.SetValue". Attaching a screen shot herewith. 

![image](https://github.com/erfajo/OrchidForDynamo/assets/173201783/c182fe57-ce43-4bb5-8bf6-d8fecf2674ab)

Even this is not making any reflection on the model. No change of values at all..!!

**Comment by erfajo** [comment]
The error indicates that something is wrong in the families!

Your need to check all your families, check that parameters are instance parameters in families you want to change, AND check if a value is overridden by setting a default value, that will also create an error.

Lastly, to throw an error, the “system” only needs one error in one of the 540 parameters you try to set, so you could try testing with a subset of parameters. Add a codeblock and write parameter[0..20] and then change the numbers to [21..40] and keep doing that until you can see where errors might happen, and then act on that.

**Comment by VAVIPL** [comment]
I can see, the parameters of the nested families are all associated.
![image](https://github.com/erfajo/OrchidForDynamo/assets/173201783/c49be710-9864-43df-8528-73836e40c8bc)

Is there any option to remove the association for a particular parameter of the nested family? (The thought process is that, if I remove the association to that particular parameter, I can assign any value through schedules. Also these associations are not countable. There will not be any issue if it got changed).

**Comment by erfajo** [comment]
Yes there is nodes for that as well, please take a look at the sample collection, and/or go to dynamobim forum and see for inspirations.
I will close this issue, since it never was an issue :-)

**Comment by VAVIPL** [comment]
Thank you So much..!!
