### ISSUE TITLE
Orchard212.1.1.8227 not found, copied files did not work

### ISSUE THREAD

**Issue by CathyShaoqin** [erfajo/OrchidForDynamo#252]
Revit:2023
Dynamo: 2.16.2
Orchid: 212.1.1.8227
### The issue
I am trying to use a Dynamo which needs Orchard 212.1.1.8227, I clicked "installed specified version", the error message shows the version could not be found.
So I downloaded Orchard212.zip file from GitHub and saved them to the folder. But also added the file path to package path. But it still not working. Can you please help? Thanks
![Orchid Package error](https://github.com/erfajo/OrchidForDynamo/assets/174440206/57d07827-5178-41f0-b3d1-e2fec80f4476)
![Orchid package location](https://github.com/erfajo/OrchidForDynamo/assets/174440206/e4b06d0b-2649-4430-a07c-1a8251b17f74)

Cathy

**Comment by erfajo** [comment]
For sure installing 2.12 will fail when using Dynamo 2.16
Do use the proper versions...
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/fe30e5bd-9565-4f65-80b5-b0cd4ee3b8a1)

**Comment by CathyShaoqin** [comment]
I have tried to install 216, but the Dynamo I am using needs 212. So when I open Dynamo, still error, cannot find a few nodes. Refer the attached as one example. Any advice? Thanks
Cathy
![Orchid Package error](https://github.com/erfajo/OrchidForDynamo/assets/174440206/0227374e-7712-4903-89d0-b5e497ecf740)

**Comment by erfajo** [comment]
You cant use a version of Orchid not suited for Dynamo. You MUST use version 2.16, there is no way around.
![image](https://github.com/erfajo/OrchidForDynamo/assets/2844374/6d8d2e1e-1818-49c2-9a65-377315b57d3b)
