### ISSUE TITLE
Add shared parameter

### ISSUE THREAD

**Issue by martinvrielink** [erfajo/OrchidForDynamo#253]
Windows 11 Pro
![image](https://github.com/user-attachments/assets/a1409211-827d-4fba-8ea2-8bb7c6df9986)
![image](https://github.com/user-attachments/assets/4fe6077a-a39e-4a77-9e3d-6f775dca2bfb)
---
### What did you do? 
I want to add a shared parameter to a family. This has to be done for 50 families and 10 shared parameters.

### What did you see instead?
The issue is that i cant get around the following error. See below.
In a  previous version of orchid this worked before.
![image](https://github.com/user-attachments/assets/3d6df43b-5297-4b32-a752-d6963c502bd7)

Do you have any thoughts on this topic?
[Desktop.zip](https://github.com/user-attachments/files/16389300/Desktop.zip)

Kind regards,

Martin

**Comment by erfajo** [comment]
I should have fixed the issue now... please confirm by installing the 6324 build

**Comment by martinvrielink** [comment]
Hi, Thank you very much. The issue is fixed

**Comment by martinvrielink** [comment]
Hi, Is this also a problem in the Revit 22 version or am i missing something?
Kind regards, Martin
![image](https://github.com/user-attachments/assets/59cd3fb0-6e80-4267-ad10-20e445275633)
