### ISSUE TITLE
Orchidrb.dll did not have a signed certificate. Orchid_320_revit not show

### ISSUE THREAD

**Issue by giotlehong** [erfajo/OrchidForDynamo#257]
Can someone help me? i can not install orchid 320 revit for my revit 2025 version because of error above. What can i do to fix this?

**Comment by erfajo** [comment]
It sounds like you are a newcomer, It sounds like Windows has warned you from installing my software, and it is a good thing that it does that. However, if you want my software you have to bypass this warning as is the case with many other kinds of software built by all of us not having a huge softwarehouse in our back that can pay for a certificate. If you don’t want to bypass it, then simply skip my software and find something else.
