### ISSUE TITLE
Unable to Install Orchid dynamo package in Revit 2024

### ISSUE THREAD

**Issue by FraNardi95** [erfajo/OrchidForDynamo#259]
### Revit, Dynamo and Orchid version

Revit: 2024.3
Dynamo:
![Dynamo version](https://github.com/user-attachments/assets/01f10d1d-69f4-4a14-a32e-3062d49d5609)
Orchid:
![Orchid version](https://github.com/user-attachments/assets/f55e8efb-8995-4f29-9e3a-f9993c3a4ef8)

### The issue
I tried the automatic installation by downloading the file "OrchidForDynamo.exe", but it did not work.

I tried the manual installation by copying the zipped file (after unzipping it) into the dynamo package folder (C:\Users\f.nardi\AppData\ Roaming\Dynamo\Dynamo\Revit\2.19\packages), but even this didn’t work.

I do not understand what I am wrong, thank you for any indications.

**Comment by erfajo** [comment]
Did you read the error page? (https://github.com/erfajo/OrchidForDynamo/blob/master/Error.md)

If none of that worked then your download might be corrupted, could you try to download once more and open the zip file with 7zip to ensure problems do not occur in the zip file.

**Comment by FraNardi95** [comment]
The problem was resolved by unlocking the zip file before extracting the files. thanks for the indication

**Comment by erfajo** [comment]
that is the most occurring error, that users dont use 7zip or don't know that locking files is a Windows issue :-)
