### ISSUE TITLE
All Orchid nodes fail with error "Your usage access has expired (IR.d02.1)..."

### ISSUE THREAD

**Issue by LRK-BIM** [erfajo/OrchidForDynamo#261]
### Revit, Dynamo and Orchid version

Revit: 22.1.70.9
Dynamo: Dynamo Revit 2.12.1.11123
Orchid: 2.12.8.6373

### The issue

All of the Orchid nodes that I've tried to use so far fail with the following error message: "Warning: <node name> operation failed. 
Your usage access has expired (IR.d02.1), for further information contact the author of the package!"

These errors only appeared after installing the lastest versions from here using the provided installer. Unfortunately I had already removed the previous Orchid files so I'm currently unable to revert back to the version that worked / tell you what version it was. 

Please see the images below and let me know if there is additional information I can provide to help determine what's happening.

![2024-10-22 13 13 55](https://github.com/user-attachments/assets/93eb6e0e-c3a7-41ff-aa9a-161c3ac0e958)
![2024-10-22 13 14 22](https://github.com/user-attachments/assets/5ff25d65-617b-4d6b-bec4-b89c31b3bbbd)

**Comment by erfajo** [comment]
From the information you gave me on LinkedIn, I am surprised you are ending up here!?

So please try to walk me through your environment. Are you using Windows 11? 
Do you have other packages installed? have you tried to follow the error description?https://github.com/erfajo/OrchidForDynamo/blob/master/Error.md

**Comment by erfajo** [comment]
Could you please try this beta out?
![image](https://github.com/user-attachments/assets/954fc6a3-d37d-4eb6-83ae-20f395282d27)

**Comment by LRK-BIM** [comment]
Hi @erfajo , thank for your reply! I will be able to test this out next week (too many deadlines this week) and get back to you with the results.

**Comment by LRK-BIM** [comment]
> Could you please try this beta out? ...and give feedback asap!? ![image](https://private-user-images.githubusercontent.com/2844374/379854975-954fc6a3-d37d-4eb6-83ae-20f395282d27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjY5NTksIm5iZiI6MTczMTQyNjY1OSwicGF0aCI6Ii8yODQ0Mzc0LzM3OTg1NDk3NS05NTRmYzZhMy1kMzdkLTRlYjYtODNhZS0yMGYzOTUyODJkMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMTU1MDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjIxMmQ0NDkxOTI4M2Q1YzBkZTdlNjkyZmM3MzkxZTJmOTIyMzZlYjkxZWY5OTM3NzI5OTE1ODMwMWY1MTE4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Q24217oFMxQT3rE6zIIjglIlJtDxUs0M7Lqa69uzbuE)

Hi @erfajo, 

Happy to report that the Beta installation above worked; no more usage access errors. 

FYI: Windows 11 (but had the same errors on another Windows 10 machine)

Other Packages: Yes, but I had tested Orchid with all the other packages removed. With this latest Beta I first installed and tested without any other packages, then added the other packages back in. 

Thank you greatly!

**Comment by erfajo** [comment]
Unfortunately, I know what the problem is and I made a workaround which is not a solution, so I have a problem to solve. However, at the moment users will not experience that problem, but if I don’t solve it, I will have a problem in the near future.

I will make new builds with the temporary solution asap.

Thanks for the report :-)
