### ISSUE TITLE
Orchid 2.19 Package issue in Revit 2024.3

### ISSUE THREAD

**Issue by Duki2711** [erfajo/OrchidForDynamo#263]
Hello. I have an issue with Dynamo v.2.19.3. I am working in Revit 2024.3. The problem is in installing the Orchid and bimorphNodes package that was downloaded from the official website.
It is placed on my C drive in the following location C:\Users\User\AppData\Roaming\Dynamo\Dynamo Revit\2.19. 
When I open Dynamo it is asking for a different Orchid version 216.2.0.8381 and it won't let me install this version or the correct version 2.19 even though in the package manager the path to the 2.19 version is correct.

**Comment by erfajo** [comment]
The only option to download Orchid is to download it from my GitHub. The package available on the packagemanager is only a placeholder, and after installing it from that source, the only available node would be nodes informing the user to download from my GitHub.

**Comment by Duki2711** [comment]
I did download it from there

**Comment by Duki2711** [comment]
![3](https://github.com/user-attachments/assets/2e77f101-dfb5-421e-bc8b-36ac6b518c8d)

    "OrchidRB, Version=2.19.3.6430, Culture=neutral, PublicKeyToken=null",
    "OrchidRE, Version=2.19.3.6430, Culture=neutral, PublicKeyToken=null",
    "OrchidIB, Version=2.19.3.6430, Culture=neutral, PublicKeyToken=null",
    "OrchidIE, Version=2.19.3.6430, Culture=neutral, PublicKeyToken=null"

**Comment by erfajo** [comment]
Well then you have the right version of Orchid... try to see if you somehow also try to load from other paths inside Dynamo.

**Comment by erfajo** [comment]
I can't see where the paths point, but you can try reading it. Likewise, try to see which version of the packages that are loaded... I presume everything is as expected. I have no idea what error you are trying to describe!?

**Comment by Duki2711** [comment]
![5](https://github.com/user-attachments/assets/fc5ea8d9-e5ec-41a3-8d73-5258f3e89f63)

it is asking for a different Orchid version and when I look from where it is installing Orchid it is the correct path with the newest Orchid in the folder

**Comment by erfajo** [comment]
that is not an error... that is one or more missing node(s).

one or more of the nodes has been marked obsolete at some point and removed between the last time you used the graph and now.
find the node(s) marked with an error, and change them to the new one. the most common error is if the nodes has changes its location in the package due to the expansion of the package.

...and you should not need any of the other packages, I am almost sure that I have all the nodes you need.

I will close this issue since there was no error.

**Comment by Duki2711** [comment]
There is an error, all the packages are loaded and working except Orchid.

**Comment by Duki2711** [comment]
all the suggested packages are loaded without errors, only Orchid doesn't work. It is still suggesting the 216 version instead 219

**Comment by erfajo** [comment]
Sorry to say, but it sounds like you are very new in the dynamo world, you should learn to walk before you try to run, and I don’t have the time to do user support at the kind of level you are asking for.

I suggest you use the dynamobim forum for help, but before doing that please learn how dynamo works, by doing the introductions courses available on the dynamobim webpage.
