### ISSUE TITLE
ADD SHARED PARAMETER AND GROUPTYPE

### ISSUE THREAD

**Issue by Mau-96** [erfajo/OrchidForDynamo#264]
### Revit, Dynamo and Orchid version
Revit: 2024.2.2
Dynamo Core: 2.19.3.6394
Dynamo Revit: 2.19.4.13096
Orchid for Dynamo: 2.0.0.6430

### The issue

I'm trying to use the "SharedParameter.Add" node to add shared parameters inside a Revit family file. I have a list with the names of those parameters and another list with the corresponding group types . When I run the Dynamo script, the shared parameters are added to the family, but they are all grouped according to the first group type. Instead, I need each parameter to be grouped according to its corresponding group type.

![image](https://github.com/user-attachments/assets/9e9365ee-281d-4ae9-bf78-5380c2079606)
![image](https://github.com/user-attachments/assets/be1fea53-55f3-4c7b-8b38-ea6ae7061c9b)

Is it a bug in the Orchid node or am I doing something wrong in my script?
Thank you.

Mau

**Comment by erfajo** [comment]
I dont think there is any error, please verify the input is correct.
ParameterName takes a list, but the inPorts do NOT!, this means you need to control your input, most likely by using lacing or list level.
![image](https://github.com/user-attachments/assets/75585527-c087-42f8-98cd-6dd4872c1ace)

**Comment by Mau-96** [comment]
Thank you @erfajo for the answer. Is there the possibility to call this node inside a python script? In this way, I can call the node many times as the parameter that I have to add.

Mau

**Comment by erfajo** [comment]
In my opinion, that would be "overthinking" the problem, just order your data if you feel that is a better method.
[ [param1, param2, param3], groupName, groupType, bool, bool]

**Comment by Mau-96** [comment]
Ok thank you for the suggestion
