### ISSUE TITLE
Document.BackgroundOpen Exception thrown

### ISSUE THREAD

**Issue by scrowe00** [erfajo/OrchidForDynamo#29]
### Operating system
(Windows 10)

### Revit and Dynamo version
Revit: 18.3
Dynamo: 2.0.1
Orchid: 202.4.2.7032

### What did you do? 
use document background open to open family document in background

### What did you expect to see?
document opened

### What did you see instead?
spits out null and I get "Warning: Document.BackgroundOpen operation failed. 
The type initializer for 'Orchid.Core.Document' threw an exception" error.

I have recently switched over to 2.0.1 and upgraded my orchid package as well. Not sure if this error is because of something I did or not. I have tried with a single file as well as several and I get the same error.

![image](https://user-images.githubusercontent.com/49884822/56533074-984a3300-651c-11e9-82f5-67d7c2d4079f.png)

 <a class="attachment" href="/uploads/dynamobim/original/3X/4/1/415260cca07fa940d0029f48fd634acb6c42f2c8.dyn">Change_Family Category.dyn</a> (19.6 KB)

**Comment by erfajo** [comment]
first, I cant open your attached graph file... 

Next, When I try to rebuild opening a file from a folder, where folder and file contains spaces, then it goes well... so I am afraid I cant replicate your error
![Capture](https://user-images.githubusercontent.com/2844374/56590002-92208900-65e6-11e9-8482-72a934e9afdb.png)

Try to move your document to desktop and try opening it again... if this goes well, then I would presume that your path is your error.

**Comment by gscribe** [comment]
Hi,

I do have the same error. But not all nodes were affected. I guess we have a problem in CurrentDBDocument.

![Capture1](https://user-images.githubusercontent.com/49343947/56845256-1299ff00-68f1-11e9-97c0-e8aea3d26487.PNG)
![Capture](https://user-images.githubusercontent.com/49343947/56845291-76242c80-68f1-11e9-82de-ae52ff097525.PNG)

**Comment by erfajo** [comment]
try to upload your graph, remember to rename or add the extension .txt to the graph file, so it can be uploaded.

**Comment by gscribe** [comment]
I tried to create a shared parameter and load back to the project.
[to send - Copy.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3123891/to.send.-.Copy.dyn.txt)

**Comment by erfajo** [comment]
I have tried to open your graph, and I must admit I do not understand what you are trying to do!?

I have an idea that you are trying to add some shared parameter to some families open in background!

What I dont know is how you find those families... are they hosted inside a project or are they saved somewhere in a network folder?

My advice is to see my sample collection, try to see these two examples
"Samples/Dynamo_1.3.x/Families/Collect families in project"
"Samples/Dynamo_1.3.x/Families/BulkUpgrade"
