### ISSUE TITLE
Index was out of range

### ISSUE THREAD

**Issue by Hyun-Tak** [erfajo/OrchidForDynamo#30]
### Operating system
Window 10

### Revit and Dynamo version
Revit: 2019
Dynamo: 2.0.2.6823
Orchid: 202.4.2.7024

### What did you do? 

I tried to check out the buildin parameter.
The node of 'builtin parameter' has the error message which is ' index was out of range. Must be non-nagative ..."
How can I have the node run without an error?
Thanks.

P.S. I was testing it on my Revit project file.

![Untitled](https://user-images.githubusercontent.com/12069639/56611529-9e511a00-65d7-11e9-8498-54a27f4e3b46.png)

**Comment by erfajo** [comment]
I have just released a huge rebuild of the existing version and a release for Dynamo 2.1... in this have I tried to adjust the code in the BIP dropdown node. I could not replicate your error, so I am just guessing if this way to write the code is better than the previous way.

Try to download the update, but be aware of the migration problem dynamo has!
https://erfajo.blogspot.com/2019/04/minor-release-13450-20250-and-major.html
