### ISSUE TITLE
Load Into project and close

### ISSUE THREAD

**Issue by andre-abotnes** [erfajo/OrchidForDynamo#32]
Does one exist, or is it possible to create a node thatcan load a family back into a document and close?

I am trying to insert a family at the innermost family of a nested family, and load them all back together into a project, using Dynamo.

**Comment by erfajo** [comment]
I have a graph showing this workflow in the sample collection
https://github.com/erfajo/OrchidForDynamo/blob/master/Samples/Dynamo_2.x.x/Families/Collect%20families%20in%20project.png
