### ISSUE TITLE
Various nodes not working, reporting unresolved

### ISSUE THREAD

**Issue by evvas** [erfajo/OrchidForDynamo#33]
### Operating system
Windows 10

### Revit and Dynamo version

Revit: 2019.2.1
Dynamo: 2.0.2.6833
Orchid: 200

### What did you do? 
Nodes not working properly, reporting unresolved. 

### What did you see instead?
![image](https://user-images.githubusercontent.com/50918050/58182120-f0ec2780-7ca4-11e9-823a-027fda0a5d14.png)

**Comment by erfajo** [comment]
You have a problem with Dynamo installation or some other packages... 
I know that some packages by mistake have included the DynamoCore.dll in their packages, and this will give errors. You could try to search for this file in your **package** folder, and remove this file if it exists.

if your error still exists, then please upload your graph file, add the extension ".txt" and then upload it

**Comment by evvas** [comment]
Apologies if I am a misunderstanding, but why have I started experiencing a
problem with these nodes when I haven't even updated Dynamo or any other
package?
Just a week ago the same configuration(without even installing Orchid 200)
was working okay. Almost overnight the nodes turned to ''unresolved'', so I
tried installing Orchid latest version and the well I got that...
I will read your posts after work hopefully they will clear the mess in my
head.

I will test what you recommend and provide feedback.

Thanks

**Comment by erfajo** [comment]
Graphs you have made in Orchid 202.4.2 or earlier will come with one or more errors in Orchid 202.5.0 without changing anything in your Dynamo/Revit setup.

When I, and most likely other developers, figured that migration did not work in the Dynamo 2.x range (including 2.1.x range) many of them decided not to move around with nodes. I did also. But while waiting for the Dynamo team to fix migration did I extend my package with more than 100 nodes. At some point was it necessary to make a better organization of all my nodes.

The migrations which work in Dynamo 1.3.x series should be the same in Dynamo 2.x series, but apparently not. This means that graphs made in 1.3 will be migrated correctly, even if you choose to update it to Dynamo 2.x series at the same time you open an old 1.3.x graph. Graphs made in the Dynamo 2.x series will fail!

I really can't do anything about this problem…


However, another problem can also be that you have another package which has included assemblies from Dynamo… and this will for sure give you problems.

Have you tried to remove all other packages except mine, and then see if you could run the graph?

I know that Lunchbox had this error some month ago in the latest build thy uploaded at the Package Manager. All the later build which they also release like I do, meaning outside the Package Manager do not have this problem.

But I am not aware if other developers have included things which can give you problems. The only way to test it is to move all packages out and then test it by moving one package back at the time to test where the error occurs.
