### ISSUE TITLE
AddProjectParameter behavior on 2017.xx and 2018.xx

### ISSUE THREAD

**Issue by knot515** [erfajo/OrchidForDynamo#35]
### Revit, Dynamo and Orchid version

Revit: 2019xx - 2018.xx - 2017.xx
Dynamo: 2.0.2 - 1.3.4
Orchid: 202.5.0.7072 - 134.5.0.7072

### The issue
hi, I'm trying to use the AddProjectParameter node but I'm am encountering some issues. I'm using it to update the the category binding on certain parameters. It really works fine in revit 2019, but I also need to make it run on older projects based on Revit 2017 and 2018. When I try to run it I get the "threw an exception" error. I'm starting to think that the node wont work on version older than the 2019 one, but I can't find any documentation regarding. Also, I'm having issues to update the category binding on updated files (2017->2019). It seems I can't modify the binding on parameters preexisting the update but only on post-update created ones.

**Comment by erfajo** [comment]
The API has not changed on this subject, and I havnt changed my code the last year on this subject. I think the issue is placed elsewhere. Could you please upload a testing environment with a small revit file and the graph file.
Files might need to be temporarily renamed into txt or something else to upload them at github.

**Comment by knot515** [comment]
I've prepared some sample files. The dyn is always the same. I can successfully operate on the 2019.2 RVT but, the same script, doesn't work on 2017 or 2018 files. I also included updated files from those builds to 2019.2 but the same dyn instruction doesn't work in order to update the category binding of existing project parameters

[SAMPLE_2018.3.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/3324875/SAMPLE_2018.3.rvt.txt)
[SAMPLE_2018.3_TO_BE_UPDATED.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/3324876/SAMPLE_2018.3_TO_BE_UPDATED.rvt.txt)
[SAMPLE_2018.3_UPDATED.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/3324877/SAMPLE_2018.3_UPDATED.rvt.txt)
[SAMPLE_2019.2.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/3324878/SAMPLE_2019.2.rvt.txt)
[PROJECT_PARAMETER_CREATE-UPDATE_BINDING.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3324879/PROJECT_PARAMETER_CREATE-UPDATE_BINDING.dyn.txt)
[SAMPLE_2017.2.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/3324880/SAMPLE_2017.2.rvt.txt)
[SAMPLE_2017.2_TO_BE_UPDATED.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/3324881/SAMPLE_2017.2_TO_BE_UPDATED.rvt.txt)
[SAMPLE_2017.2_UPDATED.rvt.txt](https://github.com/erfajo/OrchidForDynamo/files/3324882/SAMPLE_2017.2_UPDATED.rvt.txt)

**Comment by erfajo** [comment]
thanks, I will look into this asap

**Comment by knot515** [comment]
It works fine on my PC. I'll send you the screen anyway, it's super simple
![Cattura](https://user-images.githubusercontent.com/52198643/60107719-a8be9a00-9767-11e9-8c86-3628a903c5fc.PNG)

**Comment by erfajo** [comment]
it do not work... it is actually adding the parameter to your shared parameter file, and that is not the intention...  this is the error!

**Comment by knot515** [comment]
Hi, I downloaded the new build and performed the same tests and I'm encountering most of the same issues. I put together a table showing all the cases tested.It looks like the node still doesn't work in revit 2017.2 (both dyn 2.0.2 or 1.3.4 - new builds downloaded and installed). On the other hand, in revit 2018.3 e 2019.2 I can create parameter but I can't update the binding of preexisting project parameters. I think the problem is in the fact that all the project parameter I create trough your node are classified as shared parameter when I go trough the Revit Project Parameter dialago window as shown in the screenshots. The funny thing is that if I go in shared parameter I can't find those parameter, and of course, the aren't in the TXT. If I search inside the RVT with clockwork's Document.ProjectParameters, parameters crated with your Parameter.AddProjectParameter are listed as Shared Parameters. Even funnier if I look inside the document with your Parameter.ProjectParameters I find nothing. If I look with Parameter.SharedParameters I find them, but I also find old Shared Parameters deleted in the RVT and not present in the TXT.

All the files i created are stored here:
https://www.dropbox.com/s/1m2xnr1wcnvc2nv/Parameter.AddProjectParameter_TESTS_2019-06-26.zip?dl=0

**Comment by erfajo** [comment]
I dont have Revit 2017 anymore, so I cant test this. It should be the excact same procedure as

**Comment by knot515** [comment]
ok, I get it. If you don't mind leaving the thread for a few hours, I'll try something new tomorrow morning
