### ISSUE TITLE
ApperanceAsset.SetGeneric not working

### ISSUE THREAD

**Issue by atleso** [erfajo/OrchidForDynamo#38]
### Operating system
(e.g. Windows 7, Windows 10, etc)

### Revit and Dynamo version
Revit: 2020
Dynamo: 2.1.0.7733
Orchid: 210

### What did you do? 
I am trying to set the color of the appearance asset using the "ApperanceAsset.SetGeneric" block, but somehow this does not work. I tried following the C24 timber example provided but this does not work either, and there is no clear error being thrown. The only thing being said is "Warning: AppearanceAsset.SetGeneric operation failed."

![image](https://user-images.githubusercontent.com/30384601/61587845-fa551b80-ab91-11e9-94c1-c9ea7cba9977.png)

**Comment by erfajo** [comment]
I will try it out when I return from my summer holiday

**Comment by erfajo** [comment]
Sorry for the long response time, but it has been and is still a very comprehensive job to handle all the functions attached to materials...

Your issue has been solved some time ago, and I am very sorry that I forgot to answer you... however, some new features have been added to materials in the meantime, maybe you can use some of those as well :-)
![Apperance](https://user-images.githubusercontent.com/2844374/174625672-cd643280-2d90-461a-a541-dbd50ba4aff4.png)
