### ISSUE TITLE
Print.By.View node giving "no views/sheets selected" error

### ISSUE THREAD

**Issue by fadelm0** [erfajo/OrchidForDynamo#39]
### Revit, Dynamo and Orchid version

Revit: 20.0.0.377
Dynamo Core: 2.1.0.7500
Dynamo Revit: 2.1.0.7733
Orchid: 210.1.0.7117

### The issue

I've had this issue with the node Print.ByView a while ago where it doesn't work and gives a "no views/sheets selected" error. I posted it on the dynamo forums, but since it seems you are no longer active there, I am posting it here now.

Below is a link to the issue (let me know if you want me to transfer it here rather than just provide a link and I will edit this)

https://forum.dynamobim.com/t/print-byview-no-view-selected-error/37991

I would appreciate if you could point me in the right direction if I am doing anything wrong.

**Comment by erfajo** [comment]
I will try it out... when I return from my summer vacation

**Comment by erfajo** [comment]
You have not returned on this issue, so I am going to close it...
