### ISSUE TITLE
Virus/Torjan

### ISSUE THREAD

**Issue by GitHulb** [erfajo/OrchidForDynamo#40]
### Win10
(e.g. Windows 7, Windows 10, etc)

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2019
Dynamo: 2.03
Orchid: 200

### What did you do? 
Try to download the Orchid Installer Package.

### What did you expect to see?
Not sure, but definitely not a Virus

### What did you see instead?
Virus
![Dynamo200](https://user-images.githubusercontent.com/54274620/63267025-7fb31500-c291-11e9-84a8-8d63a574d3c8.JPG)

**Comment by erfajo** [comment]
I dont know why this show up, I have not added anything in the installer. You can always download the content directly and install it by yourself if you dont trust it.
