### ISSUE TITLE
Parameter.Delete Node Warning

### ISSUE THREAD

**Issue by erknsahin** [erfajo/OrchidForDynamo#42]
Hello,

I tried to delete shared parameters both project parameters and family parameters. However parameter.delete node gave a warning that "Warning: Parameter.Delete operation failed. 
Value cannot be null. Parameter name: familyParameter"

I checked parameter.name node and it has string outputs.

I attached workspace image.

Can you help me to find out what is wrong?

### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2017
Dynamo: 2.0.2.6833
Orchid: 203.1.0.7125

![deletesharedparameter](https://user-images.githubusercontent.com/54661138/63919894-4ecca000-ca48-11e9-9d49-cfb4290eeea2.png)

**Comment by erfajo** [comment]
First, your write Revit 2017 and Dynamo 2.02, this might not be compliant. When I code for Dynamo 2.x (and 1.3.x) I do it against Revit 2018, and some of the nodes does only work with Revit 2019.
However, this should not affect family parameter nodes.

I have tried to see your image (there is no graph file), and it is very difficult to say anything from a graph without any data processed in the graph.
Could you include the needed files, and write which packages you use, I can see that some of them are not mine and not dynamo core nodes.
If you upload anything else than the accepted formats, then add an new extension to the file, e.g. xx.zip becomes xx.zip.txt

**Comment by erknsahin** [comment]
I also tried with Revit 2019 but it didn't work.

I am using Data-Shapes and Beaker packages. I wrote it on Dynamo file.

You can find dynamo file attached.
[delete shared param.v04.dyn.zip](https://github.com/erfajo/OrchidForDynamo/files/3589648/delete.shared.param.v04.dyn.zip)

**Comment by erfajo** [comment]
please also a processed image, so I can see the warnings

**Comment by erknsahin** [comment]
![error](https://user-images.githubusercontent.com/54661138/64622695-657fd900-d3f0-11e9-922e-0159795a0078.jpg)

You can see the warning above.

![Capture](https://user-images.githubusercontent.com/54661138/64622825-9829d180-d3f0-11e9-96e1-33124c8315c8.png)

Also, you can see the workspace above.

**Comment by erfajo** [comment]
Thanks, could you also show the watch node from "uniqueitems"? If they are not totally unique will it give an error.

**Comment by erknsahin** [comment]
![Capture](https://user-images.githubusercontent.com/54661138/64626117-00c77d00-d3f6-11e9-8543-64377a1e0c0a.png)

Sure, attached above.

**Comment by erfajo** [comment]
It looks like there is only one document... could I have this document, so I can test what could go wrong?

**Comment by erknsahin** [comment]
[demirkapi.zip](https://github.com/erfajo/OrchidForDynamo/files/3599861/demirkapi.zip)

I am using this revit file. Revit family file is in it. I am trying to delete parameters from structural column family.

**Comment by erknsahin** [comment]
[test model.zip](https://github.com/erfajo/OrchidForDynamo/files/3599879/test.model.zip)

I am using the attached file. Family file is in it. I am trying to delete from a structural column family.

**Comment by erfajo** [comment]
I tried to open the column, and i miss one parameter in the file... the first one on your list in the watch node. could you try to test again removing this one paramer and check what happens?
![image](https://user-images.githubusercontent.com/2844374/64700887-08475e80-d4a8-11e9-9f94-484f4ea5ffe9.png)

**Comment by erfajo** [comment]
and the fix for that is quite easy...
![Capture](https://user-images.githubusercontent.com/2844374/64712822-2d45cc80-d4bc-11e9-8a63-a22de523754b.png)
[testParameterDelete.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3601611/testParameterDelete.dyn.txt)

**Comment by erknsahin** [comment]
I tested it. You are right. The first parameter is missing and node give warning because it can't find the parameter. 

Thanks for your help! 👍 

However, can you understand why is it missing? Because the parameter list is coming from other nodes but from the same elements.

**Comment by erfajo** [comment]
Inside a project can you have shared parameters present, which not necessarily are present in the individual families... this is why you should work directly on the families instead of the project.
I have examples on working with opening families from inside projects, then work on the families, and reload them back again.
