### ISSUE TITLE
FamilyType.Delete

### ISSUE THREAD

**Issue by ingridhdezbenz** [erfajo/OrchidForDynamo#43]
### Revit, Dynamo and Orchid version
Revit: 19.2.0.65
Dynamo: 2.0.3.8811
Orchid: 203.1.1.7198

### The issue
**How to use the FamilyType.Delete node.**
What I’m doing is creating new Family Types and saving each one in a different .“rvt” File, so I want to create one and save it and then delete it so that when I do the new one and save it, it saves individually. Anyway, I tried using the node like this:
![image](https://user-images.githubusercontent.com/28742643/65161520-fd587500-da37-11e9-83a6-c83ebd25907c.png)
But it didn’t work, and I don’'t know if I’m using it wrong. And I thought that maybe it got lost in the element part so I tried to implement the node in my Custom Node where I create the Family Type and ended up with this:
![image](https://user-images.githubusercontent.com/28742643/65161556-0c3f2780-da38-11e9-9640-c5d4dde3764b.png)
But still it doesn’t work, so any ideas are very much appreciated, thanks!

**Comment by erfajo** [comment]
have you tried to see the object.type from the output port? are they as required?
your graph looks like you are sending the wrong types to the node...

have you seen my sample collection? try to download them and walk trough those who look like your problem.

**Comment by erfajo** [comment]
You have not returned on this issue, so I am closing it...
