### ISSUE TITLE
Orchid not installing properly/completely?

### ISSUE THREAD

**Issue by Tyree** [erfajo/OrchidForDynamo#45]
I am trying to install Orchid 2.0 for Dynamo 2.0.3. The package shows under Add-ons, but all it has under it is "About"

I have installed the proper version locally via the exe, but it still doesn't detect any nodes within the package.

We store all packages on a shared server. The package folder is there with bin, dyf, and extra subfolders.

Any idea what I'm missing?

Thanks!

**Comment by erfajo** [comment]
does it look like this in your folder containing Orchid?
the content which is in the flavor "Dynamo Revit" is the content which should be in your Orchid folder for Revit.
![image](https://user-images.githubusercontent.com/2844374/66982069-b5b81e00-f0b5-11e9-84c1-fd6a59975227.png)

which other packages have you on the server location?

**Comment by Tyree** [comment]
Turns out I had to download and then manually drag the contents of Dynamo Revit to our network packages location. What does the installer exe do, exactly? I gather it's not necessary if you're housing packages on the network?

**Comment by erfajo** [comment]
I have just figured that the files on Github is failing... my local files from the exact same build is working. I have no idea why the files is failing on github, so I will try to push my local files once more....

**Comment by erfajo** [comment]
I have uploaded a new build.
However, i did test downloading the repository and tried different ways to take files from the zip file. If i didn't unzip correctly, then the files failed over and over again. While unzipping correctly, then the files worked. They might have worked all along if I had done it correctly from the beginning.

**Comment by Tyree** [comment]
When I used 7 Zip to pull the files from the zip (before the re-upload), it worked fine dropping them into our shared packages folder. I just couldn't tell what the installation exe did. Is it supposed to put the files into the local packages folder?

**Comment by erfajo** [comment]
I know, I have also just dragged the files I needed when I have downloaded anything from Github, so I dont know what has changed, but something has changed...

Maybe is the problems comparative to this description...
https://github.com/DynamoDS/Dynamo/wiki/How-to-Utilize-Dynamo-Builds
