### ISSUE TITLE
Results of Parameter.GetValue

### ISSUE THREAD

**Issue by huvec** [erfajo/OrchidForDynamo#47]
Hi there,

The orchid package is extremely useful.
I have a quick question regarding the parameter.getvalue node from this package.
I have a graph that reads the family files from a folder. It get the files names and type names correctly but when it gets the description parameter value, it does not list it in the order of the family type. The order is random and changes each time a new session is runned.
The arrows in the image below shows the type name and description relation.

![image](https://user-images.githubusercontent.com/16100298/67633153-31656680-f911-11e9-8f36-26f13518ca06.png)

![image](https://user-images.githubusercontent.com/16100298/67633217-17785380-f912-11e9-8e88-423f1fc46501.png)

hope you can shed some light on this or let me know how i can have it sorted according to the family type.
thanks

**Comment by erfajo** [comment]
could you make a zipfile with the needed content for testing? it is very strange if it should shuffle the content, if the data is feed correct. The zipfile need maybe to be renamed to ".txt" to upload it... try to see what works.

**Comment by huvec** [comment]
Graph and a sample family below. I changed the zip to txt.  This is the family that is in the snapshot above. The shuffling happens with families with multiple types. 

To give you an idea on what I am doing, I have about 600 families that i am exporting info from to excel and then a new shared parameters and values inserted into them

[Graph and Family.txt](https://github.com/erfajo/OrchidForDynamo/files/3776317/Graph.and.Family.txt)
thanks for help

**Comment by erfajo** [comment]
I managed to find the error, there is new builds available, including some new nodes.
try to see the graph now, it includes also usage of my "replacement" node, so you can get a NA value where you have nulls.
[_Extract RFA Content _Orchid Package.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3791363/_Extract.RFA.Content._Orchid.Package.dyn.txt)

**Comment by huvec** [comment]
Thanks for that.
I tried it and noticed an normaly. It seems to drop "summarise" null items.

![image](https://user-images.githubusercontent.com/16100298/67921377-51946e80-fc0c-11e9-85dc-1e33d15fc913.png)

**Comment by erfajo** [comment]
could I have that file... I know there is issues with "default" family types. You can make a family from inside Revit which dont become a family type in the family. I am chasing these instances to learn how to treat them.

**Comment by huvec** [comment]
Sorry I was flat out recently and have not gotten back to you. I have not tried your new build yet  but will do.
In the mean time, I will expand out the issue. the parameter value I was extracting is description. The particular family had 2 types but no description in both the types. I would have thought it will leave a null value for each type.
