### ISSUE TITLE
Orchid Revit Tab not appearing on Install of Package Revit 2020

### ISSUE THREAD

**Issue by MattGaydon** [erfajo/OrchidForDynamo#48]
### Operating system
Window 10

### Revit and Dynamo version
Revit: 2020
Dynamo: 2.1
Orchid: 210

### What did you do? 
Tried to Install Orchid both though the exe and also via packages.
The package did not show up at all until i moved them into folders on level higher 
Original:Orchid_210/Dynamo Core
New: Orchid_210_Dynamo Core 
but this logic still does not give me the Revit components 

### What did you expect to see?
tabs for Core and Revit components under Orchid Tab

### What did you see instead?
Only Core Tab under Orchid Tab

**Comment by MattGaydon** [comment]
Keeping the new File Structure noted above, but removing the Orchid_210_Dynamo Core folder solved the issue in Revit, Tab now shows up. Though is i use your folder structure of having the Dynamo Revit folder in the Orchid folder it does not show up.  

Maybe its an idea to add suffix _Sandbox to the Core Folder name as my first though was both folders were need. Admittedly i had forget about sandbox even though i was only using it last month.

**Comment by erfajo** [comment]
Yes, you cannot have both version loaded at the same time... I will fix the text :-)
