### ISSUE TITLE
associate by matching parameter names family shared parameters

### ISSUE THREAD

**Issue by jmcouffin** [erfajo/OrchidForDynamo#49]
### Revit, Dynamo and Orchid version
Revit 2020.1
Dynamo 2.2.12.5291
Orchid Latest version  for 2.2 dynamo

### The issue
I am trying to associate multiple parameters by matching names from a host family to its nested one.
my graph looks like this
![test association paramètres_2019-11-05_09-36-09](https://user-images.githubusercontent.com/7872003/68244082-55f9c680-0014-11ea-952c-0f86b23f7cc8.png)

It does work as expected once you feed a family document (the current one) as a list. If the document is passed as a 'x' and not as a [x], it does not work properly (see the last bit of my graph @ the family document input)

### Solution
you need to feed it with all inputs as a list.

### Suggestion
let it take the input directly from the current faily document

**Comment by jmcouffin** [comment]
I forgot to thank you for your amazing work. very unique!

**Comment by erfajo** [comment]
first, I have a current document node!? I am not sure what the python driven node does... however, I am sure it is not the problem.

I have tried to see your graph image, and it is really difficult to say what could be the error. Could you please include the graph and the testfile for it? Github does not take dyn or rfa/rvt files, but you can zip it and rename the zip file including a ".txt" extension. then can I remove .txt and then is should be a xxx.zip file...

**Comment by jmcouffin** [comment]
[graphFamily.txt](https://github.com/erfajo/OrchidForDynamo/files/3811852/graphFamily.txt)
there you go.
from sleepless Zlin, cz

**Comment by erfajo** [comment]
First, sorry for being late, I have been busy.
Next, thanks a lot for reporting this bug, it was a silly bug I have made, and it was very easy to fix. I am so sorry for your inconvenience.
please download latest build (7274)
I have also correct smaller things in the graph...
[test association paramètres_erfajo.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3876502/test.association.parametres_erfajo.dyn.txt)

**Comment by jmcouffin** [comment]
no problem. you have a life ;p 
Thanks for fixing it.
