### ISSUE TITLE
FamilyDocument.SetParameterByName won't work

### ISSUE THREAD

**Issue by LuisaSG** [erfajo/OrchidForDynamo#5]
### Revit and Dynamo version
Revit 2017, Dynamo 1.3.3

### The issue
I tried to set the parameters of several families at once. The parameter was already included in the families' documents.
![image](https://user-images.githubusercontent.com/33966575/45674945-6b6d1200-bb2e-11e8-9d2f-58ea0289d504.png)

The families appeared to have been saved with their parameter's valued included. However, when entering the families, the parameter had not changed.

![image](https://user-images.githubusercontent.com/33966575/45675196-0960dc80-bb2f-11e8-866c-edba6ce2525a.png)

**Comment by erfajo** [comment]
Please always remember to hover the input ports to see which data type it takes. The family type must be feed as a string
![image](https://user-images.githubusercontent.com/2844374/45876796-07e81c00-bd9c-11e8-8338-2b4e58e1937e.png)
