### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by huvec** [erfajo/OrchidForDynamo#50]
Hi. 
I have installed Orchid from package manager to a custom location. Then I ran the installer.
I get this message.
![image](https://user-images.githubusercontent.com/16100298/69185610-f3f4a180-0b7b-11ea-83a9-d143e8b05ef7.png)

Can you help please?
I was also wondering why Orchid is not deployed through the package manager?

thanks

**Comment by erfajo** [comment]
I have teste downloading all the five executables, none of them failed. Besides, none of the four executables which hold the Orchid package has an option for custom location, it is only the sample collection which can be installed on a custom location. However, that installer contains nothing to be executed, it contains only samples!?

In other words I have no idea what your error is, but it is most likely some windows error or a corrupted download which is the error.
