### ISSUE TITLE
Dynamo 2.3 support with Revit 2020.2

### ISSUE THREAD

**Issue by Danifly80** [erfajo/OrchidForDynamo#51]
### Revit, Dynamo and Orchid version
Revit: 2020.2 (20.2.0.48)
Dynamo: 2.3.0.5885
Orchid: 220.0.0.7253

### The issue
Hi Erfajo, Hi All,
my question is about the support for dynamo 2.3 (included in Revit 2020.2), I tried to use Orchid 220 version but it doesn't work.
Is there a fast way by my side to use the orchid package in 2.3 or is it need rewrite of the code?

Thanks
Daniele

**Comment by erfajo** [comment]
I have not a build ready for Dynamo 2.3 yet... Since the 2.1 version is a recompiling with the proper assemblies needed. I will work on it, but cant answer how fast it will go. I will announce here in this tread when I have build the first 230 version.

**Comment by Danifly80** [comment]
> 
> 
> I have not a build ready for Dynamo 2.3 yet... Since the 2.1 version is a recompiling with the proper assemblies needed. I will work on it, but cant answer how fast it will go. I will announce here in this tread when I have build the first 230 version.

Thanks for your work!

**Comment by erfajo** [comment]
I have uploaded a Orchid 230 version now. please check it out :-)
