### ISSUE TITLE
Add/Create Shared parameter nodes  - value can vary by group instance / parameter description

### ISSUE THREAD

**Issue by Danifly80** [erfajo/OrchidForDynamo#52]
### Is your feature request related to a problem? Please describe.

1. Can't set the options "value can vary by group instance" for text type parameters and instance parameters with nodes "Parameter.CreateSharedParameter" and "Parameter.AddSharedParameter"

2. Can't set a description for a shared parameter using "Parameter.CreateSharedParameter" node.

### Describe the solution you'd like 

1.  can set "value can vary by group instance"

2. can set the description of the shared parametes

1.  a boolean to select "value can vary by group instance"

2. a string input to set the description of the shared parametes

### Describe alternatives you've considered 

I can't find any other way to solve the problem

### Additional context 

Hi Erfajo, 
Hi everyone,

I use the orchid pkg to Add or Create shared parameter with this two nodes:
nodes

![nodes](https://user-images.githubusercontent.com/58212360/69625080-23a51d00-1046-11ea-83a8-624356632831.jpeg)

I have no problem using them, with data from dynamo itself or importing from excel.

My questions/suggestion are essentially two;

**first one:**
    is there any way, in case the shared parameter is a text type parameter to select “value can vary by group istance” (see following image)

![value can vary by group istance](https://user-images.githubusercontent.com/58212360/69625414-cf4e6d00-1046-11ea-987d-10840e41d005.JPG)

**Second one:**
    when a new parameter is created with the node “Parameter.AddSharedParameter” is there the possibility to compile the description field?

![description](https://user-images.githubusercontent.com/58212360/69625521-0b81cd80-1047-11ea-8a6c-71686258726f.jpeg)

**Comment by erfajo** [comment]
It is doable to implement both ideas, I will see what can be done.

**Comment by Danifly80** [comment]
> 
> 
> It is doable to implement both ideas, I will see what can be done.

Thanks, They will help a lot!

**Comment by erfajo** [comment]
I have updated the parameter nodes...
![Parameter](https://user-images.githubusercontent.com/2844374/69673634-077f9b00-109b-11ea-8841-976ee5dfae7d.png)
[Parameter.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/3894057/Parameter.dyn.txt)
remove ".txt" to turn it into a graph file.
