### ISSUE TITLE
Exact Manual for Installation 

### ISSUE THREAD

**Issue by andreasdraxl** [erfajo/OrchidForDynamo#54]
### Revit, Dynamo and Orchid version

Revit: 2018.3, 2019.2, 2020.2
Dynamo: 1.3.4. / 2.0.3.
Orchid: latest version 

### The issue
Hello Users,

I tried severial times to install Orchid, with the build or coping folders, nothing worked, but my windows is completly damaged after that, I have Revit 2018,2019,2020, I use Dynamo Studio, 1.3.4., 2.0.3.

Is there in upcoming versions! a easier installation process, or directly from the package browser?

For me  I can`t use Orchid, it is to dangerous! 

Is there a problem when I have severial Dynamos and Revits?

I am glad about any advise

KR

Andreas

**Comment by erfajo** [comment]
I strongly doubt that your windows is damaged, the installer is the exact same as the one dynamo is shiped with... but you are always welcome to install it manually if you know how to handle it.

I am not going to change the installer, and i have several version of dynamo installed in parallel, with individual versions of orchid and some other version specific packages.
