### ISSUE TITLE
Formula.Get only returns one formula

### ISSUE THREAD

**Issue by Crapai** [erfajo/OrchidForDynamo#55]
Revit: 2020.2
Dynamo: 2.3
Orchid: 210.0.0.7072

I'm trying to copy formulas from a nested family into a host family. I'm opening the nested family and using Formula.Get and then closing the family. When I do this I get null results for all but one parameter and the error, "Warning: Formula.Get operation failed."

Here is a screenshot.
![FormulaGet01](https://user-images.githubusercontent.com/50451766/70811507-b3abcc00-1d93-11ea-82dc-e9ce97d4038a.PNG)

Here is the script. I've added a package stamp to it.
[Revit Dev - Family - Copy nested parameters to host.zip](https://github.com/erfajo/OrchidForDynamo/files/3961474/Revit.Dev.-.Family.-.Copy.nested.parameters.to.host.zip)

Thanks for any help.

**Comment by Crapai** [comment]
I'm about to leave work so I don't have much time to write this. I think it might be because I was only getting instant parameters. I'm getting instant and type now and I have more parameter's formulas. It still causes an error which I think are now just coming from the fact that some(most) parameters don't have formulas.

**Comment by erfajo** [comment]
It is very hard for me to say if your graph is working or not, it seems that you use many nodes I cant see the benefits of. If you could provide some testing files would it be good.
However, I can see that you could get rid of many of you nodes, you really don't need any other packages than what dynamo provides and mine, maybe you need MEPover if you want to extend your graph, but you should not end up using the other three you have mentioned on your graph.

**Comment by Crapai** [comment]
Thanks for your feedback. I think It is simply caused by the null values. I'm throwing every parameter in there and I think the node only works with parameters that have formulas. I've found another node that can work with all parameters whether they have formulas or not.

**Comment by erfajo** [comment]
You can feed it with any existing parameter, if it has no formula it will return "null". However, if you feed it with a parameter that not exist, then is it failing. But why feed it with a non existing parameter?

**Comment by Crapai** [comment]
I didn't think I was using non-existent parameters but perhaps one slipped in there somehow. I might try to look at it later just to make sure.
