### ISSUE TITLE
Setup Wrong Folder

### ISSUE THREAD

**Issue by Kaankrby** [erfajo/OrchidForDynamo#58]
### Operating system
win10
### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2019.3
Dynamo: 2,0,3
Orchid: 203.1.2

### What did you do? 
İnstalling orchid

### What did you expect to see?
installing.
### What did you see instead?
Not installed. 

The folder for the setup was Dynamo_Core and Dynamo_Revit with "_". (in roaming folder) 
But normally should be without "_".

After moving to the right folder its worked.

**Comment by erfajo** [comment]
please read more carefully what is written in the default page for this repository... doing that and you would know how to handle manual downloads.
