### ISSUE TITLE
Document.ImportImage

### ISSUE THREAD

**Issue by davidclark70** [erfajo/OrchidForDynamo#59]
Hi Erik, I am using Revit 2020 and Dynamo 2.3.0, I just installed Orchid for Dynamo 230 and I do not see the node Document.ImportImage that I used with Dynamo 2.0.2 to import images into the Revit image manager.
Did you get rid of this node?
Thanks

**Comment by erfajo** [comment]
It is still there... however, I have been moving/splitting "Document" into several functions. In that movement, have I not updated the icons... I have just updated that part for existing icons. I have still +100 functions that is missing a icon. It has become a rather big job to maintain my package :-)
