### ISSUE TITLE
FamilyTyper.GetNested - Object.ToDynamoElement Issue

### ISSUE THREAD

**Issue by vinpanasiti** [erfajo/OrchidForDynamo#6]
### Revit and Dynamo version
Revit 2019.1, Dynamo 1.3.3.4111

### The issue
I'm use the node FamilyType.GetNested to get the nested family from an .rfa file (get by Directory.ContentsAll node) and then convert to Dynamo Element

I expected to get a list of dynamo element family, but I got "null" values

![image](https://user-images.githubusercontent.com/10879979/45868804-fd6f5780-bd86-11e8-9a3c-bc78543172f0.png)

[MammaAnatroccolo.zip](https://github.com/erfajo/OrchidForDynamo/files/2411071/MammaAnatroccolo.zip)

**Comment by erfajo** [comment]
Please add the needed files fot testing this. The dynamo graph and one sample file.

**Comment by erfajo** [comment]
I have tried to use what you have included in your zip file, but I have no idea what it is you are doing. However, I have tried to change those nodes there seemed odd just by looking on your graph.

You need to include some testing files, and translate everything into English so I have a chance to understand what is written in the graph.

Below is the edited graph attached.
[MammaAnatroccolo.zip](https://github.com/erfajo/OrchidForDynamo/files/2427125/MammaAnatroccolo.zip)
