### ISSUE TITLE
Open file after Created

### ISSUE THREAD

**Issue by crturybury** [erfajo/OrchidForDynamo#60]
After using your File.NewProject is it possible to immediately(meaning right after the node) open that file and continue modifying it, such as adding sheets or linking in documents.

**Comment by erfajo** [comment]
Yes, that should be doable.
The "new" file is saved at the file path given. Therefore, you should be able to open it.

**Comment by crturybury** [comment]
What I am trying to do is create my MEPS files then link those in to the appropriate discipline(i.e. Mechanical and Electrical into Structural) an then pin them all in one execution of the Dynamo script.

![image](https://user-images.githubusercontent.com/15730565/71743331-e9d7eb00-2e29-11ea-9706-2ac73b14bb4f.png)

**Comment by erfajo** [comment]
Thanks for reporting this issue...
I can see that this method gives a problem, not that I can figure why... I will do my best to find a solution...

**Comment by crturybury** [comment]
Check out the package “LinkIt” it has the ability to pin at the time of linking.

**Comment by erfajo** [comment]
it is not that node which is the problem...

**Comment by erfajo** [comment]
I found the problem... I have uploaded a new version.
![LinkedDocument-pin_beta](https://user-images.githubusercontent.com/2844374/71835437-db9c0000-30b1-11ea-9c86-167f45c26ed3.png)

**Comment by crturybury** [comment]
I am having a difficult time installing. I noticed the installer places everything in "Dynamo_Revit" not "Dynamo Revt." Last time I copied and pasted the Orchid Folder from "Dynamo_Revit" into "Dynamo Revit" and it worked but not this time.

**Comment by crturybury** [comment]
I was able to get it installed and then I tried to run this script and received this warning. After opening the Revit file the link was in fact unpinned.

![image](https://user-images.githubusercontent.com/15730565/71853327-a0450580-30a0-11ea-8782-1559d1d513a1.png)

**Comment by erfajo** [comment]
ahhh... yes, that will give pin/unpin a problem
so solving one thing opens for another... I will fix asap.
I need to make a new pin/unpin node that takes both a document and element as input

**Comment by crturybury** [comment]
I really appreciate you being so willing to help.

**Comment by erfajo** [comment]
I have uploaded a new build, with two new pin/unpin nodes
![LinkedDocument-pin_beta](https://user-images.githubusercontent.com/2844374/71857823-3d2b9100-30e9-11ea-8848-03eaebe70d82.png)

**Comment by crturybury** [comment]
Am I doing something wrong? Do I need to assemble my node graph differently?

![image](https://user-images.githubusercontent.com/15730565/71905410-b5b44100-312d-11ea-932e-c02b7e951340.png)

**Comment by crturybury** [comment]
I tried this.
![image](https://user-images.githubusercontent.com/15730565/71905822-881bc780-312e-11ea-9890-98d02882b3af.png)

**Comment by erfajo** [comment]
no that should be it... I will try to replicate your situation and test why you end up in problems, I figure that it still is a transaction problem that occur

**Comment by crturybury** [comment]
Let me know if I need to send you anything to help out.

**Comment by erfajo** [comment]
It didn't prove to be that difficult to solve that problem... new builds available.
![LinkedDocument-pin](https://user-images.githubusercontent.com/2844374/71930055-2e9db200-319b-11ea-8848-d4b99742cc25.png)

**Comment by crturybury** [comment]
This works! Thank you so much for your help. Does your Orchid Pack do anything with coordinates such as acquire/publish?  Also I have been looking for a way to Copy/Monitor Levels and Grids. Any guidance on that process?

**Comment by erfajo** [comment]
I have not build any of this, but sound like good ideas.
I am working on icons at the moment, but also curtain wall panel elements. I have made five new nodes which will be released later today.

**Comment by crturybury** [comment]
How many Revit files can be opened in the background?

**Comment by erfajo** [comment]
depends on your computer and ram

**Comment by erfajo** [comment]
I have worked on this copy/monitor idea, and this is not doable as such, since the Revit API dont support this. It seems to be so, that it is only the Revit team who can do this. However, I managed to find a solution for copying elements from a linked document and put it into the same position int the target document...
This is what I can do for now, until we get a better API from the Revit team.

**Comment by crturybury** [comment]
Thanks for looking into this for me. I am not a developer and REALLY REALLY REALLY appreciate your help. You have really helped my pipeline. One more question. Is there a way to change the path of links that are already within the model?

**Comment by erfajo** [comment]
I have had a node for this some while... look for link nodes -> Link.LinkRepath
however, now where I think about it, it should only be named Link.Repath

**Comment by crturybury** [comment]
Can this work with opened documents in the background?

**Comment by erfajo** [comment]
Theoretically yes... there is no reference to any document when reloading a link. However, how it will work in real life demands a test. If you test it, could you then please inform me of the result?

**Comment by crturybury** [comment]
I will test it

**Comment by crturybury** [comment]
I don't know where to go from here. The "Linked Revit Files" node stays empty becuase there is no file actually open Revit. It needs to read the file that is open in the background. Also the "LinkRepath" node might need a doucment input so it know what file it is repathing in side of.

![image](https://user-images.githubusercontent.com/15730565/74044129-31edae80-4990-11ea-82f6-27ce0df50d40.png)

**Comment by erfajo** [comment]
i would go for this option
![LinkRepath](https://user-images.githubusercontent.com/2844374/74087091-845ec600-4a89-11ea-9229-0a97c56f0a5d.png)
[LinkRepath.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4174405/LinkRepath.dyn.txt)

I tried it, but got some warning, so I could not see if it worked or not... I am working on something else, so I will return to this later, however, you could also try it out.
