### ISSUE TITLE
Create Shared Parameter in Family

### ISSUE THREAD

**Issue by Kynikx** [erfajo/OrchidForDynamo#61]
Revit: 2020.2
Dynamo: latest build
Orchid: latest build

I have a sample graph i am using but it is old and used the DanEDU nodes, but the graph was simple and i understood most of what it was doing... I tried to recreate it using the newest package but the CreateSharedParameter node has been changed and i do not understand how to integrate the change to accomplish the same result.
![OLD_AddShParametertoFamily](https://user-images.githubusercontent.com/59623668/72018349-7b35cb80-3235-11ea-8c0f-1a415b734f76.png)

The output of the new Parameter.CreateSharedParameter node is Parameter and not Document. What does this change as far as the next step is concerned? the previous graph took the Document output and passed it to the Document.Close node. What should come between the CreateSharedParameter node and the Document.Close node that will provide appropriate information?

![Current_AddShParamtoFamily](https://user-images.githubusercontent.com/59623668/72018387-8983e780-3235-11ea-9d59-6fe5cfe5e8bc.png)

**Comment by erfajo** [comment]
try to see my sample collection, here is some examples on parameters... however, if you in generel need to wait for some output to be processed, then use the "Await" node. There is also example on how to do that.

**Comment by Kynikx** [comment]
I have reviewed your sample collection and i don't see what i require. 
i don't think i am waiting for output to be processed... i need to know what to do with the Parameter output that doesn't work for the Document.Close node. 

![documenterror](https://user-images.githubusercontent.com/59623668/72019979-bd144100-3238-11ea-93c3-50d735cd94fc.png)

**Comment by Kynikx** [comment]
OK, forgive me. i realized the Await node and i have it working for a single file. i will try for all the files in the directory next.

**Comment by erfajo** [comment]
remember list lacing... and you can feed one node with list values, if you use list level...
If you add the graph file (rename it by adding ".txt") here, then is it more easy to help you...

**Comment by Kynikx** [comment]
[Add Share Parameter - Multi .dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4042166/Add.Share.Parameter.-.Multi.dyn.txt)

**Comment by Kynikx** [comment]
I have tried various lacing combinations... cross-product (on AddSharedParameter node) means the run does not end and i have to restart Revit. 
I am definitely missing something with the list level. i'm looking into how to use it in this case...

**Comment by erfajo** [comment]
I noticed in the graph file that you are trying to feed several parameter groups. That is not doable!
It takes several parameters, but only one group at the time... this goes also for the other setting one or more parameters must be setup with! try to see what the nodes takes as a input -> string and string[] is not the same.
The other things in the graph looks fine.

**Comment by erfajo** [comment]
You have not returned on this issue, so I am going to close it...

**Comment by Kynikx** [comment]
Oh! I have not solved it but I have other things going on, so I cannot spend all my time fixing Dynamo problems!
