### ISSUE TITLE
Associate multiple global parameters to parameters

### ISSUE THREAD

**Issue by MarkAckerley** [erfajo/OrchidForDynamo#62]
Hi Eric,

I hope you are well, thank you again for all your work on Orchid.

Forgive me if I've missed this in your samples or am making a basic error...

I wish to associate multiple type parameters to multiple global parameters for all types of a family.

Revit: 2019.2.2
Dynamo: 2.03
Orchid: 2024.4.2.7024

Please see attached simplified test files:
[Associate Global Params to Element Params.zip](https://github.com/erfajo/OrchidForDynamo/files/4052899/Associate.Global.Params.to.Element.Params.zip)

I have a family with 40 types.
The family type contains 2 parameters.
The project contains 2 global parameters.

I can associate 1 type parameter to 1 global parameter for all family types.

I can't associate 2 type parameters to 2 global parameters to all family types

The only way I can get it to work is if I daisy chain the associate parameter nodes together...

![Capture](https://user-images.githubusercontent.com/41670424/72246295-4c7b7480-35ea-11ea-94c2-5c7aae585a11.png)

This works, but not ideal if I have 20 parameters to associate :)

I have played around with all the variations of list structure, levels and lacings I could think of, but couldn't get it to work.

Any assistance would be great, thank you!

Mark

**Comment by erfajo** [comment]
Hi Mark,
Just as a quick feedback... You should be able to feed the node with lists, just remember that the two lists should be same length and paired in the same order.
The way nodes are designed after version 1.3.something, is pretty smart. You dont need to make the looping for lists anymore. You just code the "base case" and then is the rest up to the user, how they send the elements, by using lacing and/or list level. It saves a lot of work for the coders :-)

I can take a look at your graph later :-)

...and you are welcome, I enjoy coding and my package has passed 500 nodes and are still growing :-)

**Comment by erfajo** [comment]
Hi Mark,
It seems like you went over the river after water.
![Capture](https://user-images.githubusercontent.com/2844374/72666323-42ee7400-3a11-11ea-95f8-515bca4ef1b3.png)
[Associate Global Params to Element Params.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4080894/Associate.Global.Params.to.Element.Params.dyn.txt)

**Comment by MarkAckerley** [comment]
Hi Eric,

Thanks for looking for me, yes my actual graph has a re-order part :)

Unfortunately, that doesn't seem to work for me?  Though the node returns as if it is?

![image](https://user-images.githubusercontent.com/41670424/72677160-62c57c80-3a91-11ea-93ec-5ac46ac7cbb2.png)


Cheers,

Mark

**Comment by erfajo** [comment]
did you use my graph? i noticed you send the wrong types to the node in your graph... you mixed up string and element types.

**Comment by MarkAckerley** [comment]
Hi Eric, 

You are right, and my levels were wrong and I updated my package to the current version and it runs now!

Thank you for your patience.

Mark

**Comment by erfajo** [comment]
sounds good... so you have seen I have made new layout on my icons, I had to do something that was fixing I am missing +200 icons!? :-S

**Comment by MarkAckerley** [comment]
Sounds painful :(  Perhaps you need a node to auto-create icons! :)

**Comment by erfajo** [comment]
that is more or less what I have done :-)
