### ISSUE TITLE
BulkUpgrade Sample - Add Shared Parameter Fails

### ISSUE THREAD

**Issue by Shatner86** [erfajo/OrchidForDynamo#63]
Revit: 2019.2.1
Dynamo: 2.0.3.8811
Orchid: 203.1.2.7313

-------------------------------------------------------------------------------------------------------------

Hi @erfajo ,

Massive thanks for the update in December(?). This has allowed me to use your package (as previously it was only giving me the readme node.)

I'm having issues with the 'Parameter.AddSharedParameter' node when using your sample file called "BulkUpgrade.dyn". My question is to the values supplied in your code block that links to this node.

In your example, you have "Sheet & Project" as the parameter group value but stated that its because you "use a tab in my SP Parameter group" names", do you mean you create groups? Using my own as a reference I have three: "Dimensions", "Identity Data" and "Exported Parameters"

So i believe this is what i need to input here.

PG i believe is Parameter Group, so I have used nodes and found the parameter group i want is "PG_TEXT"

See below for my Shared Parameter information:

[
![image](https://user-images.githubusercontent.com/58949329/72347221-8a9e9400-36cf-11ea-93e0-eca68f252f02.png)
](url)

![image](https://user-images.githubusercontent.com/58949329/72352414-1e755d80-36da-11ea-9af5-45c9eeca8d6f.png)

Finally, my inputted information into the node:

![image](https://user-images.githubusercontent.com/58949329/72352492-41a00d00-36da-11ea-9b7d-f5d640f2e7ad.png)

The document (or family) path is working fine as the families are being opened and closed (R17 to R19). I just can't seem to figure out why the shared parameter come in as well.

Any idea what I'm doing wrong?

Many thanks,
Ben

**Comment by erfajo** [comment]
"Exported Parameters" is not the same as "Exporting Parameters"... please check spelling

**Comment by Shatner86** [comment]
![image](https://user-images.githubusercontent.com/58949329/72359490-48cd1800-36e6-11ea-98cb-51d3c81430c4.png)

i am both happy that it works and yet, disappointed in myself. 
Sorry to have wasted your time.

Thanks!
