### ISSUE TITLE
Document.Current Creates New Family Type

### ISSUE THREAD

**Issue by Crapai** [erfajo/OrchidForDynamo#64]
Noticed I had difficulty setting a formula because it was dividing by 0 in one of my types. I didn't set the value in one type because it was created by this node and not collected to the set value node.

What I've done to get around it is setup a get current family type after it, delete that type after other types are added to the family. This script always runs on a fresh family.

I'm guessing based on previous things you've posted an a lot of the tooltips for your nodes that creating this family type when none exist is important to get the node to work.

I think your typical "If no family type exists..." note should be added to the tooltip so people can keep it in mind when creating scripts, sorry graphs. 😛

**Comment by erfajo** [comment]
could you share this graph and maybe some sample files?

Could be interesting to see if the error is something I should take into consideration or it is one the users half. I am not aware if any other packages takes division by zero into consideration!?

**Comment by Crapai** [comment]
I don't think the issue is something that needs to be taken into consideration with your package because it is something within Revit it's self wont allow. I've manually done this before as well. 

Example:
I have three types in a family. I set the power factor of one type from 0 to 1. I then use the power factor parameter in a formula for another parameter. Since power factor is still set the default 0 value for the other two types, it will create a warning and not allow me to create that formula. I have to switch over to the other two types and change the power factor and then create the formula.

I firmly believe it is user error. I need to be careful that parameters have valid values for each type or to remove types I'm not going to use. This is why I suggested more documentation for the Document.Current node. I was very careful to use wait nodes for everything that was documented as adding default types and connecting the wait part to the output of my create type node. It took me a while to find out that Document.Current was creating it. Since the Document.Current is needed in for the script to run I need to accept that I will have the default type and then delete it afterwards.

**Comment by erfajo** [comment]
Current.Document does not create a new document!?
that node do only one thing, and that is instantiate a dynamo document... it is a single line of code. Notice that "new" is not the same as creating a new document! So if something is wrong, is it the way dynamo should initiate a document, and I do believe this would be a much greater problem if this was the case.

`public static Document Current => new Document(DocumentManager.Instance.CurrentDBDocument);`

**Comment by Crapai** [comment]
I think it is creating a new type not a new document.

**Comment by Crapai** [comment]
Ok, I think I figured out what was actually creating the type. I thought it was the currrent.document because a watch node I used appeared to show it creating a type, but it actually isn't. I narrowed it down to FamilyType.Create. As you can see below it doesn't have Family1 as an output but it is created in Revit. I'm providing names for the types so shouldn't it not create a default type?

![family types created](https://user-images.githubusercontent.com/50451766/72807130-b5836d80-3c24-11ea-8b44-1f45675bbbf0.PNG)
![FamilyTypeCreate issue](https://user-images.githubusercontent.com/50451766/72807131-b5836d80-3c24-11ea-8ce2-2b9086a89c5a.PNG)

**Comment by erfajo** [comment]
Family Create will create a family type with the same name as the family itself. I need to do this, since this is what Revit do on the fly in the background in the current session. however, I do not have this option, I must have a family type with a name to be able to work on it.

This is an "error" that came when Revit made it possible to name the default family type occurrence of a family with the same name as the family itself. When you do this inside a project, and then opens the family for editing, then will the type name be grayed out. inside the family edition can you then do whatever you need, but only manually. if a type do not exist, then I cant do anything in connection to types. Formula demands types.

the watched output from document create is only giving the document name (which also is the family name), it does not give the type name. however, it might be the same name the type has due to if the only occurrence of a type is the same name as the family.

the code for the watched return message is...
`return string.Format("Family Document: {0}", InternalDocument.Title);`

however, I will try to test if returning the title actually should create a type, then this is a bug I should address, I will return to you when I know some more....

thanks for reporting this

**Comment by Crapai** [comment]
The Document.Current is definitely not creating a type. I get that now. This issue is that FamilyType.Create is creating the type with the family name even if it is provided with names. My understanding from the tooltip below is that if names are provided it shouldn't create the same-name type.

![create type tooltip](https://user-images.githubusercontent.com/50451766/72826977-e7f29200-3c47-11ea-98ed-343eaa33fcc3.PNG)

**Comment by erfajo** [comment]
there is a bug... I have tested it now. this is surely something I need to fix.

thanks a lot for bringing this up.!

**Comment by erfajo** [comment]
really... when I updated the code last time, I commented an if statement out to optimize the code, and forgot all about it. unfortunately my unit testing did not include the situation like the one you have described. I definitely need to include this in my unittesting.

how fast do you need this, can I build new versions later today or can you give me some days? I am working on nodes for phasing at the moment...

I am so sorry for this rookie error

**Comment by Crapai** [comment]
I have a workaround to delete that type right now so it is not a pressing issue for me. Whenever you have time to get to it is fine by me.

**Comment by erfajo** [comment]
I actually had to do some recoding... but it made the code even more efficient, so it was a win win :-)
I will inform you here when I release next time...

and please... scripts is not what we do, scripting is very limited technology. Building graphs and working with graph technologies is a very modern way to traverse data and one of the most important research area in computation and math. Scripting is several decades old and not that smart in an overall consideration.
.Net and Python is both class driven languages,much smarter than javascript and comparable scripting languages. working in graphs is a flexible way to work with object orientated functions, where the way you form you graph will have an impact on the computation. moving nodes in the graph may have an impact. If it was scripting, then you would be very limited what you could do.

**Comment by Crapai** [comment]
To be 100% honest I'm just trolling you at this point with the script term. lol

**Comment by erfajo** [comment]
I have uploaded version 7329, this includes the fix on this error. This version includes also some new features that I have planned to write something about on my blog, however, some work-related issues came across my desk and took all my time this week and this will continue next week... but at some point will I describe what the new nodes can do especially for real estate and FM handling.

**Comment by Crapai** [comment]
Thanks for the work.
