### ISSUE TITLE
Print Zoom FitToPage

### ISSUE THREAD

**Issue by MarkAckerley** [erfajo/OrchidForDynamo#65]
Hi Eric,

Me again I'm afraid, I was trying to create print settings and make use of the ability to set a zoom to fit, but it doesn't seem to be working for me...

It's probably my fault! See below...

EDIT:  I noticed that zoom to fit is dependent on the paper placement being centered... if i set that it works!

EDIT EDIT: Hmm... it's not seeming to work in a list? see my WIP,,, 
[Create Print Settings.zip](https://github.com/erfajo/OrchidForDynamo/files/4090584/Create.Print.Settings.zip)

Cheers,

Mark

Windows10

Revit: 2019.2.2
Dynamo: 2.0.3
Orchid: 203.1.2.7323

### What did you do? 
Created Print Settings

### What did you expect to see?
Setting would be FitToPage

### What did you see instead?
Setting was Zoom

![image](https://user-images.githubusercontent.com/41670424/72796017-82e27080-3c36-11ea-9cc5-9e504b630e45.png)

**Comment by erfajo** [comment]
I will try it out...
I have noticed that different printer drivers behave differently. ex. Adobe PDF need to be set in the driver if it automatically should print to files!? this is not the issue if you use Microsoft PDF printer. And now have Autodesk also started to add a PDF printer shipped with Revit... so yet another option for printerdriver. however, a printerdriver that will be more used over time.

**Comment by MarkAckerley** [comment]
Yeah it seems a bit of a minefield :( I presume it’s all about the sequence of transactions? I noticed that each print setting is a separate one...

I also found an odd thing where (Pdf Creator and my other pdf writers) couldn’t use the A0 size... I manually remade them with A0 and they were fine. The old node made them fine...

Thanks for your time :)

Mark

**Comment by erfajo** [comment]
Hi Mark,

I have not forgotten you, but I have chosen to try to code my own "printer". there is simply to many pitfalls with using the printers like they are used from inside Revit. It seems to be a dead end, and therefore did I research if it was doable to make my own. It seems doable so I have started to see if I can succeed to do something.

**Comment by MarkAckerley** [comment]
You are a crazy guy ;)

**Comment by erfajo** [comment]
Hi Mark,
I have fixed the issue, but I have not solved to build my own printer.
The way the Revit team has build the api for printing is troublesome. it does not allow orinting to anything else than virtuel printers, if it supported the system api for creating pdf documents would it have been easy. Why they have done as they have must be some very old and outdated way of thinking printing...
the only way to sole it is by writing new paper formats to existing printers users have, this could be the Microsoft pdf printer there is shipped with windows 10, so i am considering to do this even it is a shitty way to do it.

**Comment by MarkAckerley** [comment]
Thanks Eric
