### ISSUE TITLE
How to use Orchid to update Type based parameters across multiple Revit families where each Parameter Value is unique 

### ISSUE THREAD

**Issue by thebimman** [erfajo/OrchidForDynamo#66]
### Revit, Dynamo and Orchid version
Revit: 19.2.20.24 : 20190808_0900(x64) : 2019.2.2
Dynamo: Core: 2.0.3.8810 Revit: 2.0.3.8811
Orchid: 203.1.2.7346

### The issue
Firstly, thank you for such an awesome package.

However, I have an issue when trying to update the Parameter Values across multiple Revit family files. I can get the script to work using your example for updating a single Parameter with the same Value across multiple files. Brilliant.

But, when I try to update the same Parameter with multiple Values, one value for each different family Type within each family. Please note there could be a different number of family Types within each family in the selected directly it doesn’t work.

I assume this is because the list lengths are not aligned and therefore the specific nodes don’t know how to handle the 1 -> Many relationships of the above sequence.

I have tried using a Count and List.OfRepeatedItem node to create a list of Revit family documents that match the same format as the family Types list and write the data into the Parameters based on this structure but alas with no success.

Can you please provide me with some simple guidance on how to achieve what I’m trying to accomplish?

Kind regards

J
[Update_RVT_Families.zip](https://github.com/erfajo/OrchidForDynamo/files/4242820/Update_RVT_Families.zip)

**Comment by erfajo** [comment]
I will take a look at it when I have some time, but have you seen this sample?
OrchidForDynamo/Samples/Dynamo_2.x.x/Families/SetGet.dyn

**Comment by thebimman** [comment]
Yes, that was the example I followed. It works great for applying the same parameter value to all Types within multiple Revit families. Unfortunately I’m wanting to write different values to the same parameter for each of the different family types within each family.

**Comment by thebimman** [comment]
Let me know if you’d like some sample families.

**Comment by erfajo** [comment]
My nodes support list level, but you need to organize your data somehow in nD list structure that applies to the way you feed the node. It cannot take data in a random order.

**Comment by thebimman** [comment]
Thanks for the tips. I added some additional nodes to create the data structures (hopefully I'm on the right track) and by using the levels seem close to a working solution.

However, I'm still stuck on why I can't get the data to copy correctly to all families, it seems to work correctly for the first family in the list but when proceeding to the next family the script copies the last parameter value to all family types within that family. I'm not sure why it appears to be working for the first one and not the remaining families in the list.

Any guidance you can provide would be greatly appreciated.

![Orchid Snippet](https://user-images.githubusercontent.com/10429157/75184184-de110100-57a8-11ea-90ac-fee1bed74f78.jpg)

[Orchid_Example.zip](https://github.com/erfajo/OrchidForDynamo/files/4246422/Orchid_Example.zip)

**Comment by thebimman** [comment]
#crackedit
![Orchid Snippet - Solved](https://user-images.githubusercontent.com/10429157/75188858-d9047f80-57b1-11ea-90e2-797374be763c.jpg)

**Comment by erfajo** [comment]
I did test your first attempt and it worked as expected, however, with some ramdom families of my own.
![Update_RVT_Families](https://user-images.githubusercontent.com/2844374/75222823-570e5980-57a5-11ea-92eb-c88203dd56a8.png)
I will test your next graph as well.
