### ISSUE TITLE
Update Package Online

### ISSUE THREAD

**Issue by chuong9x** [erfajo/OrchidForDynamo#68]
### The issue
Can you tell me why you don't publish the updated versions to the dynamo package online?

**Comment by erfajo** [comment]
The Dynamo way simply doesn't support the way I wanted to publish my package. I choose to do it using Github along with Lunchbox and others who skipped the website for packages. The Dynamo team didn't listen to my and other's arguments in this matter like they have not done it in several other matters.

The way the team is acting is keeping raising issues I simply don't want to be a part of. This is why I also don’t use the community website, it is put in the hands of regulars which behavior I cant accept.
At the moment am I witnessing that the Dynamo team is working on a total copy of my package, so I am considering what to do, I have several options but it will add even more blurry conditions to this environment.

Everyone knows that Autodesk is a giant that chokes those they perceive as competitors or purchase them. They tried to stifle IFC, but they failed. Now that Rhino is also appearing on the scene, Autodesk is on to something totally stupid. I could easily switch to Rhino or something completely new if they don’t start behaving.

**Comment by chuong9x** [comment]
Thanks for describing the details with me. And I will also do the same thing as you
