### ISSUE TITLE
Orchid_Objcet.XYZ Node been removed?

### ISSUE THREAD

**Issue by DurmusCesur** [erfajo/OrchidForDynamo#71]
### Revit, Dynamo and Orchid version
Revit: 2020,2
Dynamo: 2.3.0.58..
Orchid: 2.3.0 (Revit)

### The issue
Hi,

I'm not using the "Orchid_Object.XYZ" node that I used in the versions you've posted before, and you've probably removed this node in the new version. I was using this node to use the points I set in the revit (Point XYZ) clean ly in python code.

Here's an example:
![9d80056a4e8abeb27c0c123e64ba95027979b97c](https://user-images.githubusercontent.com/24898802/79045203-27f36080-7c0a-11ea-9712-e2e240ff988c.png)

I tried to do something similar, but I can only create a "String" but I can't change it to "Int" because I have to use "," and unfortunately I don't know too much coding, so I can't move forward. (ToPoint(), ToXYZ(), ToRevitType() added, but the result has not changed again.

I share code and chart with you. 
![1](https://user-images.githubusercontent.com/24898802/79045437-676e7c80-7c0b-11ea-865d-b1c725e0e2a8.png)
Node in the previous version but not now:
![2](https://user-images.githubusercontent.com/24898802/79045546-f9768500-7c0b-11ea-8ffd-5b2301a425dc.png)

```
# Copyright(c) 2019, Durmus Cesur
# DC_Package

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

grouptype = UnwrapElement(IN[0])
location = UnwrapElement(IN[1])
a = []

TransactionManager.Instance.EnsureInTransaction(doc)

for l in location:
	
	groups = doc.Create.PlaceGroup(l,grouptype)
	a.append(groups.ToDSType(True))
TransactionManager.Instance.TransactionTaskDone()

OUT = a
```
Durmus

**Comment by erfajo** [comment]
Yes I have removed that node since there was no need for it. You should be able to use the OOTB nodes for vector or point instead. I have started to use those myself instead.
