### ISSUE TITLE
Add Shared Parameters to Multiple Families

### ISSUE THREAD

**Issue by azman28** [erfajo/OrchidForDynamo#72]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2020.2.1
Dynamo: 2.3.0.7661
Orchid: 230.0.1.7364
### The issue
The list of parameters from the code block seems fine. Issue arises after the list pass through
the Parameter.AddSharedParameter which returns null in the list. (See attached image)
![Shared Parameters](https://user-images.githubusercontent.com/63569679/79088608-b0424480-7d75-11ea-9d1f-fc5a6ea5845f.png)

![family parameter](https://user-images.githubusercontent.com/63569679/79088839-7b82bd00-7d76-11ea-9f23-f7539789ee77.jpg)

As a result. the identity data parameter failed to be populated in the revit families.
![Add Shared Parameters](https://user-images.githubusercontent.com/63569679/79088796-4f673c00-7d76-11ea-8d57-420e9420412b.jpg)

**Comment by erfajo** [comment]
Among others are you misusing list level... if you want help you need to provide a proper zip file with the bare minimum needed for getting to the graph working. Add ".txt" to the zip file so you can upload it here.

**Comment by azman28** [comment]
> Among others are you misusing list level... if you want help you need to provide a proper zip file with the bare minimum needed for getting to the graph working. Add ".txt" to the zip file so you can upload it here.

[Shared Parameter_Family_Door.rar.txt](https://github.com/erfajo/OrchidForDynamo/files/4479010/Shared.Parameter_Family_Door.rar.txt)

Thanks in advance.

**Comment by erfajo** [comment]
did you solve the error since you closed the issue?

**Comment by azman28** [comment]
Sorry that I've accidentally pressed the wrong button. I've not yet
solve the error and still hope for your assistance

Thank you.

Regards,
Noor Azman

**Comment by erfajo** [comment]
try this
![Multiple Family Shared Parameters](https://user-images.githubusercontent.com/2844374/79353571-85a1e880-7f3b-11ea-91bc-8dd1fc76484f.png)
[Multiple Family Shared Parameters.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4482007/Multiple.Family.Shared.Parameters.dyn.txt)

**Comment by azman28** [comment]
This one does the job. Thank you so much for the assistance

**Comment by azman28** [comment]
This one does the job. Thank you so much for the assistance.

Regards,
Noor Azman

**Comment by erfajo** [comment]
you are welcome. I hope you learnt something about list level, and that using lacing is not really doable in combination with list level.

**Comment by azman28** [comment]
Noted. Thank you
