### ISSUE TITLE
Add Shared Parameter to a single family

### ISSUE THREAD

**Issue by azman28** [erfajo/OrchidForDynamo#73]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2020.2.1
Dynamo: 2.3.0.7661
Orchid: 230.0.1.7364

### The issue

I'm having an issue adding shared parameter to a single family. There is an error indicating a few parameters having error of failed operatio. However, in the family document, these parameters are indeed populated. Need your assistance on what went wrong. 

![Add shared parameter to a single family document](https://user-images.githubusercontent.com/63569679/79531078-d3396500-80a3-11ea-8200-cfff51f1d05b.png)

![Family Type Parameter](https://user-images.githubusercontent.com/63569679/79531113-f06e3380-80a3-11ea-9807-2436ad02fe1d.jpg)

[Set.Family.Shared.Parameters.rar.txt](https://github.com/erfajo/OrchidForDynamo/files/4490787/Set.Family.Shared.Parameters.rar.txt)

[Shared Parameters_NAA.rar.txt](https://github.com/erfajo/OrchidForDynamo/files/4490846/Shared.Parameters_NAA.rar.txt)

Thank you.

Regards,
Noor Azman

**Comment by erfajo** [comment]
Hi again, you need to get your head around how to collect data you feed the nodes with, especially try to learn how to use list level and lacing. Start doing the basic courses on dynamo.

**Comment by azman28** [comment]
Sorry about that. I knew about it just i totally missed that part. It works
now. Sorry for any inconveniences.
