### ISSUE TITLE
Family Parameter Properties

### ISSUE THREAD

**Issue by JustinStirling** [erfajo/OrchidForDynamo#74]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2019.2.2
Dynamo: 2.0.3.8810  // Dynamo Revit 2.0.3.8811
Orchid: 203.1.2.7364

### The issue
Are there any known issues with using the Orchid package with the Clockwork package?  Specifically I'm trying to feed the Orchid 'Parameter.Parameters' node into the Clockwork 'FamilyParameter.Properties'.  The results are only "null".

![image](https://user-images.githubusercontent.com/63482166/79679336-2c53e680-81d3-11ea-8002-d315c9926140.png)

**Comment by erfajo** [comment]
You cannot combine nodes who cant translate the input. As the case is with the dynamo nodes, I have made internal classes to handle i.e. parameters and other issues not handled by dynamo.
I have a node who can get the parameter values, So I cant see what the purpose is for the clockwork node, but try to describe what this node can do that isnt covered in advance. Then will I take a look at it.

**Comment by JustinStirling** [comment]
OK, I took a different approach, of trying to rename the shared family parameters, but it's only renaming a fraction of them.

![image](https://user-images.githubusercontent.com/63482166/79691089-8da7a400-822b-11ea-823d-d36f8ee932e9.png)

Any suggestions on what I'm currently doing wrong?

**Comment by erfajo** [comment]
renaming a shared parameter node!? that should not be doable at all.
only family parameters and project parameters should be doable to rename.
You can only do the same with the api as you can inside Revit...

**Comment by JustinStirling** [comment]
Okay, I think I understand now...your "Parameter.Rename" node is only renaming parameters that are NOT shared?  All of the 'false' results I'm getting must be because they are shared family parameters.  Am I correct?

I was confused on the naming of the node and possibly misunderstood something else I read on the forum as well.

Therefore, the method I must use then is the one I read you post about previously on the forum a while back?!?...

"_Create a new SP parameter, named correctly. Get the values form the “old” parameter, put it on the “new” parameter, and then you are good to go. It can be done using my orchid nodes for families, and for projects use the OOTB nodes._"

https://forum.dynamobim.com/t/renaming-shared-parameters/21936/19


The reason for my inquiries:
I’m developing a startup MEP template. I’ve been given a lot families and schedules with shared parameters I would like to keep intact, however I’d like to add a prefix to them for my company.

In my mind I think I’m getting my point across right, but maybe I’m just way off on the entire topic.

**Comment by erfajo** [comment]
There is no options for renaming shared parameters, you cant do that inside Revit and we cant code anything there can do it... noone can do that... this is just how it is.
What you can do, is changing a family shared parameter to a family parameter, and then you can rename. however, then it is not a shared parameter anymore!?

In a project we actually dont even have this option, since the api doesnt cover any other options than creating shared parameters. Meaning a project parameter is actually a shared parameter created outside your shared parameter file... but still as a shared parameter.

If you need to rename a shared parameter, then is there no other option than to work on the shared parameter file, creating new parameters and then move data from one parameter to another and then delete the obsolete parameter.

**Comment by heinrichboldt** [comment]
Hi,

There is one way to rename Shared Parameter in Families, not in running projects


  *   open the Shared Parameter File and change the name of the Parameter.
  *   start a new blank Project.
  *   Load the renamed Shared Parameter in the project
  *   Load the Revit-family in the new project
  *   open the Family in Family-Browser or
  *   Right mous buttong on Family in the Project-browser "save as.."
  *   now is the shared parameter name changed in the Family.

this is my personal experience and we have changed hundred shared parameters in families from one language to another.

funny thing is, when using same GUID for different languages of Shared Parameter Files. When somebody load a Family from other language, the already inserted shared-parameter-name will be used.

Heinrich Boldt

mail: heinrich.boldt@hotmail.de

________________________________

**Comment by erfajo** [comment]
@heinrichboldt 
This is absolutely not something I can recommend, and I doubt strongly that Autodesk will accept this kind of workaround. If something goes wrong using this method, then you will be on your own.
There is drawbacks to that method you have not described, and that is if something goes wrongly, then is the project file and families destroyed. Therefore, this method should not be practiced by anyone.
