### ISSUE TITLE
File.LoadFamily

### ISSUE THREAD

**Issue by jahody** [erfajo/OrchidForDynamo#76]
### Revit, Dynamo and Orchid version
Revit: 2019.2
Dynamo: 2.0.3.8811
Orchid: 203.1.2.7410

### The issue
Is there a way how to use File.LoadFamily node for multiple rvt files at once?
I always have to use the node just for 1 single rvt file. 
![GRAPH](https://user-images.githubusercontent.com/44327558/81201577-47b44500-8f7a-11ea-9db2-32c826af1ba4.png)

Thank you

**Comment by erfajo** [comment]
I can se you get a null value for your background open... If you dont open a document, then is it not possible to load the family. 
could you please uploade the graph file?
rename the graph file by adding .txt to the filename, then is it possible to upload.

**Comment by jahody** [comment]
Thanks for the quick reply!
Please see the script below. I checked and I am using background open from your package, it works fine with a single rvt file.

[FAMILIES - LOAD INTO PROJECT.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4588245/FAMILIES.-.LOAD.INTO.PROJECT.dyn.txt)

**Comment by jahody** [comment]
Related - could you please publish this graph in a higher resolution?
https://4.bp.blogspot.com/-vC5ruuPJcxA/XJpdkCSOeOI/AAAAAAAAEP0/WPZljdkhvHwYVtxvqyZ-eJWBwFDpCjQbQCLcBGAs/s1600/Transfer-Copy.png

**Comment by erfajo** [comment]
aha now I get it.
You want a series of documents to be opened and then load the families into each document. In that case you need to use list level.
I presume this would work
![image](https://user-images.githubusercontent.com/2844374/81215806-2e42e580-8fda-11ea-8c53-8d8dc90521c8.png)

By the way, in my setting did the node open several documents.

**Comment by erfajo** [comment]
I will try to make a better resolution... asap :-)

**Comment by jahody** [comment]
Thanks! It looks like using list level helped (for Document.BackgroundOpen).
The only thing that doesn't work for me is the "watch" - the node shows that output is a list of 2, but when I expand it shows "null".
Overall the graph works, so I don't really mind...


![01](https://user-images.githubusercontent.com/44327558/81218505-257af100-8f93-11ea-9526-12eab2ab1f63.png)
![02](https://user-images.githubusercontent.com/44327558/81218507-26138780-8f93-11ea-896b-20e95d37d8d0.png)

Thanks a lot again! 
I am now working on the graph that would do the same with Categories (walls, floors...)

**Comment by erfajo** [comment]
Hmmm the backgroundopen node should not need list level!?

I know that your version is not the newest, however, I have not changed the background node the last 3-4 month. But it beats me why you need list level on that node in that position...
