### ISSUE TITLE
Set parameter for families in directory error

### ISSUE THREAD

**Issue by c-sowers** [erfajo/OrchidForDynamo#79]
Revit: 2019.2.2
Dynamo: 2.0.3.8811
Orchid: 203.1.2.7430

I have attempted to create a graph that will search through a set of families in a directory, find the units (i.e. IMPERIAL OR METRIC), and then add that into a text parameter in the family. I am using a separate Orchid graph to add the parameter first because it leads to fewer issues. However, I am running into a few issues with the Set Parameter node.

If I run the graph on a folder full of families where each family only contains a single type, then I get no error messages and the graph runs fine. If I run it on a folder with a family that has multiple types, then I get an error message in the set parameter node, but the files still save and the parameter is set. If I run the graph on a mixed folder (i.e. some families have multiple types and some only have one) then it will run until it reaches the first multi-type family, then it will get a warning on the set parameter node and stop running.

I couldn't figure out how to access the document files from the Orchid Open in Background node, so to get the Python to work, I am using the Orchid node in conjunction with the one from Rhythm (this was suggested by moderator on Dynamo Forum). My reference files are attached. Any help you can provide is really appreciated!

![Annotation 2020-05-12 214032](https://user-images.githubusercontent.com/65030929/81772855-c853d380-949b-11ea-8c4e-0a0826f95dd0.png)

[File_Family_FindUnits_AddtoParameter_200512.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/4619885/File_Family_FindUnits_AddtoParameter_200512.dyn.txt)

**Comment by erfajo** [comment]
Hmm... the error tells that the number of inputs are not the same, but as I see it, they look the same at the image. I will try to see the graph.

You mention _"I am using a separate Orchid graph to add the parameter first because it leads to fewer issues."_, what does that mean?

**Comment by erfajo** [comment]
try to add this before the setValue node
![image](https://user-images.githubusercontent.com/2844374/81783796-2b755280-94fc-11ea-8082-948cdbde93da.png)

**Comment by c-sowers** [comment]
@erfajo This appears to work. Thank you so much for your help! I really appreciate.

Regarding what I said earlier about the separate graph for adding the parameter: if I recall correctly, if the graph contained the add parameter and set in the same graph and then folder containing even one family with multiple types, then it wouldn't add the parameter or the units. If the parameter was already in place, then you get the behavior I described before.

**Comment by erfajo** [comment]
Sounds reasonable, I thought you meant something else, like you could not use my nodes together with other nodes, and that sounded strange :-)

**Comment by erfajo** [comment]
In the next build have I added more information to the warning.
