### ISSUE TITLE
Getting null values in getformula.value node!

### ISSUE THREAD

**Issue by ranierek** [erfajo/OrchidForDynamo#8]
Hi Erfajo!
Im having no results when in comes to extracting the formula value with your nodes.
the set.formulavalue node is ok, it did work but extracting the formula with getformula.value is not working at all.
it returns nulls values.

Ive tested the strings on and on to see if i did misstype. but misstypes result in empty lists and im getting nulls.
i also did create a standart family type based on other sollutions on the forum, but i get the same errors.

could you help me on this one brother?
the goal is to schedule all my fitting`s formulas in the piping template, cause they have "if" formulas containing multiple class codes and descriptions written inside the “code” and “description” parameters, and i need to change all that info.

Files:
https://drive.google.com/drive/folders/1WM8OaqWnihTCRHCG5K63UUkVgidbySsT?usp=sharing

![getvalue](https://user-images.githubusercontent.com/43645535/46531299-13931280-c873-11e8-8c02-c476459e6928.png)

**Comment by ranierek** [comment]
Mate, im sorry for the lack of politeness.. i was in a rush this afternoon!
i appreciate a lot your job and knowledge, as well as other tech contributors in the BIM and programming areas.. So ive come to you in this moment to seek some guidance! i'd be happy to somehow help you either.. this is very important for me!
thank you! farewell

**Comment by erfajo** [comment]
Thanks for this error report, It was rather easy to fix (took 2 min.) but I am working on a release so It would be nice if I could include it in this. If you need it very fast then can I make a "roll back" in my development and release this within some hours. I will release a version which work for you latest Sunday evening. If I can manage to release what I am working on then I will try to do that, otherwise will I just make a fix release.

**Comment by ranierek** [comment]
Erik! im glad to know it wasn't some dumb mistake of mine! And also glad for your attention on this..
Just take your time friend, i don't mind waiting a few days. Accomplishing the task manually would probably take months 🤕.
Please let me know when you got any news!

**Comment by erfajo** [comment]
I have released the update now, I made an incremental update so you can continue your work :-)

I also fixed something that could give you an error when running the graph.  
[GER_Coleta de formulas nas familias.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/2453702/GER_Coleta.de.formulas.nas.familias.dyn.txt)(remove txt from filename)  
![capture](https://user-images.githubusercontent.com/2844374/46579676-93a5ad80-ca16-11e8-85bc-0cdbf8190623.png)
