### ISSUE TITLE
wrong node description

### ISSUE THREAD

**Issue by Thomas84** [erfajo/OrchidForDynamo#83]
### Operating system
Windows 10

### Revit and Dynamo version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 2020.2
Dynamo: 2.3
Orchid: 230.0.1.7437

![image](https://user-images.githubusercontent.com/5624034/83349336-7385d900-a334-11ea-8a79-f5d827417e09.png)

The description should be "number to integer" or "number to integer"

**Comment by erfajo** [comment]
Thanks :-)
I will correct this... ToNumber might then have a wrong description as well, most likely the opposite error :-)
