### ISSUE TITLE
Warning: SharedParameter.Add operation failed.

### ISSUE THREAD

**Issue by cwd017** [erfajo/OrchidForDynamo#88]
### Revit, Dynamo and Orchid version
Revit: 2020.2
Dynamo: 2.3.0.8352
Orchid: 230.0.3

### The issue
Hello,
I am new to dynamo and wrote a script to automatically add shared parameters to a family. It is working perfectly on my computer, but it is not working on my coworkers computers. I go into the dynamo script to try and dissect whats going on and get the following warning.
![image](https://user-images.githubusercontent.com/68292187/87449775-3a8f8400-c5c3-11ea-8582-76b4eef309ca.png)
I wanted everything they needed to be accessible from the server. Everything (including the Orchid package) is on the server, which worked fine for me. I then tried repeating the process (including rewriting the script from scratch) on their hard drive (I created everything on my hard drive then uploaded everything to the server). I ensured all versions matched exactly what I was using and still no luck. I have been looking for how to fix this for a couple of days and have not been able to. I have also tried both installing Orchid using the installer provided, and by manually installing it.
Thank you in advance for the help.

**Comment by erfajo** [comment]
I will check asap, looks like it is a ressource issue there should be doable to verify rather fast
