### ISSUE TITLE
Issue with finding formulas and removing them

### ISSUE THREAD

**Issue by HC-Austin** [erfajo/OrchidForDynamo#9]
I am getting the below issue with the below build. We use many manufacturer made families, some provide families with parameters that need formulas removed so that I can capitalize them to match our standards. This code looks for families with formulas then removes them. Thanks

![image](https://user-images.githubusercontent.com/44181006/46982297-f6431d00-d098-11e8-8f92-5e099ba47839.png)
![capture](https://user-images.githubusercontent.com/44181006/46982305-fe02c180-d098-11e8-84ab-a510cb4bdf08.png)

**Comment by erfajo** [comment]
which version of Orchid do you use?
current version is x.3.5.6854 (x = 132 / 201)

**Comment by HC-Austin** [comment]
Thanks for the quick response. I have updated (I thought had before but my package path was different) and am now getting the below error.  
![image](https://user-images.githubusercontent.com/44181006/47026550-eff98300-d122-11e8-9714-3b2af4a70a73.png)

![image](https://user-images.githubusercontent.com/44181006/47026539-e8d27500-d122-11e8-9f77-cfd2ba7259ff.png)

**Comment by erfajo** [comment]
one major error as i see it, is that you "open" the same document parallel... you need to chain them so the docuemtns is only "open" in one node at the time! this is why I pass "document" both as input and output.
Next, what is the unigue node doing after the getdocument node? it seems very strange to place it there. lastly... so many passtrough nodes!? seems also very strange.
You could optimize your graph and gain much computational time as I see it. upload you graph, remaing it (add .txt) in the end, and I can try to show you how.

**Comment by HC-Austin** [comment]
Even if I try to run just one GetValue with the incoming documents I get the same error. 

The unique node is filtering out duplicate family documents to reduce the list by nearly 85%. We have many families that have multiple types so when the family type list is converted to family documents you get many duplicates. The unique before the get document wasn't doing anything and could be deleted. 

Speed isn't too much of an issue, I run this once near the beginning of the project and rarely ever again. 

Thanks for your assistance.

[Remove Formulas - Copy.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/2484119/Remove.Formulas.-.Copy.dyn.txt)

**Comment by HC-Austin** [comment]
Also, regarding the pass through nodes. I wanted to make sure that the upper set of code is completed before the bottom set of code. The bottom code capitalizes the parameters that just had the formulas removed. Probably not the cleanest way and maybe unnecessary but it has worked up until recently, seems to have broken when working in Revit 2018 and 2019. Thanks again

**Comment by HC-Austin** [comment]
I have also created this shortened code to test just removing all formulas from all families with the same error message. Thanks

![capture](https://user-images.githubusercontent.com/44181006/47043457-e8e66b00-d14a-11e8-8e80-45743aa40388.png)

**Comment by erfajo** [comment]
what really worries me, is when I open your dynamo file, none of the nodes that are not OOTB nodes is missing!? and when I read your dyn file in a text editor, then it looks ok...
what version of dynamo are you using?

**Comment by erfajo** [comment]
please try this...
[Remove_Formulas_erfajo.dyn.txt](https://github.com/erfajo/OrchidForDynamo/files/2486073/Remove_Formulas_erfajo.dyn.txt)
![capture](https://user-images.githubusercontent.com/2844374/47066558-d0c42980-d1e6-11e8-8964-c209234cf01f.png)

**Comment by HC-Austin** [comment]
I still had some issue with your code so I deleted all my Orchid files and reinstalled from scratch from the latest build you just posted. everything is working perfectly. Thank you for your assistance, got a bit of an education on what you can do with list inputs to simplify my codes as well.

**Comment by erfajo** [comment]
I noticed also some errors in your Dynamo graph file... it looked like migration wasn't doing what it was supposed to.

I was very close to release an update that included a range of nodes for printing, and in that, I tested the migration. However, there were no errors, so I would wait to see what your answer was. If your Orchid was from the installer version where you could select the installation location, then I know that this could give you an error, but it is so long time ago I change into an installer that located the files automatically, so I didn’t think that there was anyone left with the old installer anymore.
- I got that Idea from the Lunchbox installer, which also gets the install location automatically.

I am glad that a total removal/reinstallation solved the problem.

**Comment by HC-Austin** [comment]
I keep my package files located on a central office server so I dont have to update each computer's files individually. Once I copied the new install files over everything worked just great. Locating an install location would be convenient but now that I know that I need to do that I will make sure it happens in the future. Thanks again

**Comment by erfajo** [comment]
For those who know what they are doing are the new installer a bit annoying, but for the many has it become easiere :-)
