### ISSUE TITLE
Problem with Orchid-Installation 

### ISSUE THREAD

**Issue by dalijmal** [erfajo/OrchidForDynamo#90]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo, and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 20.0.0.377
Dynamo: 2.1.0.7500
Orchid: 0.0.2

### The issue
(Hello, I tried several times to install Orchid with almost all version available but none of them worked)
![Orchid](https://user-images.githubusercontent.com/68688556/88539643-ed270400-d011-11ea-922e-128b0442379c.JPG)

**Comment by erfajo** [comment]
You have not downloaded the installer, you have only downloaded the initial package from Dynamo package site. This package has only one purpose namely to bring users to my github to get my installer. I do not use the dynamo package site or package manager.
