### ISSUE TITLE
Load family for already open background documents

### ISSUE THREAD

**Issue by Vanman989** [erfajo/OrchidForDynamo#91]
Do you have a load family node for documents that are already open in the background? In my head it would look just like your File.LoadFamily but be feeding an open background document into it. Can you find nodes on your github that are coming out in the next release so you dont have to wait for it? I saw you had an updated purge unused which would be amazing right now :)

**Comment by erfajo** [comment]
sure, and in that case is it family.load (RevitProject.Elements). It has been there for some years. It came along with the node Document.LoadFamily (the old name is File.LoafFamily)

**Comment by Vanman989** [comment]
thanks for the reply. Still trying to understand this node. Is it possible to load one family from a file into multiple background open documents with this node? I might have poorly explained or would you be kind enough to show me an example?

**Comment by erfajo** [comment]
Hi I think what you are looking for is not supported by Revit or Dynamo. but I might be wrong.
My nodes handles either loading a family from a document or from inside a project to get familes (in this case are they closely related to how elements are handled). Trying to work on a range of documents opened in the background can only be done in the action where the document is opened, and then do whatever is needed. when the next document is openend, the you cant return to it. In other word try to see what you are able to do following this schema.

**Comment by Vanman989** [comment]
Thank you thats really useful. I'll try copy a family in from the open project I have to multiple open background documents. Unless I've misunderstood and thats not going to be possible either haha. Trying to figure out purging multiple documents and leaving with a specific title block as the starting view

**Comment by erfajo** [comment]
I think is is doable...
I have a graph which opens files from a location, but that could be from a current project. Opening these documents will be storred in memory as a list. Then in another branch can you open documents in the background and load the list of families into the current background opened document.
Try to combine from the sample collection "Elements/File+Fam-Load" and "Families/Collect families in project".

**Comment by Vanman989** [comment]
I'm just about there. Think I'm just lacking the nodes to change the starting view title block family or place a title block family in a background document. The title block family I want is already in the documents so just trying to change it before purging. Guess either or works.

**Comment by erfajo** [comment]
I can see that you are mixing a lot of nodes from many packages. Mixing nodes from different packages might course you problems. I have no idea how nodes other than the OOTB nodes works or what the output is from those nodes. You need to set "System.Type" node on the output and see if that matches the input requirements in the next node. I can see that my package along with the OOTB nodes should cover what you need, but I might be wrong. 
I am afraid I dont have the time to assist you as long as you are using nodes outside my domain. You have to rely on if anyone at Dynamobim forum can help you.

**Comment by Vanman989** [comment]
I gave it a good go with your nodes and some others but the creating or changing families in a background document just seems to be out of reach. Thanks for all your help. I'll keep a look out for anything new that can do this.

**Comment by Vanman989** [comment]
what package is the system.type node?

**Comment by erfajo** [comment]
Sorry it is named "Object.Type", and is a core node.
![image](https://user-images.githubusercontent.com/2844374/90040087-cdf1cd00-dcc7-11ea-91cb-ab67c949fb1b.png)
