### ISSUE TITLE
Create SharedParameters files

### ISSUE THREAD

**Issue by judufr** [erfajo/OrchidForDynamo#94]
### Operating system
(e.g. Windows 10)

### Revit and Dynamo version
Revit: 20
Dynamo: 2.3
Orchid: 230

### after control of the file, i see what the node create one wrong column like on the picture.

![image](https://user-images.githubusercontent.com/69672440/90232715-5fbf1e80-de1d-11ea-8474-8b6915a614aa.png)
![image](https://user-images.githubusercontent.com/69672440/90233103-e673fb80-de1d-11ea-8c67-77d9eea9a37c.png)

If i do the same script with just one value (no list), the file is ok.

Do you have solution?

Thank you very much in advance.
Julien

**Comment by erfajo** [comment]
First, I doubt you are dealing with scripts. It looks more like you are dealing with a graph. My work does support scripting via DesignScript or Python... but I doubt is it what you are asking for. So lets keep it to you have a problem with a graph.

As I see you image, you are not giving the node the needed input, so I am worried that you are not rejected with an error. I can see from the node that I have coded that I have a demand for the input, so how are you able to overrule that!?
The result is surely that you will get an error in the file, but you should never be able to end there, you should have been stopped with an error!?

Can I have the graph file, so I have a chance to build in the needed rejection of such insufficient input?

**Comment by judufr** [comment]
Hi,
First thank for your answer and you work for the good package.
It's a graphic, may be i use the wrong name.
I don't use python because i have find your good works for it and one example for to use your "create.sharedparameters".
But that create the little problem show and if i use directly the input of the node for the name, group and type the files is not broken but my list is mix.
I know the problem is me but i don't find my error.
For it (sorry it's better before), you can find the files and graphics in example. 
[SPFiles_create_test.zip](https://github.com/erfajo/OrchidForDynamo/files/5075617/SPFiles_create_test.zip)

Thank you in advance and sorry for my english.

**Comment by erfajo** [comment]
Thanks,
I will take a look at your graph, and figure how I can prevent user from running a graph without the needed requirements. 
I have samples in the sample collection how to use the node, try downloading this.

**Comment by judufr** [comment]
thank you for your understanding.
Regards.

**Comment by erfajo** [comment]
I have now tried to add code the node not to do anything if the input is not sufficient. However, in dynamo is is doable to use a node as a function and in your case have you managed to let the node work as a function. I will try to work on a solution where you will get an error if you try to do so, but at the moment I can only let the function end as something there does not give an error but in practice will it not do anything.

Please use the node as intended and not as a function. then I presume you will get the wanted result.
