### ISSUE TITLE
Searching for the "File.SaveFamily" node

### ISSUE THREAD

**Issue by CMSLdynamo123** [erfajo/OrchidForDynamo#95]
### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)

Revit: 2019
Dynamo: 2.0.3
Orchid: 200

### The issue

Hi, 

I am currently following an online tutorial to export project families to a project directory as per the youtube tutorial here - https://www.youtube.com/watch?v=DSTWGm95fQw 

The final step is to use the "File.SaveFamily" node which when I downloaded the example script indicated it was part of the Orchid package. After installing Orchid_200 for dynamo 2.0.3 with revit 2019 I can't seem to find the required node. 
I initially developed my own script based upon the youtube video as I wished to do some list manipulation prior to saving and could not find the node. 
After downloading the script provided in the aforementioned youtube link the node was described as unresolved, as shown in the screenshot. 

Has the name of this node
![orchid file family save](https://user-images.githubusercontent.com/69853351/90516147-7fc34a80-e15b-11ea-9f61-29783efb72a0.png)
 changed or does the version I am using not contain this node? 

Any help is greatly appreciated.

Best regards

[Export all project families to sub category folders.zip](https://github.com/erfajo/OrchidForDynamo/files/5090529/Export.all.project.families.to.sub.category.folders.zip)

**Comment by erfajo** [comment]
The node has been renamed. I am sorry that migration does not work in dynamo 2.x versions. It works in dynamo 1.3 versions... but it is an issue the dynamo team has to solve.
the node is named "Family.Save" now. The below image is from my sample collection
![Family Save](https://user-images.githubusercontent.com/2844374/90524391-4cd68200-e16e-11ea-842a-6a89bca1ee98.png)

By the way, have you tried to feed the node without changing elements into family? The output from the element node should be a family but I an not sure...
![image](https://user-images.githubusercontent.com/2844374/90524886-e3a33e80-e16e-11ea-81e9-a7841a24ef7d.png)

**Comment by CMSLdynamo123** [comment]
Hi, 

Thank you very much for your speedy reply this is exactly the node I was looking for. 
Also you are correct, it seems now this node accepts family instead of a string so this part of the script was after all irrelevant. 

I encountered another problem where the pre-loaded families in my project that I cannot purge give the error "Warning: Family.Save operation failed. This family is not editable. Parameter name: loadedFamily"

These families include mullions, section heads, slipt joints etc however I didn't actually want these to be exported in the first place as they are unused in my project. If I drop them from the start of the list to give a list of families I have placed myself the node works perfectly fine and does exactly what I am looking for, so thanks! :)  

I've attached 2 screenshots in case you are interested. 

![orchid file family save 2 ](https://user-images.githubusercontent.com/69853351/90530654-0af90c00-e16d-11ea-8d7d-73be238140a7.png)
![orchid file family save 3 ](https://user-images.githubusercontent.com/69853351/90530661-0c2a3900-e16d-11ea-8566-caa40f6afd0a.png)

**Comment by erfajo** [comment]
First, do only use the camera upper right corner, and zoom into some nodes, then will the camera give you alle nodes ind that resolution.

next, system families cannot be edited, so you need to filter those out.

**Comment by erfajo** [comment]
This issue is 2 years old and many things has changed since.
one is that I now "edit" the family in memory and by doing this the output become a document, and then you can just save the document. In other words is one node replaced by two nodes, however, by doing this you will be able to do several things with the family before saving. that was not an option with the old node.

the below is from my sample collection
![Collect families in project](https://user-images.githubusercontent.com/2844374/194360650-702ef770-c685-429e-acca-fdb6800055cf.png)

**Comment by jptrujillol** [comment]
It should be something related with my installation as I can´t find Family.Edit node. I´m using 206 version for revit 21 and dynamo 2.5 and Installed Orchid manually
![image](https://user-images.githubusercontent.com/20504048/194424735-cc8500e6-be9a-4378-9850-93443eec5a0b.png)
