### ISSUE TITLE
Parameter.SetValue "Collection was of a fixed size."

### ISSUE THREAD

**Issue by Crapai** [erfajo/OrchidForDynamo#96]
### Operating system
Windows 10

### Revit and Dynamo version
Revit: 2020.2
Dynamo: 2.3.0.8352
Orchid: 230.0.1.7311

The Parameter.SetValue is not setting values for me. It is coming up with this warning, "Warning: Parameter.SetValue operation failed. Collection was of a fixed size." I've tried looking around forms for this warning but haven't been able to find it anywhere.

This has worked before and it looks like is should work now. Every other part of it seems to be working.

![image](https://user-images.githubusercontent.com/50451766/92133290-353a0300-edd6-11ea-80d0-82fb45502f41.png)

![image](https://user-images.githubusercontent.com/50451766/92133349-43881f00-edd6-11ea-82e1-ab89678f9f28.png)

**Comment by erfajo** [comment]
Sounds good you figured it by yourself :-)
