### ISSUE TITLE
Papersize from printer - But as a list

### ISSUE THREAD

**Issue by HDU91** [erfajo/OrchidForDynamo#97]
Hey Eric. 
First of all love our Orchid Package it's great.

I would like to suggest if it's possible to get a version of the node "PaperSizes" as a complete list of papersizes from the selected printer, It would help my automated pdf-print script a lot.

Hope I posted this the correct place, first time using Github, if not i'm sorry.

Henrik
DK

![DYN - Papersizes](https://user-images.githubusercontent.com/74551787/99267810-b6753380-2824-11eb-9ea4-7fe019d7aa77.JPG)

**Comment by erfajo** [comment]
Thanks for the suggestion, I will make such a node at next release. I will post here when that happens so you can update.

**Comment by erfajo** [comment]
It took minutes to make... it will look like the below. However, I have to do some testing for other things I have built before I can release.
![image](https://user-images.githubusercontent.com/2844374/99362735-241c7080-28b4-11eb-88a1-6f5d94026c9a.png)

**Comment by HDU91** [comment]
Hey Eric.
That's awesome looks great! Sure np! And thank you :-)
Henrik
DK

**Comment by erfajo** [comment]
The testing went rather fast since I was doing tests on the things I have been building for this release. I only needed a few tests and then this new node. So the new node you asked for is being released with many other new and updated nodes. Primarily updated internally with more efficient code.

**Comment by HDU91** [comment]
Super It works perfectly thanks Erik!
