### ISSUE TITLE
Installer contains virus/malware

### ISSUE THREAD

**Issue by BIMMan** [erfajo/OrchidForDynamo#98]
SecureAge APEX

Malicious
Cybereason

Malicious.5d2fe6
Cynet

Malicious (score: 100)
McAfee-GW-Edition

BehavesLike.Win32.CSDIMonetize.wc
Qihoo-360

HEUR/QVM05.1.5972.Malware.Gen
Sangfor Engine Zero

Malware

**Comment by erfajo** [comment]
No, it does not contain any malware, however, I have built-in a procedure to watch if Revit runs or not. If it does it will close down Revit before continuing the installation process.
If you want to skip this, then go to manually installation, then you can do whatever you want.

**Comment by BIMMan** [comment]
Sorry but when I scanned the exe file online it gave me this result on my post. Coincidentally or not hours after the installation on RDS the CPU on the server was on 100%, rendering it nearly unusable. Could you run a virus check on your exe held here?

**Comment by erfajo** [comment]
We have an very excellent virus scanner at Technical University of Denmark, I have no warnings none what so ever concerning anything, and for internally installation do we ship the software I built with a certificate. Externally is it shipped as is, it is freeware and the installer is meant for common installation without any support. Anyone can install it manually if they want to verify anything, you should be able to test it this way as you please.
