### ISSUE TITLE
Orchid 260 not installing + Orchid_260_Core.zip & Orchid_260_Revit.zip have no content in dyf folder

### ISSUE THREAD

**Issue by LPav66** [erfajo/OrchidForDynamo#99]
### How to get help...
I will try to assist you as best as possible. One way to do that is by answering your questions. But to get the right answer, you’ll first have to ask your question in the right way. Although I will try my best, there are things you can do to improve your chances of getting good and quick answers. Below you will find some suggestions on how to achieve that. Do not think of these suggestions as rules and especially do not take them as a guarantee of getting an answer.

1. Choose a descriptive title for your post
2. Be succinct but clear in your wording
3. Attach minimal versions of all the relevant files
4. Include a detailed image or sketch if it makes sense
5. Include links to online resources if possible
6. Create new topics rather than continuing old ones
7. This is not a ‘do my work for me’ assistance
8. Search is your friend, try first to see if your issue is handled in the samples
9. If your problem has been solved, mark the post as solved.

For further information, and an in-depth description of the points, please follow these guidelines
https://forum.dynamobim.com/t/how-to-get-help-on-the-dynamo-forums/4677

_Please delete this line and the above, and start describing your issue._

### Revit, Dynamo and Orchid version
(_Which version of Revit, Dynamo and Orchid are you using? Go to Help > About if you're not sure. for Orchid version, go to Packages > Manage Packages_)
Revit: 21.0.0.383
Dynamo Core: 2.5.0.7460
Dynamo Revit: 2.5.0.7586
Orchid: 260

### The issue
Orchid 260 not installing + Orchid_260_Core.zip & Orchid_260_Revit.zip have no content in dyf folder:

Hello Erfajo,

I've downloaded OrchidForDynamo_260.exe from Github and runned it.
It would not appear on the library bar.
![immagine](https://user-images.githubusercontent.com/42032849/99848393-fec08880-2b79-11eb-89bf-2ecf7cf2e48c.png)

Although it was registered on "Manage Nodes and Packages Paths" window
![immagine](https://user-images.githubusercontent.com/42032849/99848701-8908ec80-2b7a-11eb-8dc9-2d6f9de3294b.png)

As you can see, the folder created during the installation is empty:
![immagine](https://user-images.githubusercontent.com/42032849/99848987-092f5200-2b7b-11eb-8d50-cbf5b0e185bd.png)

At this point I decided to download the  zipped files an to install Orchid manually, but to my surprise in both Orchid_260_Core.zip and Orchid_260_Revit.zip the dyf folders are empty.
![immagine](https://user-images.githubusercontent.com/42032849/99849392-ca4dcc00-2b7b-11eb-8db4-8bbd9cf71cac.png)

![immagine](https://user-images.githubusercontent.com/42032849/99849882-a17a0680-2b7c-11eb-93b7-43e46717eb57.png)

Now I really don`t know what to do further to have Orchid installed and I would be really thankful for any help.
I`m really clueless.

Thanks in advance!

**Comment by erfajo** [comment]
The dyf folder should be totally empty, since I have no custom nodes. they are all placed inside the assembly files. The only thing you need to do is unpack the zip files and place them in the directory dynamo reads. Try also to see the description for error handling, the link is posted at the main page.

**Comment by LPav66** [comment]
Thank you!
